### ISSUE TITLE
[Node.js] "choice.trim is not a function"

### ISSUE THREAD

**Issue by ziggy42** [Microsoft/BotBuilder#1195]
I've done something like this:
```
const list = [1,2,3]
builder.Prompts.choice(session, "a string", list)
```

Now, whatever I write I get:
```
TypeError: choice.trim is not a function
    at /mnt/app/node_modules/botbuilder/lib/dialogs/EntityRecognizer.js:157:32
    at Array.forEach (native)
    at Function.EntityRecognizer.findAllMatches (/mnt/app/node_modules/botbuilder/lib/dialogs/EntityRecognizer.js:155:49)
    at Function.EntityRecognizer.findBestMatch (/mnt/app/node_modules/botbuilder/lib/dialogs/EntityRecognizer.js:142:40)
    at SimplePromptRecognizer.recognize (/mnt/app/node_modules/botbuilder/lib/dialogs/Prompts.js:72:54)
    at Prompts.recognize (/mnt/app/node_modules/botbuilder/lib/dialogs/Prompts.js:141:36)
    at Session.recognizeCurDialog (/mnt/app/node_modules/botbuilder/lib/Session.js:422:20)
    at Session.routeMessage (/mnt/app/node_modules/botbuilder/lib/Session.js:385:18)
    at next (/mnt/app/node_modules/botbuilder/lib/Session.js:45:23)
    at botbuilder (/mnt/app/node_modules/botbuilder/lib/middleware/Middleware.js:53:21)
```

I know the third param should be a string array but unfortunately list comes from another service and I didn't realize it was actually an int array...

**Comment by muzahmed** [comment]
@ziggy42 another good find! i'll fix and push shortly, we should have a new version out pretty soon!

**Comment by ziggy42** [comment]
I have 2 telegram accounts stuck in a loop now :smiley: I'm running out of sims :smile:
