### ISSUE TITLE
Error when Android Skype client user sends attachment to Skype Bot

### ISSUE THREAD

**Issue by bostondv** [Microsoft/BotBuilder#123]
While using Skype for Android and sending an attachment (PNG image) to a Node.js Skype bot an error occurs in the bot.

Using latest Skype for Android with Android 6.0.

```
Error: Incoming webhooks request was invalid, errors: IncomingAttachment.name must not be empty or whitespaces only, request: [{"type":"Image","id":"0-cus-d1-6a58a41c1d14529ebc39bc297065f236","name":"","views":[{"viewId":"original"}],"activity":"attachment","from":"8:bostondv","to":"28:ad3e98f4-848b-4879-b4cc-f88d8d14c2a9","time":"2016-04-16T12:17:28.197Z"}]
    at fromError (/Users/bostondv/Dev/pamfax/skype-bot/node_modules/skype-sdk/lib/messaging/messaging-service-request-processor-v2.js:74:47)
    at Object.processRequestData (/Users/bostondv/Dev/pamfax/skype-bot/node_modules/skype-sdk/lib/messaging/messaging-service-request-processor-v2.js:117:24)
    at MessagingService.processRequest (/Users/bostondv/Dev/pamfax/skype-bot/node_modules/skype-sdk/lib/messaging/messaging-service.js:181:40)
    at BotService.processMessagingRequest (/Users/bostondv/Dev/pamfax/skype-bot/node_modules/skype-sdk/lib/bot-service.js:250:38)
    at IncomingMessage.<anonymous> (/Users/bostondv/Dev/pamfax/skype-bot/node_modules/skype-sdk/lib/utils/messaging-handler.js:33:28)
    at emitNone (events.js:80:13)
    at IncomingMessage.emit (events.js:179:7)
    at endReadableNT (_stream_readable.js:913:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by Stevenic** [comment]
It looks like this is on the Skype side of things and unlikely to have anything to do with the node part of your bot. It looks like the attachment name is missing or something. In any case you'll want to report the bug to Skype from their developer dashboard.

**Comment by bostondv** [comment]
Thanks I'll report it to them!

**Comment by Stevenic** [comment]
Reopen the issue if you need to followup.

**Comment by bostondv** [comment]
FYI, here's the ticket posted to Skype: https://connect.microsoft.com/UCDEV/feedback/details/2605057/error-sending-attachment-to-skype-bot-using-skype-for-android
