### ISSUE TITLE
User API 404

### ISSUE THREAD

**Issue by loicbar** [Microsoft/BotBuilder#1241]
HI,

I'm trying to do a simple bot but when using the Bot Framework Emulator to call the API, the server throw an error : 
node app.js
restify listening to http://[::]:3978
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
Error: Request to 'http://localhost:3978/v3/botstate/emulator/users/2c1c7fa3' failed: [404] Not Found
    at Request._callback (c:\Workplace\Projects\ugo\node_modules\botbuilder\lib\bots\ChatConnector.js:410:46)
    at Request.self.callback (c:\Workplace\Projects\ugo\node_modules\botbuilder\node_modules\request\request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (c:\Workplace\Projects\ugo\node_modules\botbuilder\node_modules\request\request.js:1044:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (c:\Workplace\Projects\ugo\node_modules\botbuilder\node_modules\request\request.js:965:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)

Seems weird to me?

**Comment by dandriscoll** [comment]
Hi @loicbar, it looks like you have the Emulator configured to advertise the emulator's state service to be on the same port as your bot. You need to have different ports in the "Bot Url" and "Emulator Url" fields.

**Comment by Andrea-Orimoto** [comment]
@loicbar closing this issue as it seems to be addressed by dan's answer. If not feel free to reopen, and we'll look into it. Thanks!

**Comment by juhamust** [comment]
Hmm. I'm getting the same error but from `api.botframework.com` domain documented in here (even if I believe the channelId and userId are correct): https://docs.botframework.com/en-us/core-concepts/userdata/#navtitle

I'm assuming the api.botframework.com should be used instead of bot implementation?

Snippet from my code:
`https://api.botframework.com/v3/botstate/${data.channelId}/users/${data.user.id}`
