### ISSUE TITLE
Error trying to install Bot Framework Channel Emulator

### ISSUE THREAD

**Issue by jockorob** [Microsoft/BotBuilder#1304]
PLATFORM VERSION INFO
	Windows 			: 10.0.10586.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1078.0 built by: NETFXREL3STAGE
	clr.dll 			: 4.6.1080.0 built by: NETFXREL3STAGE
	dfdll.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.10586.0 (th2_release.151029-1700)

SOURCES
	Deployment url			: http://download.botframework.com/bf-v3/tools/emulator/Bot%20Framework%20Channel%20Emulator.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://download.botframework.com/bf-v3/tools/emulator/Bot%20Framework%20Channel%20Emulator.application resulted in exception. Following failure messages were detected:
		+ Exception reading manifest from http://download.botframework.com/bf-v3/tools/emulator/Bot%20Framework%20Channel%20Emulator.application: the manifest may not be valid or the file could not be opened.
		+ DTD is prohibited in this XML document.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [9/22/2016 9:40:54 AM] : Activation of http://download.botframework.com/bf-v3/tools/emulator/Bot%20Framework%20Channel%20Emulator.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [9/22/2016 9:40:55 AM] System.Deployment.Application.InvalidDeploymentException (ManifestParse)
		- Exception reading manifest from http://download.botframework.com/bf-v3/tools/emulator/Bot%20Framework%20Channel%20Emulator.application: the manifest may not be valid or the file could not be opened.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirectBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Xml.XmlException
		- DTD is prohibited in this XML document.
		- Source: System.Xml
		- Stack trace:
			at System.Xml.XmlTextReaderImpl.Throw(Exception e)
			at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
			at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
			at System.Deployment.Application.ManifestValidatingReader.XmlFilteredReader.Read()
			at System.Xml.XsdValidatingReader.Read()
			at System.Deployment.Application.ManifestReader.FromDocument(String localPath, ManifestType manifestType, Uri sourceUri)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by Andrea-Orimoto** [comment]
@jockorob  it looks like the most common problem related to this type of error is that the manifest doesn't get downloaded for some reason. I'm seeing that the install path we provide is http, but the server enforces https via internal redirect, and I'm wondering if somehow that could be an issue in some situations.

are you behind a firewall? if yes can you try from another location?
what browser are you doing this from? with what add ons? can you try changing browser?

**Comment by Andrea-Orimoto** [comment]
@jockorob are you still having this issue?

**Comment by jockorob** [comment]
No it just got it resolved.  I am behind a firewall.  Originally, I had white listed https://download.botframework.com:443 but not http://download.botframework.com/.  Once I got the IT guy to white list the second link as well it worked.  Thanks for the help.

**Comment by Andrea-Orimoto** [comment]
Great, thanks for confirming!
