### ISSUE TITLE
Skype HeroCard limitations

### ISSUE THREAD

**Issue by ashfaq-uddin** [Microsoft/BotBuilder#1310]
I noticed there are some limitations. The maximum number is 5. I get an exception 

`Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1fzuLIfgVsDSM17Cfmy1HETSPj5uqrcmBxBl4KnjyrgI/activities' failed: [400] Bad Request
    at Request._callback (D:\code\bots\Deals\node_modules\botbuilder\lib\bots\ChatConnector.js:410:46)
    at Request.self.callback (D:\code\bots\Deals\node_modules\request\request.js:187:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\code\bots\Deals\node_modules\request\request.js:1048:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\code\bots\Deals\node_modules\request\request.js:969:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)`

-

**Comment by Andrea-Orimoto** [comment]
Hi @ashfaq-uddin, you are right, there is a limit of 5 in skype, it is documented in the readme of this sample https://github.com/Microsoft/BotBuilder-Samples/tree/master/CSharp/cards-CarouselCards. Let us know if you have any more questions.
