### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by skyrpex** [Microsoft/BotBuilder#1386]
Hi there,

we got two servers (one with apache and one with nginx). Both serve the same certificate. When I use the nginx endpoint, the `Test connection to your bot` button gives this error:

> 500 InternalServerError
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Intercom.DevPortal.Server.Controllers.BotManagerController.<PingV3BotAsync>d__72.MoveNext() in C:\a\1\s\DevPortalLib\Controllers\BotManagerController.cs:line 1926

Any insights? Thanks.

**Comment by Maarten88** [comment]
HTTP/2.0 maybe? I've had "funny" problems simply connecting to IIS on Windows 10 from Chrome, caused by incompatible SSL algorithms under with HTTP/2.0.
