### ISSUE TITLE
Typing exception

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#1512]
Hi!

We got an exception

```
Microsoft.Rest.HttpOperationException: Operation returned an invalid status code 'NoContent'
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__7.MoveNext() in c:\Projects\GitHub\BotBuilder-NuGet3.2.1\CSharp\Library\Microsoft.Bot.Connector\ConnectorAPI\Conversations.cs:line 717
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__15.MoveNext() in c:\Projects\GitHub\BotBuilder-NuGet3.2.1\CSharp\Library\Microsoft.Bot.Connector\ConnectorAPI\ConversationsExtensions.cs:line 248
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.AlwaysSendDirect_BotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__4.MoveNext() in c:\Projects\GitHub\BotBuilder-NuGet3.2.1\CSharp\Library\Dialogs\BotToUser.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogContext.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__10.MoveNext() in c:\Projects\GitHub\BotBuilder-NuGet3.2.1\CSharp\Library\Dialogs\DialogContext.cs:line 83
```

when sent a typing activity

```
        public static async Task TypingAsync(this IDialogContext context)
        {
            IMessageActivity typing = context.MakeMessage();
            typing.Type = ActivityTypes.Typing;
            await context.PostAsync(typing);
        }
```

Previously everything worked :(

**Comment by darrenjefford** [comment]
Is there a workaround for this issue ahead of the bug being fixed? Thanks

**Comment by tomlm** [comment]
I believe this should be fixed now, but the workaround is to add try/catch around it to catch the exception.

**Comment by darrenjefford** [comment]
Yes, all fixed in the latest release. Thanks
