### ISSUE TITLE
Long choice prompt to Facebook caused 500 internal error 

### ISSUE THREAD

**Issue by bobzsj87** [Microsoft/BotBuilder#1525]
My choices are: Mon-Fri (10:30AM-12:00PM/3:00PM-4:30PM), Mo-Fri 8:00am-10:00am/1:00pm-6:00pm, Sat-Sun 9:00am-5:00pm

And got the following error:

```
2016-10-26T11:32:01.440413+00:00 app[web.1]: Error: Request to 'https://facebook.botframework.com/v3/conversations/1114121145321679-332410020435755/activities/mid.1477481519630%3A619b82f468' failed: [500] Internal Server Error
2016-10-26T11:32:01.440430+00:00 app[web.1]:     at Request._callback (/app/node_modules/botbuilder/lib/bots/ChatConnector.js:410:46)
2016-10-26T11:32:01.440431+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:186:22)
2016-10-26T11:32:01.440432+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2016-10-26T11:32:01.440433+00:00 app[web.1]:     at Request.emit (events.js:191:7)
2016-10-26T11:32:01.440434+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1060:10)
2016-10-26T11:32:01.440434+00:00 app[web.1]:     at emitOne (events.js:96:13)
2016-10-26T11:32:01.440435+00:00 app[web.1]:     at Request.emit (events.js:188:7)
2016-10-26T11:32:01.440436+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:980:12)
2016-10-26T11:32:01.440436+00:00 app[web.1]:     at IncomingMessage.g (events.js:286:16)
2016-10-26T11:32:01.440437+00:00 app[web.1]:     at emitNone (events.js:91:20)
2016-10-26T11:32:01.440438+00:00 app[web.1]:     at IncomingMessage.emit (events.js:185:7)
2016-10-26T11:32:01.440439+00:00 app[web.1]:     at endReadableNT (_stream_readable.js:934:12)
2016-10-26T11:32:01.440439+00:00 app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:74:11)
2016-10-26T11:32:01.440440+00:00 app[web.1]:     at process._tickDomainCallback (internal/process/next_tick.js:122:9)

```

[update]: facebook quick reply has a "title has a 20 character limit". I manually detect for those >20 and specify "list" as listStyle. But should be automatic.

**Comment by digitallawyer** [comment]
Also running into this issue. Thanks for looking into it! 👍
