### ISSUE TITLE
Passing in FormDialog defaults from LuisDialog

### ISSUE THREAD

**Issue by jsiegmund** [Microsoft/BotBuilder#158]
I'm trying to mix & match dialogs to support querying the user for information. I have a LuisDialog which gets the intent from the user. One of the parameters is "Customer name", which of course can be one out of many. Sometimes Luis fails to get the correct customer name out of the sentence and that entity is left empty. In this case, I want to provide the user with a couple of choices, for which I want to use a FormDialog. 

So within the Luis Dialog, I check whether the customer name has been filled and when it isn't I call:

> context.Call<BookHours>(new FormDialog<BookHours>(new BookHours()
>                     {
>                         Date = date.Value,
>                         Hours = hours
>                     }, options: FormOptions.PromptInStart), BookHours);
>                     return;
> 

The BookHours class looks like this: 

> [Serializable]
public class BookHours
{
    public Customers Customer { get; set; }
    [Microsoft.Bot.Builder.FormFlow.Prompt(AllowDefault = Microsoft.Bot.Builder.FormFlow.BoolDefault.True)]
    public DateTime Date { get; set; }
    [Microsoft.Bot.Builder.FormFlow.Prompt(AllowDefault = Microsoft.Bot.Builder.FormFlow.BoolDefault.True)]
    public double Hours { get; set; }
}

The BookHours return method looks like: 

> public async Task BookHours(IDialogContext context, IAwaitable<BookHours> record)
> {
>    BookHours hoursRecord = await record;
>    await RegisterHours(context, hoursRecord);
> }

The rest of the code isn't relevant I think.

The idea works; I get the BookHours dialog and select a customer (these are now hard-coded from an enum, will become dynamic later on). But when I now return to the BookHours method, the await for the record object fails. Error thrown: 

_Index was outside the bounds of the array._

This happens on line 209 of Fiber.cs:
`var next = await leaf.PollAsync(this);`

Here's the complete stacktrace as well:

>    at Microsoft.Bot.Builder.Internals.Fibers.Wait`1.Microsoft.Bot.Builder.Internals.Fibers.IAwaiter<T>.GetResult() in G:\Sources\github\BotBuilder\CSharp\Library\Fibers\Wait.cs:line 321
   at Luc.Dialogs.IntelligentDialog.<BookHours>d__9.MoveNext() in G:\Sources\js\Luc\Luc\Dialogs\IntelligentDialog.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogContext.ThunkResume`1.<Rest>d__3.MoveNext() in G:\Sources\github\BotBuilder\CSharp\Library\Dialogs\DialogContext.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`1.<Microsoft-Bot-Builder-Internals-Fibers-IWait-PollAsync>d__19.MoveNext() in G:\Sources\github\BotBuilder\CSharp\Library\Fibers\Wait.cs:line 242
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.Internals.Fibers.Frame.<Microsoft-Bot-Builder-Internals-Fibers-IFrameLoop-PollAsync>d__7.MoveNext() in G:\Sources\github\BotBuilder\CSharp\Library\Fibers\Fiber.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.Internals.Fibers.Fiber.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop-PollAsync>d__10.MoveNext() in G:\Sources\github\BotBuilder\CSharp\Library\Fibers\Fiber.cs:line 209

I'm well aware that I might not be on the right track of how to combine these dialogs, but I couldn't find anything better yet. So please let me know when I can solve things in a different (better) way.

**Comment by willportnoy** [comment]
The original exception seems to be "Index was outside the bounds of the array".

This exception doesn't actually originate from the call to leaf.PollAsync (i.e. there is no array there) - that method call is propagating an earlier exception.

Can you have you debugger break on the original, thrown exception, so we can see where it is?  I suspect it's in the form filling before BookHours.

**Comment by willportnoy** [comment]
I'm going to close this item for now, but feel free to reopen with more information.

**Comment by jsiegmund** [comment]
Sorry, was out of town for a couple of days. Here's the stacktrace for the exception thrown: 

`   at Microsoft.Bot.Builder.Internals.Fibers.Wait`1.Microsoft.Bot.Builder.Internals.Fibers.IAwaiter<T>.GetResult() in G:\Sources\github\BotBuilder\CSharp\Library\Fibers\Wait.cs:line 321
   at Luc.Dialogs.IntelligentDialog.<BookHours>d__9.MoveNext() in G:\Sources\js\Luc\Luc\Dialogs\IntelligentDialog.cs:line 107
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogContext.ThunkResume`1.<Rest>d__3.MoveNext() in G:\Sources\github\BotBuilder\CSharp\Library\Dialogs\DialogContext.cs:line 138
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`1.<Microsoft-Bot-Builder-Internals-Fibers-IWait-PollAsync>d__19.MoveNext() in G:\Sources\github\BotBuilder\CSharp\Library\Fibers\Wait.cs:line 242
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.Internals.Fibers.Frame.<Microsoft-Bot-Builder-Internals-Fibers-IFrameLoop-PollAsync>d__7.MoveNext() in G:\Sources\github\BotBuilder\CSharp\Library\Fibers\Fiber.cs:line 113
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Builder.Internals.Fibers.Fiber.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop-PollAsync>d__10.MoveNext() in G:\Sources\github\BotBuilder\CSharp\Library\Fibers\Fiber.cs:line 209`
