### ISSUE TITLE
Error: Request to 'https://skype.botframework.com/v3/conversations/asd/activities' failed: [500] Internal Server Error

### ISSUE THREAD

**Issue by mmulesa** [Microsoft/BotBuilder#1584]
Hi, when the application (echo bot from example) is running in azure, occasionally an error 500.
Not in cloud the application works correctly.
If the botframework can block IP?
Outgoing IP in the azure cloud - 13.84.47.22,13.84.43.108,13.84.44.175,13.84.40.119

Error: Request to 'https://skype.botframework.com/v3/conversations/asd/activities' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:413:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

**Comment by tomlm** [comment]
asd is not a valid skype conversationId.  Look at the url, I don't think that is correct.

**Comment by mmulesa** [comment]
It is just a shortcut links

Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1gN1zxKfwlVUvXPzlvD5MW2-TaxrH5V0A2yu4WajD9PU/activities' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:413:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

**Comment by mmulesa** [comment]
It is just a shortcut links

Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1gN1zxKfwlVUvXPzlvD5MW2-TaxrH5V0A2yu4WajD9PU/activities' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:413:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

**Comment by DSRoden** [comment]
I am getting the same error following a status 200 on an incoming message via a skype test bot. 

Error: Request to 'https://skype.botframework.com/v3/conversations/.../activities' failed: [500] Internal Server Error

**Comment by vijaymishra13** [comment]
I am getting same error on Azure. It's working fine from web-client but fails for Skype.

Error: Request to 'https://smba.trafficmanager.net/v3/conversations/29%.../activities' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:435:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

**Comment by dharamgoyal** [comment]
I am getting Bad format of conversation ID
POST method
https://skype.botframework.com/v3/conversations/3UTNld2Vr7GKqwhPeUEEpf/activities
jsonBody{
  {
    "type": "message",
    "from": {
        "id": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "name": "Standup Alice"
    },
    "conversation": {
        "id": "57OrEnePMU3JmNTszfgBJ3",
        "name": "News Alert"
   },
   "recipient": {
        "id": "xxxxxxxxxxxxx",
        "name": "Bao"
    },
  "channelId": "skype",
    "text": "My bot's reply"
}
}

Please let me know what i am doing wrong.
