### ISSUE TITLE
[500] Internal Server Error - from some ip of azure

### ISSUE THREAD

**Issue by mmulesa** [Microsoft/BotBuilder#1590]
Hi, 
web application (echo bot from example) deployed in a cloud of Azurе. The application outgoing ip 13.84.47.22,13.84.43.108,13.84.44.175,13.84.40.119.

13.84.47.22 - work fine
but when ip 13.84.44.175, I have 500 error

Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1gN1zxKfwlVUvXPzlvD5MW2-TaxrH5V0A2yu4WajD9PU/activities' failed: [500] Internal Server Error
at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:413:46)
at Request.self.callback (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:186:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request. (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:1060:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage. (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:980:12)
at IncomingMessage.g (events.js:291:16)
at emitNone (events.js:91:20)

**Comment by tomlm** [comment]
I looked in the logs and see no requests with that conversationId.  Are you saying it is only failing from one particular instance of your bot?

**Comment by mmulesa** [comment]
Yes, it's from two different copies at the moment is "App ID f06a57bb-83a8-4da8-bba1-a3917e46ed69". Since applications are deployed as a web application in the cloud Azure. Have a different outbound IP addresses (13.84.47.22,13.84.43.108,13.84.44.175,13.84.40.119). So when the balancer microsoft substitutes address 13.84.44.175 - botframwork return error 500.

**Comment by mmulesa** [comment]
five minutes ago

Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1gN1zxKfwlVUvXPzlvD5MW2-TaxrH5V0A2yu4WajD9PU/activities' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:413:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1gN1zxKfwlVUvXPzlvD5MW2-TaxrH5V0A2yu4WajD9PU/activities' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:413:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1gN1zxKfwlVUvXPzlvD5MW2-TaxrH5V0A2yu4WajD9PU/activities' failed: [500] Internal Server Error
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:413:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:1060:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\request\request.js:980:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

**Comment by chrimc62** [comment]
@mmulesa are you still having this issue?

**Comment by mmulesa** [comment]
@chrimc62 Hi, now there are no errors

**Comment by dandriscoll** [comment]
Closing issue as resolved
