### ISSUE TITLE
SurrogateLogDecorator is not thread-safe

### ISSUE THREAD

**Issue by MateuszGallus** [Microsoft/BotBuilder#1592]
SurrogateLogDecorator has field 'visited' of type  HashSet<Type>. Hashsets are not thread-safe, and SurrogateLogDecorator lifetime scope is set to SingleInstance. I have some integration test that emulates multithreaded environment. This test from time to time fails because of exception:

System.NullReferenceException: Object reference not set to an instance of an object. 

   at System.Collections.Generic.HashSet`1.AddIfNotPresent(T value) 
   at System.Collections.Generic.HashSet`1.Add(T item) 
   at Microsoft.Bot.Builder.Internals.Fibers.Serialization.SurrogateLogDecorator.Visit(Object obj) 
   at Microsoft.Bot.Builder.Internals.Fibers.Serialization.SurrogateLogDecorator.System.Runtime.Serialization.ISerializationSurrogate.GetObjectData(Object obj, SerializationInfo info, StreamingContext context)

   at System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(Object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder)

   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(WriteObjectInfo objectInfo, NameInfo memberNameInfo, NameInfo typeNameInfo)

   at System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(Object graph, Header[] inHeaders, __BinaryWriter serWriter, Boolean fCheck)

   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph, Header[] headers, Boolean fCheck)

   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)

   at Microsoft.Bot.Builder.Internals.Fibers.FormatterStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.Save(T item)

   at Microsoft.Bot.Builder.Internals.Fibers.ErrorResilientStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.Save(T item)

   at Microsoft.Bot.Builder.Internals.Fibers.FactoryStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.Save(T item)

   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IDialogStack-PollAsync>d__19.MoveNext()

**Comment by willportnoy** [comment]
Yes, you are correct - I will fix.

**Comment by MateuszGallus** [comment]
Thank You
