### ISSUE TITLE
[Node] parseTime fails when passing a string

### ISSUE THREAD

**Issue by hgjkant** [Microsoft/BotBuilder#1620]
Hi,
in our bot (Node js, builder v3.4.4) I'm trying to get a date from a string with `EntityRecognizer.parseTime` which ends up with 
```
TypeError: entities.forEach is not a function
    at Function.EntityRecognizer.resolveTime (C:\Users\user\workspace\project\bot\node_modules\botbuilder\lib\dialogs\EntityRecognizer.js:36:18)
    at Function.EntityRecognizer.parseTime (C:\Users\user\workspace\project\bot\node_modules\botbuilder\lib\dialogs\EntityRecognizer.js:28:33)
```
If I look at the method itself
```js

EntityRecognizer.parseTime = function (entities) {
    if (typeof entities == 'string') {
        entities = EntityRecognizer.recognizeTime(entities);
    }
    return EntityRecognizer.resolveTime(entities);
};
```
`EntityRecognizer.resolveTime` expects an array (it calls `forEach` on `entities`) while `recognizeTime` returns an object, causing the error.

I was able to work around it with 
```js
const entity = EntityRecognizer.recognizeTime(string);
const date = EntityRecognizer.resolveTime([entity]);
```

**Comment by chrimc62** [comment]
@stevenic or @maxpert is this fixed?

**Comment by Stevenic** [comment]
Good catch. I have a fix in code review right now. The fix should be in v3.5

**Comment by Stevenic** [comment]
This should be resolved. Please let me know if it still persists and I'll reopen.

**Comment by ajayaneja896** [comment]
@Stevenic 
I have version botbuilder version 3.7.0 and when i am trying to use parseTime it results in a exception same as the hgjkant
The dialog where i am using the code
bot.dialog('/getNumber',[
    function (session,args) {
        if (args && args.reprompt) {
            builder.Prompts.text(session, "I didn't get the time you entered! Please Enter the time of collection again");
        } else {
            builder.Prompts.text(session, "What time would you like to have te test collection");
        }
    },
    function (session, results) {
        try{
            var timeStamp  = builder.EntityRecognizer.parseTime(results.response);
            session.endDialogWithResult({ response: timeStamp });
        }
        catch(Exception){
            session.replaceDialog('/getNumber', { reprompt: true });
        }
    }
]);


exception :- What time would you like to have te test collection
tommorow
I didn't get the time you entered! Please Enter the time of collection again
10pm

Oops. Something went wrong and we need to start over.
TypeError: entities.forEach is not a function
    at Function.EntityRecognizer.resolveTime (/home/ajay/curill-bot/node_modules/botbuilder/lib/dialogs/EntityRecognizer.js:36:18)
    at Function.EntityRecognizer.parseTime (/home/ajay/curill-bot/node_modules/botbuilder/lib/dialogs/EntityRecognizer.js:28:33)
    at Array.<anonymous> (/home/ajay/curill-bot/app.js:76:55)
    at Object.waterfallAction [as BookTest] (/home/ajay/curill-bot/node_modules/botbuilder/lib/dialogs/SimpleDialog.js:52:36)
    at IntentDialog.dialogResumed (/home/ajay/curill-bot/node_modules/botbuilder/lib/dialogs/IntentDialog.js:81:44)
    at Session.endDialogWithResult (/home/ajay/curill-bot/node_modules/botbuilder/lib/Session.js:314:28)
    at Array.<anonymous> (/home/ajay/curill-bot/app.js:26:21)
    at SimpleDialog.waterfallAction [as fn] (/home/ajay/curill-bot/node_modules/botbuilder/lib/dialogs/SimpleDialog.js:52:36)
    at SimpleDialog.dialogResumed (/home/ajay/curill-bot/node_modules/botbuilder/lib/dialogs/SimpleDialog.js:24:14)
    at Session.endDialogWithResult (/home/ajay/curill-bot/node_modules/botbuilder/lib/Session.js:314:28)
