### ISSUE TITLE
System.NullReferenceException

### ISSUE THREAD

**Issue by GhostAtom** [Microsoft/BotBuilder#1656]
I have this exception who randomly appears. Someone have an idea?

   at Microsoft.Bot.Builder.Dialogs.Internals.Extensions.MaxBy[T,R](IEnumerable`1 items, Func`2 selectRank, IComparer`1 comparer)
   at Microsoft.Bot.Builder.Dialogs.LuisDialog`1.BestIntentFrom(LuisResult result)
   at Microsoft.Bot.Builder.Dialogs.LuisDialog`1.<BestResultFrom>b__6_0(LuisResult result)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at Microsoft.Bot.Builder.Dialogs.Internals.Extensions.MaxBy[T,R](IEnumerable`1 items, Func`2 selectRank, IComparer`1 comparer)
   at Microsoft.Bot.Builder.Dialogs.LuisDialog`1.BestResultFrom(IEnumerable`1 results)
   at Microsoft.Bot.Builder.Dialogs.LuisDialog`1.<MessageReceived>d__7.MoveNext()

**Comment by GhostAtom** [comment]
I think this issue is external to my bot because I'm using my master branch who worked before and the code is unchanged.
I faced this issue before but with a lower botbuilder knowledge, so I couldn't figure out if it's my code or not.

**Comment by GhostAtom** [comment]
I'm quite sure that is because I have exhausted my Azure credit. Anyway the exception should mention that there is an issue with connecting Luis service.

**Comment by msft-shahins** [comment]
this [change](https://github.com/Microsoft/BotBuilder/commit/23599183d88b28b3dffdf339d41635116f157bf2#diff-fc12be413ee856c7ceff21175ced7b51R215) which is not released yet should address this issue and raise the Luis service call failures as exception.
