### ISSUE TITLE
Node.js Skype message send always fails with [500] Internal Server Error

### ISSUE THREAD

**Issue by APXEOLOG** [Microsoft/BotBuilder#1751]
This is the example code:
```
const builder = require('botbuilder');
const restify = require('restify');

const server = restify.createServer();
server.listen(4770, function () {
    console.log('%s listening to %s', server.name, server.url);
});

const connector = new builder.ChatConnector({
    appId: '...',
    appPassword: '...'
});
const bot = new builder.UniversalBot(connector);
server.post('/api/messages', connector.listen());

bot.on('error', function (message) {
    console.log(message);
});

bot.dialog('/', function (session) {
    session.send("Hello World");
});
```
It works perfectly with built-in Web Chat, but when i am trying this with Skype i got error:
```
Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1xnCyeJXuG6vWU_KWabetAYO5G_k5qhNEse7z3OAKwm8/activities' failed: [500] Internal Server Error
    at Request._callback (/usr/share/apxeolog/hafen-skype-bot/node_modules/botbuilder/lib/bots/ChatConnector.js:414:46)
    at Request.self.callback (/usr/share/apxeolog/hafen-skype-bot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/share/apxeolog/hafen-skype-bot/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/share/apxeolog/hafen-skype-bot/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

```

I've added additional logging at `ChatConnector.js:414` and this is the response body :
```
{ errorCode: -1,
     message: 'ExceptionContext::MS.Msn.Messenger.ConnectionGateway.WebApi.Models.ResourceMri GetDecryptedIdentity(MS.Msn.Messenger.ConnectionGateway.WebApi.Models.ResourceMri, MS.Msn.Messenger.Runtime.MessengerResourceIdentifier, MS.Msn.Messenger.Runtime.Agents.ApsAgentCache)' } }
```
Please can you fix this, i got this error for 4 months already
I have no idea why only Skype is not working...

**Comment by konstlut** [comment]
@APXEOLOG Could you please share your bot msa app id?

**Comment by APXEOLOG** [comment]
You mean Microsoft App ID for my bot? Should i share it here, or it is private information?

**Comment by konstlut** [comment]
This is not a secret information until you want your bot to be kept in secret.

**Comment by APXEOLOG** [comment]
Here it is: 9c53676a-6f1c-4f20-8f8e-1ea7f1f1c8ed

**Comment by konstlut** [comment]
@APXEOLOG thanks a lot! I see the record in our registry for your bot is corrupted on our side. I will try to resolve that so it likely be fixed tonight .

**Comment by konstlut** [comment]
@APXEOLOG Will you try that again, please?

**Comment by APXEOLOG** [comment]
@konstlut It works fine now, thank you!
