### ISSUE TITLE
ASP.NET CORE (Full Fx) - System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by NicolasHumann** [Microsoft/BotBuilder#1834]
Hi, I have a System.UnauthorizedAccessException when the bot is developped with ASP.NET Core (Full Fx). It works fin with ASP.NET Classic.

The Microsoft App ID and Password are set in the environnemnt variables in the launchSettings.json
The controller get the request fine and the attribute is set like this  [BotAuthentication(MicrosoftAppId = "207b61e4-706b-4ba3-9501-0bbf6bdf1449", MicrosoftAppPassword = "XXXXX")]

`System.UnauthorizedAccessException: Authorization for Microsoft App ID 207b61e4-706b-4ba3-9501-0bbf6bdf1449 failed with status code Unauthorized
   at Microsoft.Bot.Connector.JwtTokenRefresher.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__8.MoveNext()`

Am I missing something ?

Thanks

**Comment by msft-shahins** [comment]
Currently bot builder and connector libraries don't support ASP.NET Core. Adding support for ASP.NET Core is in our backlog.
