### ISSUE TITLE
DirectlineClient -> PostMessage -> 500 server error

### ISSUE THREAD

**Issue by JPThorne** [Microsoft/BotBuilder#1849]
Hi there. As of this morning we are seeing 500 "InternalServer" errors from the directline client. 

We're using the latest nuget package - version 1.1.1, and have enabled the version 3.0 option in the botframework.com configuration screen. We had it just on the version 1.0 option as well, same error. 

In addition, using the embedded webchat control on the botframework.com configuration screen never returns a result. We are also seeing 0 errors on any of our channels - however there should still be some errors showing, we never cleared them, and there should now be errors showing of the 500 server error surely? 

The 'test connection to your bot' option does return a 'Endpoint authorization succeeded' though. And we can still receive responses via facebook. 

So it seems somethings up with the directline service? Is there a 'status page' somewhere we could check?

Here's the stacktrace: 

```
  at Microsoft.Bot.Connector.DirectLine.Conversations.<PostMessageWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.DirectLine.ConversationsExtensions.<PostMessageAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.DirectLine.ConversationsExtensions.PostMessage(IConversations operations, String conversationId, Message message)
   at Atura.BotIntegrationTests.Core.AturaDirectLineIntegrationClient.SendMessage(String conversationId, String from, String messageText)
```

**Comment by dandriscoll** [comment]
Hi @JPThorne, we're looking into the bot errors.

Can you send a conversation ID where you're seeing the failure? If you're using Direct Line 1.0/1.1, the API returns 500 for both bot errors and internal errors, and we see many bot errors. If you send a conversation ID, I can take a closer look to see where the problem is.

**Comment by JPThorne** [comment]
@dandriscoll thanks for the response, I've checked it this morning again and the problem has cleared up.
