### ISSUE TITLE
error builder.AnimationCard is not a constructor

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#1888]
Hi, first of all , thanks for the fabulous effort in maintaining this library. I want to send a GIF across all channels and read about AnimationCard in the documentation repo

My code looks like this
```
function onMessage(session) {
    var msg = new builder.Message(session).addAttachment(createAnimationCard(session, 'title', 'subtitle', 'text'));
    session.send(msg);
}

function createAnimationCard(session, title, subtitle, text) {
    return new builder.AnimationCard(session)
        .title(title)
        .subtitle(subtitle)
        .text(text)
        .media([
            new builder.MediaUrl()
                .profile('GIF test')
                .url('http://media2.giphy.com/media/FiGiRei2ICzzG/giphy.gif')
        ])
}
```
I did open the node_modules folder and went to botbuilder/lib/cards and did not see an AnimationCard. any ideas why? Thank you for your suggestion in advance
```
TypeError: builder.AnimationCard is not a constructor
    at createAnimationCard (D:\bots\fastrivia\index.js:65:12)
    at Array.onMessage (D:\bots\fastrivia\index.js:60:58)
    at SimpleDialog.waterfallAction [as fn] (D:\bots\fastrivia\node_modules\botbuilder\lib\dialogs\DialogAction.js:131:25)
    at SimpleDialog.begin (D:\bots\fastrivia\node_modules\botbuilder\lib\dialogs\SimpleDialog.js:15:14)
    at Session.beginDialog (D:\bots\fastrivia\node_modules\botbuilder\lib\Session.js:180:16)
    at routeToDialog (D:\bots\fastrivia\node_modules\botbuilder\lib\Session.js:421:23)
    at D:\bots\fastrivia\node_modules\botbuilder\lib\Session.js:449:29
    at D:\bots\fastrivia\node_modules\botbuilder\lib\Session.js:505:25
    at ActionSet.recognizeAction (D:\bots\fastrivia\node_modules\botbuilder\lib\dialogs\ActionSet.js:44:9)
    at D:\bots\fastrivia\node_modules\botbuilder\lib\Session.js:501:43
```

**Comment by slidenerd** [comment]
I have fixed the error
first of all, check the cards folder inside botbuilder library's main src. If you dont see AnimationCard, you need to uninstall botbuilder and install what I can call as the unstable release probably
`npm install --save botbuilder@next`

That should help
In the next step, create an AnimationCard like anything else
```
function createAnimationCard(session) {
    return new builder.AnimationCard(session)
        .title('BotFramework Hero Card')
        .subtitle('Your bots — wherever your users are talking')
        .text('Build and connect intelligent bots to interact with your users naturally wherever they are, from text/sms to Skype, Slack, Office 365 mail and other popular services.')
        .media([{
            profile: 'gif',
            url: 'https://media0.giphy.com/media/aWRWTF27ilPzy/200.gif'
        }])
}
```
Finally, initialize like a HeroCard
```
    var msg = new builder.Message(session).addAttachment(createAnimationCard(session));
    session.send(msg);
```

And there you go, this screenshot was from the bot emulator
![test](https://cloud.githubusercontent.com/assets/5139030/21353894/08784fd8-c6ee-11e6-9cc1-c42665d90c0a.gif)
