### ISSUE TITLE
issue with facebook messenger message

### ISSUE THREAD

**Issue by goldstark** [Microsoft/BotBuilder#1944]
i show the code, i ignore why it is wrong in facebook and ok in webchat emulator
thank you for your help

```javascript
var reply=null;
function qnaMaker(session,q)
{
var url="http://qnaservice.cloudapp.net/KBService.svc/GetAnswer?kbId=MYKEYf&question="+ encodeURIComponent(q);
 request(url, function(err, res, body) {
     body=JSON.parse(body);
     body=body["answer"];
     body=body.replace("&#233;","e");   
     reply.text = body;
     bot.send(reply);  
     console.log("qnamaker");
 });
bot.dialog("/",function(session){
reply=session.message;
 qnaMaker(session,session.message.text);
});
```
Log:
```
2017-01-02T09:21:05.502 TypeError: Cannot read property 'replyReceived' of undefined
    at Session.routeToActiveDialog (D:\home\site\wwwroot\messages\node_modules\botbuilder\lib\Session.js:495:23)
    at disambiguateRoute (D:\home\site\wwwroot\messages\node_modules\botbuilder\lib\bots\UniversalBot.js:310:37)
    at D:\home\site\wwwroot\messages\node_modules\botbuilder\lib\bots\UniversalBot.js:316:21
    at D:\home\site\wwwroot\messages\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (D:\home\site\wwwroot\messages\node_modules\async\lib\async.js:236:30)
    at Object.async.forEach.async.each (D:\home\site\wwwroot\messages\node_modules\async\lib\async.js:209:22)
    at D:\home\site\wwwroot\messages\node_modules\botbuilder\lib\bots\UniversalBot.js:295:19
    at UniversalBot.Library.recognize (D:\home\site\wwwroot\messages\node_modules\botbuilder\lib\bots\Library.js:56:13)
    at UniversalBot.routeMessage (D:\home\site\wwwroot\messages\node_modules\botbuilder\lib\bots\UniversalBot.js:289:14)
    at D:\home\site\wwwroot\messages\node_modules\botbuilder\lib\bots\UniversalBot.js:283:80.
```

**Comment by ancashoria** [comment]
I have the same problem, any idea how to fix it?
It was working yesterday, so not sure what's causing the problem.

**Comment by amitbend** [comment]
Same here

**Comment by goldstark** [comment]
instead of usering bot.send (i guess if bot inherit form context for messenger), team give me this answer that resolve my probem : using QnAMakerDialog to dialog

var qnaMakerDialog = builder_cognitiveservices.QnAMakerDialog;
qnaMakerDialog.prototype.invokeAnswer = function (session, recognizeResult, threshold, noMatchMessage) {
        var qnaMakerResult = recognizeResult;
        if (qnaMakerResult.score >= threshold) {
            session.send(qnaMakerResult.answer.replace('&#233;','e'));
        }
        else {
            session.send(noMatchMessage);
        }
    };

**Comment by Stevenic** [comment]
So a couple of points... you're calling bot.send() instead of session.send() which is what you would actually want to call. So I know you got your issue resolved but here's the more correct solution for what you were originally trying to do:

```
function qnaMaker(session,q)
{
var url="http://qnaservice.cloudapp.net/KBService.svc/GetAnswer?kbId=MYKEYf&question="+ encodeURIComponent(q);
 request(url, function(err, res, body) {
     body=JSON.parse(body);
     body=body["answer"];
     body=body.replace("&#233;","e");   
     session.send(body);
     console.log("qnamaker");
 });
bot.dialog("/",function(session){
     qnaMaker(session,session.message.text);
});
