### ISSUE TITLE
Unable to send audio attachment to FB Messenger via bot

### ISSUE THREAD

**Issue by amititash** [Microsoft/BotBuilder#1993]
Hi, 

I am unable to send an audio attachment via botbuilder. I am on the latest version of the botbuilder. Below is the snippet of code I am using.  I have tried all different options and it seems this is not working. When will this be fixed ?

`var msg = new builder.Message(session).sourceEvent(
               {facebook: {
                    attachment: {
                        type: "audio",
                        payload: {
                             url:"https://petersapparel.com/bin/clip.mp3"
                        }
                    }
                }
            });
        session.send(msg);`

I am recieving the following error

`Error: Request to 'https://facebook.botframework.com/v3/conversations/1106358962795256-204426340019460/activities/38b93pDlg4a' failed: [400] Bad Request
    at Request._callback (/workspace/FranceSayBot/node_modules/botbuilder/lib/bots/ChatConnector.js:413:46)
    at Request.self.callback (/workspace/FranceSayBot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/workspace/FranceSayBot/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/workspace/FranceSayBot/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)`

**Comment by LarsLiden** [comment]
This question has been answered on your StackOverflow post:  
http://stackoverflow.com/questions/41544251/unable-to-send-audio-attachment-to-fb-messenger-via-bot
