### ISSUE TITLE
Can't add CSV attachment for Skype using node.js

### ISSUE THREAD

**Issue by amphora-ken** [Microsoft/BotBuilder#2046]
I have no trouble with content types of image/xxx, but if I add a URL for a csv file as text/csv, it fails with the following stack trace:
Error: Request to 'https://smba.trafficmanager.net/v3/conversations/29%3A1p2kJbFW69eJhxBidUtKWdwrEA13GmqxLjUV5x4J21Ls/activities' failed: [400] Bad Request
    at Request._callback (/home/ec2-user/mistrobot/node_modules/botbuilder/lib/bots/ChatConnector.js:434:46)
    at Request.self.callback (/home/ec2-user/mistrobot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ec2-user/mistrobot/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ec2-user/mistrobot/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

Any idea how to make this work?
Thanks

**Comment by nickcordrey** [comment]
File sharing from a bot to a user or from a user to a bot is not supported in Skype today, but it is in our backlog as a feature request.
