### ISSUE TITLE
Exception When calling Luis with json as query

### ISSUE THREAD

**Issue by AmirSasson** [Microsoft/BotBuilder#2095]
i have a bot where users can send JSON as string, and I have a LUIS app that i have trained to understand these JSON strings and translate into custom intents,
all worked fine, till yesterday when i started to get errors (http 500) from the LUIS service.
i didnt upgrade my SDK (nuget Package3.4.0), and i a pretty sure this is something that was done on the LUIS server.
from  within the luis.ai site Sending JSONs works well, but when using the SDK i get an exception: 

System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Bot.Builder.Luis.LuisService.<Microsoft-Bot-Builder-Luis-ILuisService-QueryAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Luis.Extensions.<QueryAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.LuisDialog`1.<MessageReceived>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by cahann** [comment]
We didn't deploy any changes to LUIS back-end since last week. @AmirSasson, are you saying that when you call the LUIS endpoint directly things are working fine however when you use the botbuilder SDK you start getting 500 ?

**Comment by AmirSasson** [comment]
Exactly,
It all worked well till jan 22nd (more or less), i used to send json as
query to Luis and had a trained model where these json translated into a
specific intent.
But in the past week it all got http 500.
As a worked around i now send Key value pair which works fine.

**Comment by cahann** [comment]
@willportnoy have you guys did any changes to the botbuilder SDK ?

**Comment by willportnoy** [comment]
@cahann no changes to the LUIS client, at least.  It sounds like @AmirSasson was sending a json string as the "q" query parameter to the LUIS service.

**Comment by jameslew** [comment]
We haven't seen anything on this in two weeks so I'm closing.  Please let us know if you're still having the problem.
