### ISSUE TITLE
[LUIS] Unable to use email channel

### ISSUE THREAD

**Issue by jsebrech** [Microsoft/BotBuilder#2118]
I'm trying to use the email channel, but no matter what I put in the email, I get the following error:

SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/opt/sumi-dev/node_modules/botbuilder/lib/dialogs/LuisRecognizer.js:70:39)
    at Request.self.callback (/opt/sumi-dev/node_modules/botbuilder/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/opt/sumi-dev/node_modules/botbuilder/node_modules/request/request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/opt/sumi-dev/node_modules/botbuilder/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)

I'm using botbuilder 3.5.4

**Comment by jsebrech** [comment]
Additional detail: this happens from Outlook 365 with the mail format set to HTML. If I set it to plain text, it works.

**Comment by jsebrech** [comment]
Further details, it appears the signature is the issue. Attaching the html file.
[MCS 2016.zip](https://github.com/Microsoft/BotBuilder/files/732070/MCS.2016.zip)

**Comment by Stevenic** [comment]
Sorry for the delay. I'm trying to get the right people to look at this...

**Comment by Stevenic** [comment]
The issue looks to be a bogus response returned from LUIS.

**Comment by craigjensen** [comment]
Please attach your BotId if you are still seeing this and we'll take a look in our logs to see if we can isolate the issue.

**Comment by Stevenic** [comment]
@jsebrech we need to see the text that we're sending to LUIS. Could you make your bot a little simple like below and then send us the text of the message? Thanks!

```
var bot = new builder.UniversalBot(connector, function (session) {
     console.log(session.mesage.text);
     session.send('msg: ' + session.message.text);
});

**Comment by jsebrech** [comment]
Due to circumstances I won't be able to look into this before the second week of march, but I'll pick it up then.

**Comment by Stevenic** [comment]
Ok... we'll leave this open for now

**Comment by jsebrech** [comment]
I just now reproduced this issue with the bot with bot handle SumiDevBot and app id edca82d3-9574-4ac7-8b96-6ec3df58b093

The stack trace of the error is the same as in my initial post.

I tested what is being sent as instructed and get this in the logs:

2017-03-09T09:12:42.418Z - info: test

Joeri Sebrechts


MCS

Software & Advisory for
Integrated Real Estate, Facility & Workplace Management
www.MCSsolutions.com<http://www.mcssolutions.com/>




Visit our latest blog<http://www.mcssolutions.com/be/blog/> | Legal disclaimer<https://www.mcssolutions.com/be/legal/email-disclaimer/>
“We are hiring ! Check here<https://www.mcssolutions.com/join/?__hstc=36998655.2447b7506e7a91e4d6c5fad7b69c83bd.1462803525775.1464688295311.1464869462405.22&__hssc=36998655.1.1464869462405&__hsfp=2196117068> for open vacancies”

**Comment by cahann** [comment]
What is your LUIS application ID?

**Comment by jsebrech** [comment]
The LUIS app ID is 9fe0a544-65d6-4b1d-a741-273b372aae46

**Comment by cahann** [comment]
Hitting LUIS directly seems to be working fine.

**Comment by nwhitmont** [comment]
@jsebrech are you still having the issue with botbuilder v3.7.0?

**Comment by jsebrech** [comment]
I am still seeing the issue with v3.7.0. Just reproduced it:
2017-04-27T12:19:07.291Z - error: UniversalBot unexpected error SyntaxError: Unexpected end of input
    at Object.parse (native)
    at Request._callback (/opt/sumi-dev/node_modules/botbuilder/lib/dialogs/LuisRecognizer.js:70:39)
    at Request.self.callback (/opt/sumi-dev/node_modules/botbuilder/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/opt/sumi-dev/node_modules/botbuilder/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/opt/sumi-dev/node_modules/botbuilder/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)

**Comment by nwhitmont** [comment]
@jsebrech can you provide a code example that reproduces this issue?

**Comment by nwhitmont** [comment]
@jsebrech I'm unable to reproduce your error.  I setup a new bot with Azure Bot Service using Node SDK and the Echo Bot template. Configured the email channel using a valid outlook.com email account. Sent test messages to the bot's email address using 1) plain text, and 2) HTML formatted email, both worked without error. The bot responded to the messages without error in both cases.

**Comment by jsebrech** [comment]
@nwhitmont Perhaps you can provide me with an email address to send to? The issue was the specific signature that we add below our emails, not just a HTML-formatted mail.

**Comment by nwhitmont** [comment]
@jsebrech Can you share the code that is triggering the issue?

**Comment by nwhitmont** [comment]
reopen if you're still experiencing the issue
