### ISSUE TITLE
Prompts.choice error ([sprintf] unexpected placeholder)

### ISSUE THREAD

**Issue by slidenerd** [Microsoft/BotBuilder#2144]
Hey, first of all thank you for all your fantastic efforts in maintaining this lib. I am facing this issue from yesterday.
```
let text = messages.welcome(session.userData.firstName)
let choices = messages.welcomeButtons
builder.Prompts.choice(session, text, choices)
```

My text looks like this
```
messages.welcome = function (name) {
    let gift = emoji.get(emojis.gift)
    let iphone = emoji.get(emojis.iphone)
    let computer = emoji.get(emojis.computer)
    let camera = emoji.get(emojis.camera)
    let tv = emoji.get(emojis.tv)
    let watch = emoji.get(emojis.watch)
    let makeup = emoji.get(emojis.lipstick)
    let wink = emoji.get(emojis.wink)
    let text =
        "Hey " + name + "! I am Bob " + wink + ", I will show you a price like 9 " + gift + " " + gift + ", if you guess it correctly as 999, I will give upto 99% off on that product. It can be anything: an " + iphone + " iPhone, a " + computer + " Macbook, a DSLR " + camera + " camera, a 4K " + tv + " TV, a luxury " + watch + " watch or a " + makeup + " beauty product. Can you guess its price " + wink + "?"

    return text
}
```

My welcome Buttons look as follows

```
messages.welcomeButtons = [
    emoji.get(emojis.rocket) + " Lets Play!",
    " How it works " + emoji.get(emojis.question)
]
```
The emojis are being rendered with the node-emoji library and they are working perfectly.

Here is the scenario, if I specify a list style, this code works but I dont see the buttons.

**Scenario 1**

```
let text = messages.welcome(session.userData.firstName)
let choices = messages.welcomeButtons
builder.Prompts.choice(session, text, choices, { listStyle: "button" })
```

**Output**
![snap 2017-01-31 at 14 50 54](https://cloud.githubusercontent.com/assets/5139030/22459059/173016e4-e7c5-11e6-8be9-62384a1f7798.png)

**Scenario 2**

I dont specify the list style and the bot crashes
```
let text = messages.welcome(session.userData.firstName)
let choices = messages.welcomeButtons
builder.Prompts.choice(session, text, choices)
```
![snap 2017-01-31 at 14 52 00](https://cloud.githubusercontent.com/assets/5139030/22459065/1d0c73c8-e7c5-11e6-8e9d-33af5351c2b6.png)

```

SyntaxError: [sprintf] unexpected placeholder
    at Function.sprintf.parse (d:\bots\zupquiz\node_modules\sprintf-js\src\sprintf.js:164:23)
    at sprintf (d:\bots\zupquiz\node_modules\sprintf-js\src\sprintf.js:19:34)
    at Object.vsprintf (d:\bots\zupquiz\node_modules\sprintf-js\src\sprintf.js:174:24)
    at fmtText (d:\bots\zupquiz\node_modules\botbuilder\lib\Message.js:261:46)
    at Message.text (d:\bots\zupquiz\node_modules\botbuilder\lib\Message.js:49:33)
    at Prompts.createPrompt (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\Prompts.js:239:21)
    at Prompts.sendPrompt (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\Prompts.js:175:24)
    at Prompts.begin (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\Prompts.js:122:14)
    at Session.beginDialog (d:\bots\zupquiz\node_modules\botbuilder\lib\Session.js:215:16)
    at beginPrompt (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\Prompts.js:348:13)
    at Function.Prompts.choice (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\Prompts.js:300:9)
    at welcome (d:\bots\zupquiz\index.js:131:25)
    at Array.stepOne (d:\bots\zupquiz\index.js:113:9)
    at SimpleDialog.waterfallAction [as fn] (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\SimpleDialog.js:67:25)
    at SimpleDialog.begin (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\SimpleDialog.js:18:14)
    at Session.beginDialog (d:\bots\zupquiz\node_modules\botbuilder\lib\Session.js:215:16)
    at Object.handler (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\ActionSet.js:226:25)
    at next (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\ActionSet.js:144:19)
    at ActionSet.selectActionRoute (d:\bots\zupquiz\node_modules\botbuilder\lib\dialogs\ActionSet.js:152:13)
    at UniversalBot.Library.selectGlobalActionRoute (d:\bots\zupquiz\node_modules\botbuilder\lib\bots\Library.js:219:22)
    at UniversalBot.Library.defaultSelectRoute (d:\bots\zupquiz\node_modules\botbuilder\lib\bots\Library.js:277:22)
    at UniversalBot.Library.selectRoute (d:\bots\zupquiz\node_modules\botbuilder\lib\bots\Library.js:85:18)
```
Package.json contents in case you need it
```
"dependencies": {
    "botbuilder": "^3.5.4",
    "cron": "^1.2.1",
    "dashbot": "^0.8.4",
    "express": "^4.14.1",
    "jimp": "^0.2.27",
    "jsonfile": "^2.4.0",
    "moment": "^2.17.1",
    "mongoose": "^4.8.1",
    "node-emoji": "^1.5.1",
    "nodemon": "^1.11.0",
    "request": "^2.79.0",
    "share-url": "^1.0.0"
  }

```
Any suggestions are highly appreciated 👍

**Comment by willportnoy** [comment]
Is it possible that the string representation of the emojis conflicts with the string representation of the placeholders in the sprintf library?

**Comment by slidenerd** [comment]
If that were the case, both scenarios would fail dont you think? it only fails when i dont specify the list style, how weird is that :)

**Comment by willportnoy** [comment]
@Stevenic what is the intention behind the extra %s in https://github.com/Microsoft/BotBuilder/blob/master/Node/core/lib/dialogs/Prompts.js#L239 ?

**Comment by Stevenic** [comment]
@slidenerd sorry for the very long delay.  The issue with "scenario 1" is that you need to pass in `builder.ListStyle.button` which maps to a number and not a string.

For "scenario 2", if you're crashing it's most likely because you're generating some sort of invalid escape code for `SPRINTF`. You may want to build your prompt as an IMessage instead so you don't run through SPRINTF at all.

**Comment by Stevenic** [comment]
Closing for now but please feel free to comment.
