### ISSUE TITLE
[NodeJS]: FB endpoint and another '[500] Internal Server Error'

### ISSUE THREAD

**Issue by vorti2** [Microsoft/BotBuilder#2179]
Hi,

now we have the following error in our bot connected to Microsoft Bot Framework:
```
Error: Request to 'https://facebook.botframework.com/v3/conversations/1169397476441139-637700629724509/activities/mid.%24CAAJD%2FFmVC2dgNdz0jVaBJesWqgud' failed: [500] Internal Server Error
    at Request._callback (/Users/wvo/Documents/Development/gyant/work/gyant-connector/node_modules/botbuilder/lib/bots/ChatConnector.js:452:46)
    at Request.self.callback (/Users/wvo/Documents/Development/gyant/work/gyant-connector/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:192:7)
    at Request.<anonymous> (/Users/wvo/Documents/Development/gyant/work/gyant-connector/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:189:7)
    at IncomingMessage.<anonymous> (/Users/wvo/Documents/Development/gyant/work/gyant-connector/node_modules/request/request.js:1001:12)
    at Object.onceWrapper (events.js:291:19)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```
We use now the newest npm module from
```
"botbuilder": "^3.6.0"
```
(and I know: MSBF is in 'preview' status :wink:)

Any new idea? (see also [another issue with 5** error](https://github.com/Microsoft/BotBuilder/issues/2140))

Thanks,
Wilhelm

**Comment by msft-shahins** [comment]
@vorti2 is it possible to share the body some of the requests that you are getting 500 for?

**Comment by vorti2** [comment]
@msft-shahins any tips for getting the body of a request to MSBF? 
Btw curl without any body brings the also an error:
```
*   Trying 40.127.139.252...
* TCP_NODELAY set
* Connected to facebook.botframework.com (40.127.139.252) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: *.botframework.com
* Server certificate: Microsoft IT SSL SHA2
* Server certificate: Baltimore CyberTrust Root
> GET /v3/conversations/1169397476441139-637700629724509/activities/mid.%24CAAJD%2FFmVC2dgNzbwmlaBfGoQtgYG HTTP/1.1
> Host: facebook.botframework.com
> User-Agent: curl/7.51.0
> Accept: */*
>
< HTTP/1.1 500 Internal Server Error
< Cache-Control: private
< Content-Length: 75
< Content-Type: text/html
< Server: Microsoft-IIS/8.0
< X-Powered-By: ASP.NET
< Strict-Transport-Security: max-age=31536000
< Date: Fri, 03 Feb 2017 21:50:36 GMT
<
* Curl_http_done: called premature == 0
* Connection #0 to host facebook.botframework.com left intact
The page cannot be displayed because an internal server error has occurred.⏎
```

**Comment by vorti2** [comment]
@msft-shahins here is a payload with the error and one with no error. 
[MSBF-Payloads.zip](https://github.com/Microsoft/BotBuilder/files/752328/MSBF-Payloads.zip)

The result with no error I have created by delete my FB messenger communication to the bot and start with a fresh session.

**Comment by vorti2** [comment]
Okay, after 6 days of work now same HTTP 500 error occurs. After this error occurs I make a new bot, a new FB page and a new FB bot ... All works until the reply from my bot -> MSBF -> FB.

Must I wait another day?

**Comment by vorti2** [comment]
Strange, but after I reboot my development machine (on which these errors occurred) the error is gone. Afterwards a second 500er error occurs, I reboot my machine, error is gone.
Hmm ...
