### ISSUE TITLE
../dialogs/IntentRecognizerSet not found due to case issue?

### ISSUE THREAD

**Issue by achadha0111** [Microsoft/BotBuilder#2187]
I was trying to deploy a bot with botbuilder 3.6.0 to Heroku, however, build fails because IntentRecognizerSet is not found. I am assuming its because of the case sensitivity on Linux (which is what Heroku uses). Would someone happen to know a fix?

**Comment by carlosscastro** [comment]
Hi @achadha0111, could you please send us the full error text you are getting? Thanks!

**Comment by achadha0111** [comment]
` Error: Cannot find module '../dialogs/IntentRecognizerSet'
2017-02-06T17:33:44.139141+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:469:15)
2017-02-06T17:33:44.139143+00:00 app[web.1]:     at Function.Module._load (module.js:417:25)
2017-02-06T17:33:44.139144+00:00 app[web.1]:     at Module.require (module.js:497:17)
2017-02-06T17:33:44.139144+00:00 app[web.1]:     at require (internal/module.js:20:19)
2017-02-06T17:33:44.139146+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/botbuilder/lib/bots/Library.js:9:29)
2017-02-06T17:33:44.139146+00:00 app[web.1]:     at Module._compile (module.js:570:32)
2017-02-06T17:33:44.139147+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2017-02-06T17:33:44.139148+00:00 app[web.1]:     at Module.load (module.js:487:32)
2017-02-06T17:33:44.139148+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2017-02-06T17:33:44.139149+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)`

**Comment by achadha0111** [comment]
@carlosscastro , any updates?

**Comment by Stevenic** [comment]
I agree that it sounds like a casing problem but I don't see a casing problem.  Are you able to figure out the exact place where we use the wrong case?

**Comment by achadha0111** [comment]
I am supposing, from the error message, it was the naming of the file IntentRecognizerSet.js which was preventing the file from being found when Heroku tried to build it. However, it seems to be working now, so I think we can close this issue. Thank you for looking into it though! Cheers.
