### ISSUE TITLE
Authorization for Microsoft App ID  failed with status code Forbidden

### ISSUE THREAD

**Issue by vovanb** [Microsoft/BotBuilder#2214]
Hi Team @msft-shahins @dandriscoll @willportnoy ,
I am using OnActionExecutingAsync for assigning MicrosoftAppId in run-time instead of using web config.
When new request come-in in method Post: 
  public async Task<HttpResponseMessage> Post([FromBody] Activity activity)

I am calling 
`await Conversation.SendAsync(activity, () => ControllerHandler.MakeJsonRootDialog(strDirPath));`
and I got 
`
System.UnauthorizedAccessException: Authorization for Microsoft App ID  failed with status code Forbidden
   at Microsoft.Bot.Connector.JwtTokenRefresher.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.AlwaysSendDirect_BotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.MapToChannelData_BotToUser.<PostAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.LogBotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.PostUnhandledExceptionToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5.MoveNext()
Exception thrown: 'System.UnauthorizedAccessException' in mscorlib.dll
`
Can you please help ASAP? May be I can create ConnectorClient and somehow call IDialog?

**Comment by msft-shahins** [comment]
Builder is using [ConnectorClientFactory](https://github.com/Microsoft/BotBuilder/blob/3a98a6b3d15962a57b5454bfb3f730d3588de3ef/CSharp/Library/Microsoft.Bot.Builder/ConnectorEx/IConnectorClientFactory.cs#L63) to instantiate ConnectorClient and StateClient. You can implement your own ConnectorClientFactory that instantiate the right clients and register that with the Conversation container. Here is the default registration: https://github.com/Microsoft/BotBuilder/blob/master/CSharp/Library/Microsoft.Bot.Builder.Autofac/Dialogs/DialogModule.cs#L116

**Comment by vovanb** [comment]
@msft-shahins 
My  Dialog defined as 
 ` internal static IDialog<JObject> MakeJsonRootDialog()`
Can you provide example how to instantiate ConnectorClientFactory that instantiate the right clients and register that with the Conversation container prior call to
 ` await Conversation.SendAsync(activity, () => ControllerHandler.MakeJsonRootDialog(strDirPath));`
Real appreciate it. There is 0 example about.

**Comment by willportnoy** [comment]
https://github.com/Microsoft/BotBuilder/issues/2121#issuecomment-275731497 has an example of registering custom services in the container - for example, you can register a per-request MicrosoftAppCredentials that will get used by the connector client factory and other services that depend on it.

**Comment by msft-shahins** [comment]
https://github.com/Microsoft/BotBuilder/issues/2258#issuecomment-280506334 should address your question.
