### ISSUE TITLE
Bot connecting fine to channels except facebook

### ISSUE THREAD

**Issue by jarmstrongnz** [Microsoft/BotBuilder#2229]
I am having issues with my ConnectorClient (C#) not connecting to Facebook. However, Dev Portal, Skype and the Emulator all connect fine to my bot. I am trying to diagnose using ngrok and I am having an exception is thrown as follows:

`		e.ToString()	"System.UnauthorizedAccessException: Authorization for Microsoft App ID efb06f27-b28d-48fc-b94e-425a402ada91 failed with status code Forbidden
   at Microsoft.Bot.Connector.JwtTokenRefresher.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivity(IConversations operations, Activity activity)
   at DirectLineTestBot.MessagesController.<Post>d__0.MoveNext() in C:\\Users\\armstrongj\\Documents\\Visual Studio 2015\\Projects\\DirectLineTestBot\\DirectLineTestBot\\Controllers\\MessagesController.cs:line 20"	string
`

thrown on the line:

`await connector.Conversations.ReplyToActivityAsync("test");`

The code is bare bones as follows:

`using System;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using Microsoft.Bot.Connector;

namespace DirectLineTestBot
{
    [BotAuthentication]
    public class MessagesController : ApiController
    {
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity.Type == ActivityTypes.Message)
            {
                ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
                try
                {
                    await connector.Conversations.ReplyToActivityAsync(activity.CreateReply("test"));
                }
                catch (Exception e)
                {
                }
            }
            var response = Request.CreateResponse(HttpStatusCode.OK);
            return response;
        }
    }
}`

**Comment by jarmstrongnz** [comment]
Anyone update on this one? Note that I have previously had this ngrok bot working fine with this facebook connection (with same app credentails etc).. not too sure what has changed since it broke. 

this seems to be a similar issue
https://github.com/Microsoft/BotBuilder/issues/2237

**Comment by JasonSowers** [comment]
@jarmstrongnz  I am closing this issue for inactivity. If you are still having trouble please feel free to continue the conversation if needed. We can always reopen if this is still an issue for you.
