### ISSUE TITLE
dialog misbehaves after bot crashed

### ISSUE THREAD

**Issue by PadmanavAgarwal** [Microsoft/BotBuilder#2299]
My bot crashed in between a dialog waterfall. I fixed the errors, restarted the bot, deleted user data and deleted conversation data and yet the dialog is behaving absurdly. How to refresh my bot out of this problem?

Below is the error message in the console, whenever I reach that dialog :

`TypeError: Cannot read property 'replace' of undefined
    at DefaultLocalizer.escapeKey (C:\new\playbot\node_modules\botbuilder\lib\DefaultLocalizer.js:204:19)
    at DefaultLocalizer.createKey (C:\new\playbot\node_modules\botbuilder\lib\DefaultLocalizer.js:196:33)
    at DefaultLocalizer.trygettext (C:\new\playbot\node_modules\botbuilder\lib\DefaultLocalizer.js:69:24)
    at DefaultLocalizer.gettext (C:\new\playbot\node_modules\botbuilder\lib\DefaultLocalizer.js:86:21)
    at Prompts.createPrompt (C:\new\playbot\node_modules\botbuilder\lib\dialogs\Prompts.js:213:38)
    at Prompts.sendPrompt (C:\new\playbot\node_modules\botbuilder\lib\dialogs\Prompts.js:175:24)
    at Prompts.begin (C:\new\playbot\node_modules\botbuilder\lib\dialogs\Prompts.js:122:14)
    at Session.beginDialog (C:\new\playbot\node_modules\botbuilder\lib\Session.js:215:16)
    at beginPrompt (C:\new\playbot\node_modules\botbuilder\lib\dialogs\Prompts.js:348:13)
    at Function.Prompts.choice (C:\new\playbot\node_modules\botbuilder\lib\dialogs\Prompts.js:300:9)`

I added session.endDialog() in the beginning of the dialog,hoping that it will break out of that dialog cycle, but it didn't help and I got the below error message (if that is at all helpful ):
```
node_modules\botbuilder\lib\dialogs\SimpleDialog.js:40
                var step = s.dialogData[consts.Data.WaterfallStep];
                                       ^

TypeError: Cannot read property 'BotBuilder.Data.WaterfallStep' of null
    at waterfallAction (C:\new\playbot\node_modules\botbuilder\lib\dialogs\SimpleDialog.js:40:40)
    at skip (C:\new\playbot\node_modules\botbuilder\lib\dialogs\SimpleDialog.js:36:13)
    at C:\new\playbot\app.js:182:17
    at C:\new\playbot\node_modules\mssql\lib\main.js:1588:20
    at StreamEvents.<anonymous> (C:\new\playbot\node_modules\mssql\lib\msnodesqlv8.js:698:59)
    at StreamEvents.g (events.js:260:16)
    at emitNone (events.js:67:13)
    at StreamEvents.emit (events.js:166:7)
    at rowsCompleted (C:\new\playbot\node_modules\msnodesqlv8\lib\driverMgr.js:384:24)
    at queued_onNextResult (C:\new\playbot\node_modules\msnodesqlv8\lib\driverMgr.js:423:17)``
```

**Comment by freshfey** [comment]
@PadmanavAgarwal how did you solve this problem?

**Comment by suvamsh** [comment]
I'm seeing the same thing as well, the error isn't very clear. How did you solve it? @PadmanavAgarwal

**Comment by PadmanavAgarwal** [comment]
We can use a global "goodbye" middleware (introduced in v3.1) to end a conversation with the bot.
However, as a permanent solution, we need to use proper error and exception handling mechanisms to gracefully handle ambiguous situations during a conversation.

As for the error message posted, I later found that this error message is often displayed when there is a problem with initialization of some session objects (there may be some other cases as well)

@freshfey , @suvamsh  can you please explain your problem in detail ?
