### ISSUE TITLE
Request to 'https://smba.trafficmanager.net/apis/v3/conversations' failed: [400] Bad Request

### ISSUE THREAD

**Issue by ooclleeke** [Microsoft/BotBuilder#2305]
I am running sample code - NodeJS/core-CreateNewConversation. 
When I send a message on Skype client, it throw an error as below.
```
ERROR: ChatConnector: startConversation - error starting conversation.
Error: Request to 'https://smba.trafficmanager.net/apis/v3/conversations' failed: [400] Bad Request
    at Request._callback (D:\test\core-CreateNewConversation\node_modules\botbuilder\lib\bots\ChatConnector.js:453:46)
    at Request.self.callback (D:\test\core-CreateNewConversation\node_modules\request\request.js:186:22)
    at emitTwo (events.js:88:13)
    at Request.emit (events.js:173:7)
    at Request.<anonymous> (D:\test\core-CreateNewConversation\node_modules\request\request.js:1081:10)
    at emitOne (events.js:78:13)
    at Request.emit (events.js:170:7)
    at IncomingMessage.<anonymous> (D:\test\core-CreateNewConversation\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:261:16)
    at emitNone (events.js:73:20)
```
I am using botbuilder version 3.6.0
Here is my request, this request is generated by botbuilder:
```
{
	"method":"POST",
	"url":"https://smba.trafficmanager.net/apis/v3/conversations",
	"body":{
		"bot":{"id":"28:d68f1978-a529-4638-a086-469cf4deb66c","name":"Create-New-Conversation-LEEKE"},
		"members":[{"id":"29:13UZ4uz2YkZz19368Km5DJGHml4RoZoS_EtZbSzJmWw0","name":"Ken 6 OOCL"}]
	},
	"json":true,
	"headers":{"Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Il9VZ3FYR190TUxkdVNKMVQ4Y2FIeFU3Y090YyIsImtpZCI6Il9VZ3FYR190TUxkdVNKMVQ4Y2FIeFU3Y090YyJ9.eyJhdWQiOiJodHRwczovL2FwaS5ib3RmcmFtZXdvcmsuY29tIiwiaXNzIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDZkNDk0MjAtZjM5Yi00ZGY3LWExZGMtZDU5YTkzN
Tg3MWRiLyIsImlhdCI6MTQ4NzU3NDkwMSwibmJmIjoxNDg3NTc0OTAxLCJleHAiOjE0ODc1Nzg4MDEsImFwcGlkIjoiZDY4ZjE5NzgtYTUyOS00NjM4LWEwODYtNDY5Y2Y0ZGViNjZjIiwiYXBwaWRhY3IiOiIxIiwiaWRwIjoiaHR0cHM6Ly9zdHMud2luZG93cy5uZXQvZDZkNDk0MjAtZjM5Yi00ZGY3LWExZGMtZDU5YTkzNTg3MWRiLyIsInRpZCI6ImQ2ZDQ5NDIwLWYzOWItNGRmNy1hMWRjLWQ1O
WE5MzU4NzFkYiIsInZlciI6IjEuMCJ9.rZsXi5s6prvXVUXoiFefe99W5ASeODhdBFRCo-T1eJ7qijMDyjejw6dq7MQtAS6wujOZtDGM2rWATQjoHIMC3p6d0ZYZ2altdQ2_9JiCG3lMSDgkN1mCHiQB4F3Tp5oEU5mUiwvOcKDhyJg3mM-jlXU59UB9PXeTcV2zJRDpxRiVjU68IbfQYSINbs-hEqwNxsicYmAX4gZgjBuUowixitX1O2sRHCK1yEcXmPjKAiC_67XWAZJH5phN-17PCYrbvrklHfvcTWRW
4R8enVhsNTdw6bb05tckSXRX5I2Bw6vOMmaN_Pf4DzTtjgCWToTLGwodthpHrxpUA2725H9w8g"}
}
```

**Comment by konstlut** [comment]
This was mitigated for all bots that experienced this issue including this one (28:d68f1978-a529-4638-a086-469cf4deb66c) the final fix will be released in on 2/24/2017.
