### ISSUE TITLE
Failed on "Test connection to your bot"

### ISSUE THREAD

**Issue by NOTPOWERUSER** [Microsoft/BotBuilder#2307]
I got following message after I press the button "Test" on my bot's page.

`
500 InternalServerError
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
   at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Intercom.DevPortal.Server.Controllers.BotManagerController.<PingV3BotAsync>d__76.MoveNext() in D:\a\1\s\DevPortalLib\Controllers\BotManagerController.cs:line 2038`

**Comment by willportnoy** [comment]
It sounds like your SSL certificate is invalid - is it a test certificate?

Otherwise, 

https://docs.botframework.com/en-us/technical-faq/#how-can-i-troubleshoot-my-bots-authentication

**Comment by NOTPOWERUSER** [comment]
Thanks your!!
I used self-signed certification to bind my bot.
It seems this certification is unable to be trust.
After I applied for a valid  certification from GlobalSign and import to my server, now It's working

**Comment by huxaiphaer** [comment]
Please am having the same problem too , what did you mean by SSL certificate, please if possible can you provide  a Step by Step procedure for that,

**Comment by ranmax123** [comment]
i'm having the same issue, what is the resolution?

**Comment by andy51002000** [comment]
@ranmax123 Do you use self-signed certificate created by your bot server?  If so, Bot connector will treat as invalid certificate and you can go to the following link to get a valid sign.
https://www.globalsign.com/en/
