### ISSUE TITLE
Bot Framework Emulator error while I opened it!

### ISSUE THREAD

**Issue by HalwestRasul** [Microsoft/BotBuilder#2399]
Hi 
I wanna test my test-bot but while opening the emulator, it gives me the following error logs.

`[00:03:39] Emulator listening on http://[::]:48555 
[00:03:39] [err-server] spawn UNKNOWN "Error: spawn UNKNOWN\n at exports._errnoException (util.js:1026:11)\n at ChildProcess.spawn (internal/child_process.js:313:11)\n at exports.spawn (child_process.js:392:9)\n at runNgrok (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\ngrok.js:109:13)\n at run (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\ngrok.js:67:13)\n at C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\ngrok.js:77:13\n at lock (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\node_modules\\lock\\index.js:72:7)\n at Object.connect (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\ngrok.js:61:5)\n at startNgrok (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\botFrameworkService.js:95:23)\n at ngrok.kill (C:\\Users\\Halwest\\AppData\\Local\\botframework\\app-3.5.25\\resources\\app\\app\\server\\botFrameworkService.js:129:17)" 
[00:03:39] Checking for new version... 
[00:03:42] Application is up to date.  `

note: I don't know run which port of ngrok.
thanks.

**Comment by HalwestRasul** [comment]
@eanders-MS could you help me!

**Comment by eanders-MS** [comment]
It looks like the emulator is failing to launch ngrok. Could you please check your installed version of ngrok to ensure it is version 2.1.18 or later? Earlier versions have been known to be incompatible. Check the version by running `ngrok -v` from a command prompt.

Note: You only need ngrok when connected to a bot running remotely. You don't need ngrok to connect the emulator to a bot running on localhost.

**Comment by HalwestRasul** [comment]
thanks for your replay @eanders-MS, ngrok version 2.1.18 .

**Comment by eanders-MS** [comment]
Is your ngrok path correctly configured in the Emulator's app settings?
![image](https://cloud.githubusercontent.com/assets/12176807/23669519/507d2d50-0319-11e7-83f2-23d77f2e85e4.png)

**Comment by carlosscastro** [comment]
@HalwestRasul Hello, did the answer from @eanders-MS work for you? I'll close this for now, but feel free to reach out again.

**Comment by HalwestRasul** [comment]
@eanders-MS  yes, ngrok path is true, but I wanna test it in localhost !

**Comment by eanders-MS** [comment]
I wonder if the ngrok client is working at all. Are you able to run ngrok from the command line? What do you see when you run this command:
```
ngrok http -host-header=rewrite 3978
```

**Comment by HalwestRasul** [comment]
@eanders-MS  I'm sorry before I said that the ngrok path was true but its wrong now its true because I moved the ngrok.exe  :) 
Thanks for you now the Emulator was work fine ;)
