### ISSUE TITLE
defaultDialog in UniversalBot causes an exception not finding this.onEventHandler

### ISSUE THREAD

**Issue by mohamedmansour** [Microsoft/BotBuilder#2435]
I created an Azure Bot Service, downloaded the code, then adapted the following [example
](https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/basics-menus/app.js)

The source is the following, any idea why it crashes?

```
"use strict";
var builder = require("botbuilder");
var botbuilder_azure = require("botbuilder-azure");

var useEmulator = (process.env.NODE_ENV == 'development');

var connector = useEmulator ? new builder.ChatConnector() : new botbuilder_azure.BotServiceConnector({
    appId: process.env['MicrosoftAppId'],
    appPassword: process.env['MicrosoftAppPassword'],
    stateEndpoint: process.env['BotStateEndpoint'],
    openIdMetadata: process.env['BotOpenIdMetadata']
});

var bot = new builder.UniversalBot(connector [
    function (session) {
        session.send("Hello... I'm a bot that can help you around the hackathon.");
    },
    function (session, results) {
        session.endConversation("Goodbye until next time...");
    }
]);

if (useEmulator) {
    var restify = require('restify');
    var server = restify.createServer();
    server.listen(3978, function() {
        console.log('test bot endpont at http://localhost:3978/api/messages');
    });
    server.post('/api/messages', connector.listen());    
} else {
    module.exports = { default: connector.listen() }
}
```

**Throws the following:**

```
>node index.js
test bot endpont at http://localhost:3978/api/messages
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
TypeError: this.onEventHandler is not a function
    at ChatConnector.dispatch (d:\mentorbot\messages\node_modules\botbuilder\lib\bots\ChatConnector.js:381:22)
    at ChatConnector.verifyBotFramework (d:\mentorbot\messages\node_modules\botbuilder\lib\bots\ChatConnector.js:126:18)
    at IncomingMessage.<anonymous> (d:\mentorbot\messages\node_modules\botbuilder\lib\bots\ChatConnector.js:51:27)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
WARN: ChatConnector: receive - emulator running without security enabled.
ChatConnector: message received.
TypeError: this.onEventHandler is not a function
    at ChatConnector.dispatch (d:\mentorbot\messages\node_modules\botbuilder\lib\bots\ChatConnector.js:381:22)
    at ChatConnector.verifyBotFramework (d:\mentorbot\messages\node_modules\botbuilder\lib\bots\ChatConnector.js:126:18)
    at IncomingMessage.<anonymous> (d:\mentorbot\messages\node_modules\botbuilder\lib\bots\ChatConnector.js:51:27)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:186:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

**Comment by Imdharm** [comment]
did you got the solution .
if  yes then help me also. I'm facing same issue. @mohamedmansour

**Comment by dpdonohue** [comment]
Me too.  Is there a solution?
