### ISSUE TITLE
SDK crashes with `_this.localPath is not a function`

### ISSUE THREAD

**Issue by nebrius** [Microsoft/BotBuilder#2525]
I'm running the following example, modified from https://docs.botframework.com/en-us/node/builder/overview/:

```JavaScript
const restify = require('restify');
const builder = require('botbuilder');

const APP_ID = ...;
const APP_PASSWORD = ...;

const server = restify.createServer();
server.listen(3000, () => {
  console.log(`${server.name} listening to ${server.url}`);

  const connector = new builder.ChatConnector({
    appId: APP_ID,
    appPassword: APP_PASSWORD
  });

  const bot = builder.UniversalBot(connector); // crashes here
  server.post('/api/messages', connector.listen());

  bot.dialog('/', (session) => {
    session.send('Hello World');
  })
});
```

When I run this, I get the following exception:

```
restify listening to http://[::]:3000
C:\Users\brhugh\Projects\my-first-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:27
        _this.localePath('./locale/');
              ^

TypeError: _this.localePath is not a function
    at Object.UniversalBot (C:\Users\brhugh\Projects\my-first-bot\node_modules\botbuilder\lib\bots\UniversalBot.js:27:15)
    at Server.server.listen (C:\Users\brhugh\Projects\my-first-bot\index.js:16:23)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:91:20)
    at Server.emit (events.js:188:7)
    at emitListeningNT (net.js:1291:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
```

Node: 7.8.0 (installed from nodejs.org)
NPM: 4.2.0
OS: Windows 10 Pro (64-bit)

**Comment by nebrius** [comment]
Update: it was a bug on my end, I left `new` off of the call to `builder.UniversalBot(connector)` which cause the `this` pointer to be incorrect.
