### ISSUE TITLE
NullRef in MicrosoftAppCredentials.RefreshTokenAsync(...)

### ISSUE THREAD

**Issue by Urzzza** [Microsoft/BotBuilder#2747]
## System Information (Required)

* C# 
* master 

## Issue Description

In MicrosoftAppCredentials.RefreshTokenAsync(...) the check about successful status code is after the reading of content. In error case, content is null, which leads to NullReferenceException.

## Example Code
code taken from MicrosoftAppCredentials.RefreshTokenAsync(...):

    using (var response = await httpClient.PostAsync(OAuthEndpoint, content).ConfigureAwait(false))
    {
        // This line throws NRE if response code is not successful
        string body = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
        try
        {
            response.EnsureSuccessStatusCode();
        <...>

## Steps to Reproduce
1. Get any unsuccessful response for token refresh.

## Expected Behavior

Move content reading inside try block after checking response status code. Like this:

    using (var response = await httpClient.PostAsync(OAuthEndpoint, content).ConfigureAwait(false))
    {
        try
        {
            response.EnsureSuccessStatusCode();
            string body = await response.Content.ReadAsStringAsync().ConfigureAwait(false);
        <...>

## Actual Results

 Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<GetTokenAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.MicrosoftAppCredentials.<ProcessHttpRequestAsync>d__25.MoveNext()

**Comment by Urzzza** [comment]
Thanks
