### ISSUE TITLE
Can't get conversation members list. Failure due to: ThreadNotFound. with Node/core-GetConversationMembers example when I try it in skype/msteams

### ISSUE THREAD

**Issue by tom-moveworkforward** [Microsoft/BotBuilder#2759]
## System Information (Required)

* **Node**
* **3.8.1**
* **Azure Bot Service**
* **Node.js 6.9.5 + npm version 3.10.10**

## Issue Description
Error for msteams and skype. Works fine in Slack and web-chat.

## Example Code
https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-GetConversationMembers

## Steps to Reproduce
just deploy example from https://github.com/Microsoft/BotBuilder-Samples/tree/master/Node/core-GetConversationMembers

## Expected Behavior

List of conversation members

## Actual Results

Error retrieving conversation members { url: 'https://smba.trafficmanager.net/v3/conversations/29%3A1UbaMPqpYABhTvgpqhoQ00bjAqDi65n9fV_VXET6dafs/members',
  method: 'GET',
  headers: 
   { 'content-length': '77',
     'content-type': 'application/json; charset=utf-8',
     server: 'Microsoft-HTTPAPI/2.0',
     date: 'Sun, 14 May 2017 05:40:48 GMT',
     connection: 'close' },
  errObj: 
   { Error: Not Found
       at Request.callback (D:\home\site\wwwroot\node_modules\superagent\lib\node\index.js:626:17)
       at D:\home\site\wwwroot\node_modules\superagent\lib\node\index.js:795:18
       at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\superagent\lib\node\parsers\json.js:16:7)
       at emitNone (events.js:91:20)
       at IncomingMessage.emit (events.js:185:7)
       at endReadableNT (_stream_readable.js:974:12)
       at _combinedTickCallback (internal/process/next_tick.js:74:11)
       at process._tickDomainCallback (internal/process/next_tick.js:122:9)
     original: null,
     response: 
      Response {
        domain: null,
        _events: {},
        _eventsCount: 0,
        _maxListeners: undefined,
        res: [Object],
        request: [Object],
        req: [Object],
        links: {},
        text: '{"error":{"code":"ServiceError","message":"Failure due to: ThreadNotFound."}}',
        body: [Object],
        files: undefined,
        buffered: true,
        headers: [Object],
        header: [Object],
        statusCode: 404,
        status: 404,
        statusType: 4,
        info: false,
        ok: false,
        redirect: false,
        clientError: true,
        serverError: false,
        error: [Object],
        accepted: false,
        noContent: false,
        badRequest: false,
        unauthorized: false,
        notAcceptable: false,
        forbidden: false,
        notFound: true,
        charset: 'utf-8',
        type: 'application/json',
        setEncoding: [Function: bound ],
        redirects: [] },
     status: 404 },
  status: 404,
  statusText: '{"error":{"code":"ServiceError","message":"Failure due to: ThreadNotFound."}}',
  obj: 
   { error: 
      { code: 'ServiceError',
        message: 'Failure due to: ThreadNotFound.' } },
  data: '{"error":{"code":"ServiceError","message":"Failure due to: ThreadNotFound."}}' }

**Comment by tom-moveworkforward** [comment]
Issue solved, in my case I was trying to request this information for direct bot<->user channel. When you request same info from group channel it works fine. 

P.s I guess output error should be more precise, describing that this rest api works only for group chats
