### ISSUE TITLE
[CSharp] too many attempts

### ISSUE THREAD

**Issue by wiltodelta** [Microsoft/BotBuilder#278]
After update to Microsoft.Bot.Builder 1.2.0.1 in **Telegram** and **Facebook** I get an error:

```
System.Exception: too many attempts
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.Microsoft.Bot.Builder.Internals.Fibers.IAwaiter<T>.GetResult()
   at Microsoft.Bot.Builder.Dialogs.Chain.LoopDialog`1.<ResumeAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.ThunkResume`1.<Rest>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.<Microsoft-Bot-Builder-Internals-Fibers-IWait<C>-PollAsync>d__19.MoveNext()
```

here:

```
return await Conversation.SendAsync(message, () => new BotDialog());
```

Slack, WebChat works properly.

**Comment by wiltodelta** [comment]
Problem is using PromptDialog.Confirm with PromptStyle.Auto. With PromptStyle.None no errors.

**Comment by wiltodelta** [comment]
+ Facebook

**Comment by msft-shahins** [comment]
There seems to be a bug in connector that does not deliver the buttons with `Action.Message == null` to Facebook and Telegram. We are working on a fix. I assume that the `too many attempts exception` happen because you sent random messages, instead of `yes`, `no`, to your bot when you haven't received any messages from `prompt.confirm`.

**Comment by msft-shahins** [comment]
We pushed a fix. it should have been fixed now on Telegram and Facebook.
