### ISSUE TITLE
[Node SDK] Changes in ActionSet.addDialogTrigger breaks default triggerAction / onSelectAction behavior

### ISSUE THREAD

**Issue by pcostantini** [Microsoft/BotBuilder#2796]
## System Information (Required)

* SDK Platform: Node
* SDK Version: 3.8.0->3.8.3
* Development Environment: All

## Issue Description

The triggerAction / onSelectAction behavior has changed in 3.8.0.

The following change (https://github.com/Microsoft/BotBuilder/commit/d2f02998dc8da4570a65f4d73b45ab833b70ddb0#diff-3b7c8f16348d79be25452957ec091cc8R95)
changes the dialogId to 'trigger([DIALOG_ID])' 

Now, the routeData.action (received in the onSelectAction handler) no longer has the dialog action name and samples that depended on it fail:
 
https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/feature-onInterrupted/app.js#L75-L76
https://github.com/Microsoft/BotBuilder-Samples/blob/0a0ac967546da456ccb395f6875df3b8ce0918a5/Node/core-globalMessageHandlers/bot.js#L82

## Example Code

https://github.com/Microsoft/BotBuilder/blob/master/Node/examples/feature-onInterrupted/app.js#L75-L76

## Steps to Reproduce
1. Run sample `feature-onInterrupted`
2. Type 'continue order' to trigger the error

## Expected Behavior

Should trigger the `continueOrderDialog` dialog.

## Actual Results

Exception:
```
Error: Dialog[trigger(*:continueOrderDialog)] not found.
    at Session.beginDialog (/home/pc/Projects/SW/BotBuilder-samples/BotBuilder/Node/core/lib/Session.js:244:19)
    at Object.onSelectAction (/home/pc/Projects/SW/BotBuilder-samples/BotBuilder/Node/examples/feature-onInterrupted/app.js:76:17)
    at ActionSet.selectActionRoute (/home/pc/Projects/SW/BotBuilder-samples/BotBuilder/Node/core/lib/dialogs/ActionSet.js:149:27)
    at UniversalBot.Library.selectGlobalActionRoute (/home/pc/Projects/SW/BotBuilder-samples/BotBuilder/Node/core/lib/bots/Library.js:224:22)
    at UniversalBot.Library.defaultSelectRoute (/home/pc/Projects/SW/BotBuilder-samples/BotBuilder/Node/core/lib/bots/Library.js:301:22)
    at UniversalBot.Library.selectRoute (/home/pc/Projects/SW/BotBuilder-samples/BotBuilder/Node/core/lib/bots/Library.js:90:18)
````

**Comment by nwhitmont** [comment]
@pcostantini since this is related to another repository, you would need to open the issue there so the owner of BotBuilder-Samples can track it. thanks

**Comment by pcostantini** [comment]
Hi @nwhitmont,
A change introduced in the Node SDK is now affecting samples in BotBuilder and BotBuilder-Samples
Just want to be sure the change is not a regression.

The issue affects samples in both repositories.
Thanks!
