### ISSUE TITLE
[Question] The bot referenced by the 'from' field is unrecognized

### ISSUE THREAD

**Issue by sowsan** [Microsoft/BotBuilder#2857]
Existing issue reported (similar) 
https://github.com/Microsoft/BotBuilder/issues/2450

Not sure how to fix the above recommendation on my scenario,

## System Information (Required)
* SDK Platform: C# - VS 2017 Latest Update
* SDK Version: Microsft.Bot.Builder v3.8.1
* Development Environment: localhost / Azure App Service 

## Issue Description
I have bot that I created for sending the proactive messgaes to the user. When a user use the bot for the first time in webchannel , I'm capturing the ConversationReference and store it in a database. Now, once I need to send a message to the user, I'm using Azure function to read the ConversationReference from the database and out put it using the Azure Function OutPut to Bot feature.

My problem is, whenever the bot send a proactive reply its failing with the below error message,
"**The bot referenced by the 'from' field is unrecognized**"

<Call Stack>
   at Microsoft.Bot.Connector.ErrorHandling.<HandleErrorAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.AlwaysSendDirect_BotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.InputHintQueue.<Microsoft-Bot-Builder-Dialogs-Internals-IMessageQueue-QueueMessageAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.AutoInputHint_BotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.MapToChannelData_BotToUser.<PostAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.LogBotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogContext.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
</Call Stack>

ConversationReference JSON
{
  "userId": "1306fb7022434393ad164c8f83b067d0",
  "conversationReference": {
    "user": {
      "id": "3406fb75534334393ad164c8f83b067d0"
    },
    "bot": {
      "id": "myBot@wD6NRXI6csY",
      "name": "myBot"
    },
    "conversation": {
      "id": "3432fb7022434393ad164c8f83b067d0"
    },
    "channelId": "webchat",
    "serviceUrl": "https://webchat.botframework.com/"
  }
}

## Steps to Reproduce
Follow the steps here to create proactive bot except resumption cookie method, use ConversationReference 

https://www.codeproject.com/Articles/1176637/How-to-create-Proactive-Bot-with-Microsoft-Bot-Fra
http://gregoryfabry.com/2017/04/using-conversationreference-delayed-message-bot-framework

## Expected Behavior
Bot should resume the conversation and send the message to the end user

## Actual Results
Error : "**The bot referenced by the 'from' field is unrecognized**"

**Comment by sowsan** [comment]
Any comments Team ?

**Comment by fanidamj** [comment]
Hoping that issue has been resolved, closing it. Feel free to reopen if any questions.
