### ISSUE TITLE
[Question] bot.on(converstaionupdate) node js not working on fb messenger and skype .....only working with Emulator

### ISSUE THREAD

**Issue by hardikchoudhary** [Microsoft/BotBuilder#3027]
I am working on node js

First message on connect show in emulaator only not in fb or skype

**Comment by nrobert** [comment]
Can you add more details about your implementation?
All events are not fired by every channel, but the `ConversationUpdate` should be fired in Skype at least

**Comment by sir-rois** [comment]
I guess I have same issue with FB.
There is an error inside botframework on first connection:

`Error: Request to 'https://facebook.botframework.com/v3/conversations/XXXX/activities/mid.%%%%%' ' failed: [400] Bad Request
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:452:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)`

**Comment by stevengum97** [comment]
@hardikchoudhary you must provide the code that reproduces the issue *(in this issue)* if you wish to receive worthwhile help.

**Comment by stevengum97** [comment]
Closing due to inactivity.

**Comment by hardikchoudhary** [comment]
Sorry steve i will update the code here tommorow...for the reference
