### ISSUE TITLE
[Question] Get error when call LUIS 

### ISSUE THREAD

**Issue by binhpht** [Microsoft/BotBuilder#3109]
System Information (Required)
* SDK Language: Node
* Development Environment: Localhost

## Issue Description
Get error when call LUIS function 
```bash
SyntaxError: Unexpected end of JSON input
    at Object.parse (native)
    at Request._callback (...node_modules\botbuilder\lib\dialogs\LuisRecognizer.js:86:39)
    at Request.self.callback (...node_modules\request\request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (...node_modules\request\request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (...\node_modules\request\request.js:1091:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

## Code Example
```js
bot.dialog('/', [
    function (session) {
        getProfile(session, function (session,profile) { session.beginDialog('/ensureProfile', profile); })
    },
    function (session, results) {
        session.send("Hi... I'm a sample bot.");
        session.replaceDialog('/luis');
    }
]);
```

**Comment by nwhitmont** [comment]
@binhpht Can you post the code from your `getProfile()` method? What is the code for your `/luis` dialog handler?

**Comment by binhpht** [comment]
@nwhitmont Hi, my addtional fuction like this
const getProfile = function (session, func) {
    if (session.conversationData.profile && session.conversationData.profile.channel === 'webchat') {
        session.userData.profile = session.conversationData.profile;
        func(session,session.userData.profile);
    } else {
        console.log('Not found ID');
    }
};

bot.dialog('/ensureProfile', [
    function (session, args, next) {
        session.dialogData.profile = args || blankUID;

        if (!session.dialogData.profile) {

        } else {
            next();
        }
    }
]);

**Comment by nwhitmont** [comment]
@binhpht Based on the error in your original comment: `SyntaxError: Unexpected end of JSON input` - There is a syntax error in the JSON being passed to one of your code methods.  It's difficult to troubleshoot without seeing your complete bot code.
