### ISSUE TITLE
[Question] NullReferenceException with FormDialog

### ISSUE THREAD

**Issue by punitganshani** [Microsoft/BotBuilder#3153]
## Issue Description
The form builder doesn't construct a form and directly gives OperationCanceledException in an emulator

## Code Example
Use the PizzaBot sample in the GitHub and run the sample

## Steps to Reproduce the Issue
1. Download the PizzaBot sample
2. Change LUIS model (I used a LUIS Model hosted in East US) in PizzaDialog and MSA details in Web.config
3. Execute the code in Visual Studio
4. In an emulator, send the message `I want to order pizza` to the bot
5. Bot replies back `You canceled the form!`

## Exception

```
Exception thrown: 'Microsoft.Bot.Builder.FormFlow.FormCanceledException`1' in mscorlib.dll
Microsoft.Bot.Builder.FormFlow.FormCanceledException`1[Microsoft.Bot.Sample.PizzaBot.PizzaOrder]: Object reference not set to an instance of an object. ---> 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Bot.Builder.FormFlow.FormDialog`1.<MessageReceived>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Bot.Builder.FormFlow.FormDialog`1.<MessageReceived>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.FormFlow.FormDialog`1.<Microsoft-Bot-Builder-Dialogs-IDialog<T>-StartAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.ThunkStart.<Rest>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.<Microsoft-Bot-Builder-Internals-Fibers-IWait<C>-PollAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Frame`1.<Microsoft-Bot-Builder-Internals-Fibers-IFrameLoop<C>-PollAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Fiber`1.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop<C>-PollAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.Microsoft.Bot.Builder.Internals.Fibers.IAwaiter<T>.GetResult()
   at Microsoft.Bot.Sample.PizzaBot.PizzaOrderDialog.<PizzaFormComplete>d__4.MoveNext() in C:\temp\BotBuilder-master\CSharp\Samples\PizzaBot\PizzaOrderDialog.cs:line 80
```

**Comment by nwhitmont** [comment]
@punitganshani What is the URL to the "PizzaBot sample in the GitHub"?

**Comment by punitganshani** [comment]
@nwhitmont here you go `https://github.com/Microsoft/BotBuilder/tree/master/CSharp/Samples/PizzaBot`

**Comment by JasonSowers** [comment]
@punitganshani what version of the SDK are you using.  If it is 3.8.5 please try reverting to 3.8.4 or earlier and let us know if the issue persists.  I', trying to see if this is related to some other issues.

**Comment by punitganshani** [comment]
Yes its `3.8.5`, will revert to `3.8.4` and try again..

**Comment by punitganshani** [comment]
Works like a charm with `3.8.4`

![image](https://user-images.githubusercontent.com/1032553/28377159-8b777bb6-6cde-11e7-8357-dd19d5fe82aa.png)

**Comment by JasonSowers** [comment]
Can you use that as a workaround for now?  There is a pull request in for this I will see if we can get this reviewed, merged and fixed as early as we can.

**Comment by JasonSowers** [comment]
Version 3.9 has been released which includes the fix for this Issue.  Please reopen and continue the discussion if needed.  Thanks for your patience.

**Comment by punitganshani** [comment]
Thanks, this works in the new version.
