### ISSUE TITLE
Issue with facebook 

### ISSUE THREAD

**Issue by Losformen** [Microsoft/BotBuilder#3274]
Hello,

I have a issue to connect facebook channel to the bot.

## System Information
* SDK Language: .Net
* SDK Version:  v3.9.0
* Development Environment:  Visual Studio 2015 ; deployed on azure as a web application

## Bot Info 
* Bot name: Mon Chere Bot
* Bot handle: cherebot
* App ID: 0c7e0624-1318-4015-afc4-ffd244ca9dae
* Connected channels: Skype, Facebook

## Issue Description
I have a issue to connect facebook channel.
First, the bot is working, I can speak to it through the botframework-emulator, the web chat and skype
Second, I already test a bot whitch was generated automatically with "bot service" from Azure and I succeed connecting it to facebook
So, very strange, I try to debug with Visual Studio, and when it tries to send a simple answer (see code below), it raises an exception : System.UnauthorizedAccessException

message :
Authorization for Microsoft App ID 0c7e0624-1318-4015-afc4-ffd244ca9dae failed with status code Forbidden and reason phrase 'Forbidden'

stacktrace : 

> 

Authorization for Microsoft App ID 0c7e0624-1318-4015-afc4-ffd244ca9dae failed with status code Forbidden and reason phrase 'Forbidden'    at Microsoft.Bot.Connector.JwtTokenRefresher.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bot_Application1.MessagesController.<Post>d__1.MoveNext() 

## Code Example
 (simple answer code)
 ConnectorClient connector = new ConnectorClient(new Uri(activity.ServiceUrl));
Activity reply = activity.CreateReply(reponse);
await connector.Conversations.ReplyToActivityAsync(reply);

and I added in the code before :
Microsoft.Bot.Connector.MicrosoftAppCredentials.TrustServiceUrl(@"https://facebook.botframework.com", DateTime.MaxValue);

## Steps to Reproduce the Issue
1. speak to the bot

## Expected Behavior
working

## Actual Results
Throw an exception

**Comment by Losformen** [comment]
I recreate everything and now it's working...
