### ISSUE TITLE
[.NET SDK] Error: "Microsoft.Rest.SerializationException: Unable to deserialize the response."

### ISSUE THREAD

**Issue by singhsurya** [Microsoft/BotBuilder#3351]
We faced below-mentioned exception in our Bot application on 14th August around 5:30 PM UTC. Bot application was working very slow and break many times. Could you guys please let us know if there was any issue in the Bot service at your end. If yes, then what was the issue and what have you fixed? Can we avoid such issues at our end somehow? @dandriscoll @jameslew @stevengum97  

I found an issue reported of the same kind  [here](https://github.com/Microsoft/BotBuilder/issues/3318)

Unable to deserialize the response. Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: T. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__8.MoveNext()

Thanks!
Surya

**Comment by nwhitmont** [comment]
@singhsurya For reference, what version of BotBuilder SDK are you using?

**Comment by singhsurya** [comment]
@nwhitmont  we are using bot builder SDK version 3.8.1

**Comment by JasonSowers** [comment]
Going to close this issue as you say it has resolved.  Please continue the conversation as needed here.

**Comment by singhsurya** [comment]
@JasonSowers I posted this question to know if Bot framework service was down at the specified time.
