### ISSUE TITLE
Bot crashes on 3 Thumbnail Cards dialog choice prompt

### ISSUE THREAD

**Issue by akontsevich** [Microsoft/BotBuilder#3367]
[message.json.txt](https://github.com/Microsoft/BotBuilder/files/1242678/message.json.txt)

## System Information
* SDK Language: Node.js
* SDK Version: 3.9.1
* Development Environment: localhost

## Issue Description
Bot crashes on simple thing: create 3 **ThumbnailCard**s with just 1 button in each, add them as attachment to a message, then call `builder.Prompts.choice(session, msg, buttons);` and bot crashes and does not show me any buttons and unable to go to the next waterfall step.

If I try only 1 ThumbnailCard with 3 buttons in it - works fine, but they aligned vertically - not what I want - horizontal layout.

## Code Example
My first waterfall step of my root dialog code:
```
[
    /**
     * @param {Session} session
     */
    function (session, args) {
        // Clear conversation data on new search - empty object
        session.conversationData = {};
        
        var buttons = ["Send Message", "New Search", "Agent"];
        var options = { listStyle: builder.ListStyle.button };
        var msg = new builder.Message(session).attachmentLayout(builder.AttachmentLayout.carousel);
        
        if(args && args.reprompt)
            msg.text("How can I help You with Your hotel search?");
        else
            msg.text("Hello there. How can I help You with Your hotel search today?");

        const cards = [
            new builder.ThumbnailCard(session).buttons([
                new builder.CardAction(session).title("Send Message").value("Send Message").type("imBack")
            ]),
            new builder.ThumbnailCard(session).buttons([
                builder.CardAction.openUrl(session, "http://app.selectrooms.co", "New Search")
            ]),
            new builder.ThumbnailCard(session).buttons([
                new builder.CardAction(session).title("Agent").value("Agent").type("imBack")
            ])
        ];
        msg.addAttachment(cards);
        
        builder.Prompts.choice(session, msg, buttons, options);
    },
...
]
```

## Steps to Reproduce the Issue
1. Created carousel cards with 3 **ThumbnailCard**s with just 1 button in each
2. User enters `hi`
3. Bot crashes and does not show buttons or cards

## Expected Behavior
Show 3 buttons in one line with specified actions.

## Actual Results
Error log in console:
```
ChatConnector: message received.
User `Bot` with Id: `default-bot` connected to bot!
ChatConnector: message received.
UniversalBot("*") routing "hi" from "emulator"
Session.beginDialog(/)
/ - waterfall() step 1 of 5
/ - Session.beginDialog(BotBuilder:prompt-choice)
.BotBuilder:prompt-choice - Session.send()
.BotBuilder:prompt-choice - Session.sendBatch() sending 1 message(s)
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at addWrite (../Src/node_modules/botbuilder/lib/bots/ChatConnector.js:340:29)
    at ChatConnector.saveData (../Src/node_modules/botbuilder/lib/bots/ChatConnector.js:355:21)
    at ../Src/node_modules/botbuilder/lib/bots/UniversalBot.js:483:21
    at UniversalBot.tryCatch (../Src/node_modules/botbuilder/lib/bots/UniversalBot.js:503:13)
    at UniversalBot.saveStorageData (../Src/node_modules/botbuilder/lib/bots/UniversalBot.js:480:14)
    at Object.onSave (../Src/node_modules/botbuilder/lib/bots/UniversalBot.js:327:27)
    at Session.onSave (../Src/node_modules/botbuilder/lib/Session.js:584:22)
    at Session.sendBatch (../Src/node_modules/botbuilder/lib/Session.js:427:14)
    at Timeout.<anonymous> (../Src/node_modules/botbuilder/lib/Session.js:655:23)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
.BotBuilder:prompt-choice - ERROR: Converting circular structure to JSON
.BotBuilder:prompt-choice - Session.endConversation()
Session.sendBatch() sending 2 message(s)
```
**P.S.** Also `msg` converted to JSON with `util.inspect(msg, {showHidden: true, depth: null, breakLength: 120})` attached.

**Comment by akontsevich** [comment]
Fixed the code:
```
        var msg = new builder.Message(session)
            .text(text)
            .attachmentLayout(builder.AttachmentLayout.carousel)
            .attachments(cards);
```
Changed `addAttachment` to `attachments` - works now. However cards are too wide, how to reduce their width to just buttons widths?

**Comment by JasonSowers** [comment]
glad you got it working 👍
