### ISSUE TITLE
[Question] Dynamically loaded dialogs fails to cast into IDialog<object>

### ISSUE THREAD

**Issue by Enghouse-CCSP-PS** [Microsoft/BotBuilder#3462]
Hello,

We used an answer in #2407 and it helped to make stuff work in ASPX project, but now we are in self hosted environment and start controller from there. 

We try to load dialogs dynamically the following way:
1) Load instance of IDialog<object> from dll
2) Create next dialog from JSON file and continue there
3) Continue as needed

When we try to load simple EchoBot - everything is working fine, but as long as next step is involved or we try to load JSON, we give the following exception:

**Object of type 'OrderBotSample.CustomerEntryDialog' cannot be converted to type 'Microsoft.Bot.Builder.Dialogs.IDialog`1[System.Object]'.**
```
Stack trace:
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.RuntimeType.CheckValue(Object value, Binder binder, CultureInfo culture, BindingFlags invokeAttr)
   at System.Reflection.RtFieldInfo.UnsafeSetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture)
   at System.Runtime.Serialization.FormatterServices.SerializationSetValue(MemberInfo fi, Object target, Object value)
   at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
   at System.Runtime.Serialization.ObjectManager.DoNewlyRegisteredObjectFixups(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.RegisterObject(Object obj, Int64 objectID, SerializationInfo info, Int64 idOfContainingObj, MemberInfo member, Int32[] arrayIndex)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.RegisterObject(Object obj, ParseRecord pr, ParseRecord objectPr, Boolean bIsString)
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObjectEnd(ParseRecord pr)
   at System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Microsoft.Bot.Builder.Internals.Fibers.FormatterStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.TryLoad(T& item) in C:\Projects\CSharp\Library\Microsoft.Bot.Builder\Fibers\Store.cs:line 65
   at Microsoft.Bot.Builder.Internals.Fibers.ErrorResilientStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore<T>.TryLoad(T& item) in C:\Projects\CSharp\Library\Microsoft.Bot.Builder\Fibers\Store.cs:line 108
```
   
And dialog starts over again.

Our code is pretty straightforward, we start in controller:

```
await Conversation.SendAsync(activity, () =>
{
   var assembly = Assembly.LoadFrom(@"..\OrderBotSample.dll");
   IDialog<object> dialog = (IDialog<object>)assembly.CreateInstance("OrderBotSample.CustomerEntryDialog");
   return dialog;
});
```

CustomerEntryDialog is as following:

```
namespace OrderBotSample
{
    [Serializable]
    public class CustomerEntryDialog : IDialog<object>
    {
        private static readonly Logger _logger = LogManager.GetCurrentClassLogger();
        public CustomerEntryDialog()
        {
            Debug.WriteLine("CustomerEntryDialog: Constractor Created");
        }

        public async Task StartAsync(IDialogContext context)
        {
            _logger.Trace(string.Empty);
            context.Wait(MessageReceivedAsync);
        }

        public async Task MessageReceivedAsync(IDialogContext context, IAwaitable<IMessageActivity> argument)
        {
            _logger.Trace("In");
            context.Forward(FormDialog.FromForm(() => BuildJsonForm("..\ServiceSelect.json"), FormOptions.PromptInStart), DialogCompleted, context.Activity.AsMessageActivity()).Wait();
            _logger.Trace("Out");
            context.Wait(MessageReceivedAsync);
        }

        private IForm<JObject> BuildJsonForm(string strPath)
        {
            using (var stream = File.OpenRead(strPath))
            {
                var schema = JObject.Parse(new StreamReader(stream).ReadToEnd());
                return new FormBuilderJson(schema)
                    .AddRemainingFields()
                    .Build();
            }
        }
        private async Task DialogCompleted(IDialogContext context, IAwaitable<object> result)
        {
            context.Done(true);
            return;           
        }
    }
}

```
ServiceSelect.json:

```
{
  "type": "object",
  "required": [
    "ServiceSelect",
    "CustomerId",
    "Language"
  ],
  "Templates": {
    "NotUnderstood": {
      "Patterns": [ "I do not understand \"{0}\".", "Try again, I don't get \"{0}\"." ]
    },
    "EnumSelectOne": {
      "Patterns": [ "Please let me know the {&}: {||}" ],
      "ChoiceStyle": "PerLine"
    }
  },
  "properties": {
    "ServiceSelect": {
      "Prompt": {
        "Patterns": [ "What service you would like to get ? {||}" ]
      },

      "Before": [ { "Message": [ "Welcome to our bot selfservice example!" ] } ],
      "Describe": { "Image": "https://placeholdit.imgix.net/~text?txtsize=16&txt=myBot&w=125&h=40&txttrack=0&txtclr=000&txtfont=bold" },

      "type": [
        "string",
        "null"
      ],
      "enum": [
        "Queue 1",
        "Queue 2",
        "Check Order",
        "Open Case"
      ]
    },
    "CustomerId": {
      "type": [ "number", "null" ],
      "Active": "return (string) state[\"ServiceSelect\"] == \"Check Order\";"
    },
    "Language": {
      "Prompt": {
        "Patterns": [ "In what Language  do you want get service? {||}" ]
      },
      "type": [
        "string",
        "null"
      ],
      "enum": [
        "English",
        "Japanese"
      ],
      "Active": "return (string) state[\"ServiceSelect\"] != \"Check Order\";"
    },

    "PhoneNumber": {
      "type": [ "string", "null" ],
      "pattern": "(\\(\\d{3}\\))?\\s*\\d{3}(-|\\s*)\\d{4}",
      "Active": "return (string) state[\"ServiceSelect\"] != \"Check Order\";"
    }
  },
  "OnCompletion":  "context.Done<bool>(true);" 
}

```
Tried couple of ways, but it all comes down to this issue.

Any ideas? Any possibilities to load dialogs dynamically from outer dlls?

**Comment by vovanb** [comment]
We have same issue - any response about exception and workaround?

**Comment by EricDahlvang** [comment]
@vovanb & @Enghouse-CCSP-PS 

I'm not sure why the error is occurring, but have either of you tried  Assembly.LoadFile instead of Assembly.LoadFrom ?

**Comment by EricDahlvang** [comment]
Closing due to no response.
