### ISSUE TITLE
Every incoming dialog triggers error code on SKYPE only (not FB)

### ISSUE THREAD

**Issue by SerendioSoftwares** [Microsoft/BotBuilder#3518]
## Bot Info 

* SDK Platform:Node JS
* SDK Version: 
* Active Channels: Skype, FB
* Microsoft ID: 8d5325bb-f0a7-4b02-9358-3e1ed49e3a8f
* Deployment Environment: Self Hosted

## Issue Description
Error code appears whenever user input is received from skype.
It proceeds to the next dialog step until it completely freezes in a certain step.

## Code Example
Error: Request to 'https://smba.trafficmanager.net/apis/v3/conversations/29%3A1p9bvTpYWEZqHpCECCnCjNrmUg9CR3riwatwg_wWFULQ/activities' failed: [400] Bad Request
    at Request._callback (/root/chatbot/node_modules/botbuilder/lib/bots/ChatConnector.js:512:46)
    at Request.self.callback (/root/chatbot/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/root/chatbot/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/root/chatbot/node_modules/request/request.js:1091:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at IncomingMessage.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

## Expected Behavior
No error and proceed to next step

**Comment by stevengum97** [comment]
What is your bot's application ID? This will help us in diagnosing what the problem is.

**Comment by stevengum97** [comment]
@SerendioSoftwares, I've been able to engage in a conversation with your bot and haven't seen any errors in the logs for Skype from dev.botframework.com. Nor have I seen any strange behavior from the bot itself. Does your bot show any errors locally?

**Comment by nwhitmont** [comment]
Reopen if further questions
