### ISSUE TITLE
[Node.js SDK] 400 Bad Request When Sending Hint Message With HeroCards

### ISSUE THREAD

**Issue by zidaneymar** [Microsoft/BotBuilder#3529]
## Bot Info 
* Bot handle: 
* App ID: 6bfcad44-e701-421d-8425-ae8c7dd20300
* SDK Platform: Node.js
* SDK Version: 3.10.2
* Active Channels: FB Skype
* Deployment Environment: Azure App Service

## Issue Description
I try to send a list of HeroCard and a hint message to users, but I notice that the hint message below the card can't be sent successfully, (I have tried to change the content of the message). 

**Here is the log:**

Skype:
Error: Request to 'https://smba.trafficmanager.net/apis/v3/conversations/29%3A1ZyCVUOXA8q0vYajS9XklxakeLT_2J5mwh9FKXLXnReLH-RBdTXttRImdz_9yb7cZ/activities' failed: [400] Bad Request
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:537:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

FB:
Error: Request to 'https://facebook.botframework.com/v3/conversations/1461125910591107-212312559305090/activities/mid.%24cAACb7mQaLElk9GRu-Vewx8mNDBUo' failed: [400] Bad Request
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:537:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1085:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

## Expected Behavior

![image](https://user-images.githubusercontent.com/9328933/30911463-499a71bc-a3bb-11e7-8c64-a278413082c2.png)

## Actual Results

![image](https://user-images.githubusercontent.com/9328933/30911165-271b900e-a3ba-11e7-867c-0e0267a43410.png)
There should be an extra message below the card. Other messages can be shown.

**Comment by stevengum97** [comment]
@zidaneymar Can you provide the code you're using to send the cards and the message?

**Comment by zidaneymar** [comment]
I have found the reason: 
Sending two messages **at the same time** will lead to this error.
