### ISSUE TITLE
[Slack] sourceEvent as object does not work in Slack

### ISSUE THREAD

**Issue by roadhump** [Microsoft/BotBuilder#3551]
## Bot Info 
* SDK Platform: Node.js
* SDK Version: 3.10.2

## Issue Description
When we set `sourceEvent` as object on `Message` and send it to Slack, it will throw error. `sourceEvent` as string will work fine .

```
Error: Request to 'https://slack.botframework.com/v3/conversations/B3XR711H8%3AT16T1FTK2%3AD3XTGB1EY/activities/c7f9e032867f469ea8a713b37ef1d2de' failed: [400] Bad Request
        at Request._callback (botbuilder/node_modules/botbuilder/lib/bots/ChatConnector.js:537:46)
        at Request.self.callback (botbuilder/node_modules/request/request.js:187:22)
        at emitTwo (events.js:106:13)
        at Request.emit (events.js:191:7)
        at Request.<anonymous> (botbuilder/node_modules/request/request.js:1044:10)
        at emitOne (events.js:96:13)
        at Request.emit (events.js:188:7)
        at IncomingMessage.<anonymous> (botbuilder/node_modules/request/request.js:965:12)
        at emitNone (events.js:91:20)
        at IncomingMessage.emit (events.js:185:7)
        at endReadableNT (_stream_readable.js:974:12)
        at _combinedTickCallback (internal/process/next_tick.js:74:11)
        at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

## Code Example

won't work
```
session.send(new Message(session).text('test').sourceEvent({
        slack: {foo: 'bar'}
    }))
```

will work 
```
session.send(new Message(session).text('test').sourceEvent({
        slack: 'hi'
    }))
```

**Comment by nwhitmont** [comment]
@roadhump How does this affect the functionality of your bot specifically?

What problem are you trying to solve here?

**Comment by fanidamj** [comment]
The issue seems inactive, closing the issue assuming it as resolved. Fee free to reopen if you have questions or comments.
