### ISSUE TITLE
 Error: Request to 'https://state.botframework.com/v3/botstate/webchat/users/---omitted---' failed: [400] Bad Request

### ISSUE THREAD

**Issue by cxfire16** [Microsoft/BotBuilder#3629]
## Bot Info 
* Bot handle: chuckAI  
* App ID:  2e2a70b5-3cfa-4369-979f-d68a9b46533b
* SDK Platform:  Node.js 
* SDK Version: 3.11.0
* Active Channels: Direct Line, WebChat
* Deployment Environment: Heroku, Auzure Bot Service, and Azure App Service

## Issue Description
Error 400 Bad Request

## Code Example
Fails after the user data is loaded.

## Reproduction Steps
1. Say hello to bot
2. Bot will not reply
3. Say hello again to the bot
4. Conversation will continue but will ultimately fail due to the preloaded data not persisting.

Setting the persistence to true will invoke the error 400
Setting the persistence to false will of course fail with the data unavailable.
The data I mean is the session.userData.

## Expected Behavior
On a locally hosted instance, the bot works perfectly. But upon deployment to the cloud, the error is encountered.

## Actual Results

2017-10-18T05:55:45.826423+00:00 app[web.1]: Message: hey there
2017-10-18T05:55:46.271398+00:00 app[web.1]: LOGIN SUCCESS
2017-10-18T05:55:46.373598+00:00 app[web.1]: PRODUCT LIST GET SUCCESS
2017-10-18T05:55:46.884315+00:00 app[web.1]: STAFF LIST GET SUCCESS
2017-10-18T05:55:46.885050+00:00 app[web.1]: PASS
2017-10-18T05:55:46.885075+00:00 app[web.1]: Message: hey there
2017-10-18T05:55:46.885158+00:00 app[web.1]: Active Context: undefined
2017-10-18T05:55:47.253779+00:00 app[web.1]: Error: Request to 'https://state.botframework.com/v3/botstate/webchat/users/LwNyQ9F43QZ' failed: [400] Bad Request
2017-10-18T05:55:47.253803+00:00 app[web.1]:     at Request._callback (/app/node_modules/botbuilder/lib/bots/ChatConnector.js:532:46)
2017-10-18T05:55:47.253804+00:00 app[web.1]:     at Request.self.callback (/app/node_modules/request/request.js:186:22)
2017-10-18T05:55:47.253805+00:00 app[web.1]:     at emitTwo (events.js:106:13)
2017-10-18T05:55:47.253806+00:00 app[web.1]:     at Request.emit (events.js:191:7)
2017-10-18T05:55:47.253807+00:00 app[web.1]:     at Request.<anonymous> (/app/node_modules/request/request.js:1163:10)
2017-10-18T05:55:47.253807+00:00 app[web.1]:     at emitOne (events.js:96:13)
2017-10-18T05:55:47.253808+00:00 app[web.1]:     at Request.emit (events.js:188:7)
2017-10-18T05:55:47.253809+00:00 app[web.1]:     at IncomingMessage.<anonymous> (/app/node_modules/request/request.js:1085:12)
2017-10-18T05:55:47.253810+00:00 app[web.1]:     at IncomingMessage.g (events.js:292:16)
2017-10-18T05:55:47.253810+00:00 app[web.1]:     at emitNone (events.js:91:20)
2017-10-18T06:04:15.467388+00:00 heroku[router]: at=info method=POST path="/api/messages" host=chuck-ai-conversation-bot-1.herokuapp.com request_id=5ab9e45c-e2a4-430b-9e7e-752f85633711 fwd="137.116.153.103" dyno=web.1 connect=0ms service=11ms status=202 bytes=117 protocol=https
2017-10-18T06:04:18.512109+00:00 app[web.1]: []
2017-10-18T06:04:18.512418+00:00 app[web.1]: FAIL

![image](https://user-images.githubusercontent.com/13092237/31703289-95896110-b40e-11e7-91cb-0e9703ef6cd0.png)

**Comment by JasonSowers** [comment]
Can you please share the request including headers you are using to call the bot?

**Comment by cxfire16** [comment]
I use only the web preview and the emulator to test the bot. I use no other clients at the moment. I believe I found the root cause of the problem. Could it be the default state service going over the 32kb limit? Although it is documented that using Custom State Client is way better, the error never pointed out that it was running out of storage. I ran a test to confirm my theory. I removed most of the userData to see if it causes the issue, it worked. I noticed this when the issue led me to various developers and I realized I was still using the default state service from the demos. I'd like to ask for confirmation regarding this issue. A big thanks!

**Comment by JasonSowers** [comment]
Yes, the state storage has a limit, this was most likely the cause of your issues.  We highly recommend using a custom state client 👍

**Comment by cxfire16** [comment]
Issue now resolved. I'd like to suggest errors like this to give more details as it took me a while to hunt it down. The error description was too way broad I had to test everything end to end. Anyways, thank you for the quick response.

**Comment by JasonSowers** [comment]
You're welcome and good luck!
