### ISSUE TITLE
setTimeout throws 500 exception while using cortana with bot framework

### ISSUE THREAD

**Issue by potatoParadox** [Microsoft/BotBuilder#3643]
## Bot Info 
* Bot handle: EchoTestHandle  
* App ID: bf7c0616-9744-424e-b71f-ab7c3b1cdacc
* SDK Platform: Node.js
* SDK Version: 3.11
* Active Channels: Cortana, WebChat
* Deployment Environment: ngrok

## Issue Description
setTimeout throws 500 exception while using cortana with bot framework. It works fine with the web chat, and emulator

## Code Example

var bot = new builder.UniversalBot(connector, function (session) {
    session.send("Hello");
    setTimeout(function () {
                session.send("This does not execute in Cortana");
         }, 1000);
});

## Expected Behavior
I should be able to make async requests

## Actual Results
Error: Request to 'https://CortanaBFChannelWestUS.azurewebsites.net/v3/conversations/978fef30-343f-4e97-8b1c-61142f2071cf/activities/DAc2oW4tPca' failed: [500] Internal Server Error
    at Request._callback (/Users/ayushgera/Development/Hack2017/cortanaBot/node_modules/botbuilder/lib/bots/ChatConnector.js:532:46)
    at Request.self.callback (/Users/ayushgera/Development/Hack2017/cortanaBot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/Users/ayushgera/Development/Hack2017/cortanaBot/node_modules/request/request.js:1163:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/Users/ayushgera/Development/Hack2017/cortanaBot/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:893:12)
    at doNTCallback2 (node.js:429:9)
    at process._tickDomainCallback (node.js:384:17)

**Comment by EricDahlvang** [comment]
@potatoParadox 

The Cortana channel does not currently accept proactive messages. It is a highly requested feature, and should be available sometime soon. However, there is currently no timeline.
