### ISSUE TITLE
[Question] Bot Application not replying and giving error 401 (Unauthorized)?

### ISSUE THREAD

**Issue by akgmca** [Microsoft/BotBuilder#3694]
## Bot Info 
* App ID: 8af0b8b5-5f0d-4a31-89a2-8c5fbb25f962
* SDK Platform:  .NET
* Active Channels: Skype
* Deployment Environment: Azure App Service

## Issue Description
I have created a bot application it is working on the Emulator as expected and I have deployed it on the Azure App Service. When I am connecting it with Emulator without AppId and Password then it is working but with AppId and Password it is not working.

Also I have added it to skype and web chat channels. It is not working with these channel as well. it is showing the below exception while replying. Before replying the expected data is returning.

Error: System.UnauthorizedAccessException: Authorization for Microsoft App ID 8af0b8b5-5f0d-4a31-89a2-8c5fbb25f962 failed with status code Unauthorized and reason phrase 'Unauthorized' ---&gt; System.Net.Http.HttpRequestException: Response status code does not indicate success: 401 (Unauthorized).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Microsoft.Bot.Connector.JwtTokenRefresher.&lt;SendAsync&gt;d__2.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.Bot.Connector.JwtTokenRefresher.&lt;SendAsync&gt;d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.&lt;FinishSendAsync&gt;d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Bot.Connector.Conversations.&lt;ReplyToActivityWithHttpMessagesAsync&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.&lt;ReplyToActivityAsync&gt;d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.AlwaysSendDirect_BotToUser.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.InputHintQueue.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IMessageQueue-QueueMessageAsync&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.AutoInputHint_BotToUser.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.MapToChannelData_BotToUser.&lt;PostAsync&gt;d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.LogBotToUser.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync&gt;d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogContext.&lt;Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync&gt;d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Extensions.&lt;PostAsync&gt;d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at StockPriceBotForEmulator.Dialogs.RootDialog.&lt;MessageReceivedAsync&gt;d__1.MoveNext()

## Code Example

using System;
using System.Threading.Tasks;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Connector;
using StockPriceBotForEmulator.Service;

namespace StockPriceBotForEmulator.Dialogs
{
    [Serializable]
    public class RootDialog : IDialog<object>
    {
        public Task StartAsync(IDialogContext context)
        {
            context.Wait(MessageReceivedAsync);

            return Task.CompletedTask;
        }

        private async Task MessageReceivedAsync(IDialogContext context, IAwaitable<object> result)
        {
            try
            {
                var activity = await result as Activity;

                //var stockSymbol = activity.Text;
                //var replyMessage = await GetStock(stockSymbol);

                var replyMessage = string.Empty;
                var Phrase = activity.Text;
                ServiceLogger.LogAuditTrail(string.Format("Input Text: {0}", Phrase.ToString()));
                var luisResponse = await LuisService.ParseUserInput(Phrase);
                ServiceLogger.LogAuditTrail(string.Format("Input Text LUIS Object Response: {0}", luisResponse.ToString()));
                if (luisResponse.intents.Length > 0)
                {
                    switch (luisResponse.intents[0].intent)
                    {
                        case "StockPrice":
                            var stockSymbol = luisResponse.entities[0].entity;
                            ServiceLogger.LogAuditTrail(string.Format("Input Text LUIS Keyword: {0}", stockSymbol.ToString()));
                            replyMessage = await GetStock(stockSymbol);
                            ServiceLogger.LogAuditTrail(string.Format("Input Text Stock Response: {0}", replyMessage.ToString()));
                            break;
                        case "None":
                            replyMessage = $"Sorry!!! I did not understsnd what you said.";
                            break;
                    }
                }
                else
                {
                    replyMessage = $"Sorry!!! I did not understsnd what you said.";
                }
                ServiceLogger.LogAuditTrail(string.Format("Input Text Stock Final Response: {0}", replyMessage));
                string AppId = System.Configuration.ConfigurationManager.AppSettings["MicrosoftAppId"].ToString();
                string AppPassword = System.Configuration.ConfigurationManager.AppSettings["MicrosoftAppPassword"].ToString();
                ServiceLogger.LogAuditTrail(string.Format("AppId: {0}", AppId));
                ServiceLogger.LogAuditTrail(string.Format("Password: {0}", AppPassword));
                ServiceLogger.LogAuditTrail(string.Format("ServiceUrl: {0}", activity.ServiceUrl));

                ConnectorClient CC = new ConnectorClient(new Uri(activity.ServiceUrl), new MicrosoftAppCredentials(AppId, AppPassword));
                ServiceLogger.LogAuditTrail(string.Format("Credentials: {0}", CC.Credentials.ToString()));

                // return our reply to the user
                await context.PostAsync(replyMessage);

                context.Wait(MessageReceivedAsync);
            }
            catch(Exception ex)
            {
                ServiceLogger.LogAuditTrail(string.Format("Error: {0}", ex));
                ServiceLogger.LogError(string.Format("Exception: {0}", ex));
            }
        }

        private async Task<string> GetStock(string Symbol)
        {
            var stockItem = await StockService.GetStockPrice(Symbol);
            string returnValue = string.Empty;
            if (stockItem.Status == "FAIL")
            {
                returnValue = $"I could not find any value for the symbol '{Symbol}'";
            }
            else
            {
                returnValue = $" Stock Name: '{stockItem.Symbol}', Stock Last Price: '{stockItem.LastPrice}'";
            }
            ServiceLogger.LogAuditTrail(string.Format("Input Text Stock Response: {0}", returnValue.ToString()));
            return returnValue;
        }
    }
}

using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.Bot.Builder.Dialogs;
using Microsoft.Bot.Connector;
using Microsoft.AspNetCore.Mvc;
using StockPriceBotForEmulator.Service;

namespace StockPriceBotForEmulator.Controllers
{
    [Route("api/[controller]")]
    [BotAuthentication]
    public class MessagesController : Controller
    {
        /// <summary>
        /// POST: api/Messages
        /// Receive a message from a user and reply to it
        /// </summary>
        [HttpPost]
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (activity?.Type == ActivityTypes.Message)
            {
                await Conversation.SendAsync(activity, () => new Dialogs.RootDialog());
            }
            else
            {
                HandleSystemMessage(activity);
            }

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        private Activity HandleSystemMessage(Activity message)
        {
            if (message.Type == ActivityTypes.DeleteUserData)
            {
                // Implement user deletion here
                // If we handle user deletion, return a real message
            }
            else if (message.Type == ActivityTypes.ConversationUpdate)
            {
                // Handle conversation state changes, like members being added and removed
                // Use Activity.MembersAdded and Activity.MembersRemoved and Activity.Action for info
                // Not available in all channels
            }
            else if (message.Type == ActivityTypes.ContactRelationUpdate)
            {
                // Handle add/remove from contact lists
                // Activity.From + Activity.Action represent what happened
            }
            else if (message.Type == ActivityTypes.Typing)
            {
                // Handle knowing tha the user is typing
            }
            else if (message.Type == ActivityTypes.Ping)
            {
            }

            return null;
        }
    }
}

## URL
http://stockpricebotforemulator20171025114533.azurewebsites.net/api/messages
![emulator_output](https://user-images.githubusercontent.com/32123445/32223833-08629ea8-be65-11e7-9b94-fd11fc5c9594.png)
![skype_output](https://user-images.githubusercontent.com/32123445/32223834-08a89a52-be65-11e7-9aad-61fd25cd19a2.png)
![webchat_output](https://user-images.githubusercontent.com/32123445/32223836-08f056a8-be65-11e7-8d42-dea93ab950b6.png)

**Comment by JasonSowers** [comment]
Try creating a new bot in the [dev portal](https://dev.botframework.com) and generating a new app id and password and see if that works when you plug those into your config.

**Comment by EricDahlvang** [comment]
It appears that the  BotAuthentication attribute is not being used.  Is this an asp.net core application?  asp.net core is not currently supported by the Bot Builder.  This pull request https://github.com/Microsoft/BotBuilder/pull/3472 that is currently being reviewed.  You might be able to download the source, and reference it locally.

**Comment by akgmca** [comment]
I have created the new app with new Bot Id and Password but still the problem is same and showing the same error.

Please Help......

**Comment by EricDahlvang** [comment]
@akgmca Are you creating asp.net core applications?

**Comment by akgmca** [comment]
I am creating the Cot Application Core 2.0

**Comment by JasonSowers** [comment]
.NET core is not supported at this time, please join the conversation here #572
