### ISSUE TITLE
 Exception on deserializing stored data! Stack has been cleared

### ISSUE THREAD

**Issue by AmirSasson** [Microsoft/BotBuilder#3811]
## Bot Info : Software Genie Staging

* App ID: 40a785d4-e9c3-4731-a0a8-14f618a3c808
* SDK Platform: .NET 
* SDK Version: 3.11.0
* Active Channels: facebook, skype
* Deployment Environment: vs2017

## Issue Description
just upgraded my *Microsoft.Bot.Builder* from 3.9.0.0 to  3.11.0
my dialogs stack is lost as it cannot be deserielized each time a message arrives to the bot.
each message i see in the output logs:
```
Exception on deserializing stored data! Stack has been cleared.
 Details: System.Runtime.Serialization.SerializationException: The object with ID 161 was referenced in a fixup but does not exist.
   at System.Runtime.Serialization.ObjectManager.GetCompletionInfo(FixupHolder fixup, ObjectHolder& holder, Object& member, Boolean bThrowIfMissing)
   at System.Runtime.Serialization.ObjectManager.CompleteObject(ObjectHolder holder, Boolean bObjectFullyComplete)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at Microsoft.Bot.Builder.Internals.Fibers.FormatterStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore< T>.TryLoad(T& item)
   at Microsoft.Bot.Builder.Internals.Fibers.ErrorResilientStore`1.Microsoft.Bot.Builder.Internals.Fibers.IStore< T>.TryLoad(T& item)
```

## Reproduction Steps
1. pushing a dialog to the root stack
2. send a message

## Expected Behavior
the user states is able to be loaded, and stack stays.

## Actual Results
stack got cleared and i am unable to read user state

**Comment by JasonSowers** [comment]
@AmirSasson can you please post your code so we can better assist you?

**Comment by EricDahlvang** [comment]
Try sending ' /deleteProfile' to the bot, to reset the dialog stack.

**Comment by AmirSasson** [comment]
@EricDahlvang I will try this and publish the results.
btw, the code is the most straight full one,  like having a rootDialog, and then pushing into stack another child dialog. the result would be always error when deserializing, and therefore returning to the root dialog.

**Comment by EricDahlvang** [comment]
@AmirSasson also, are you using a custom state service or the default?  The default is intended only for prototyping.

https://blog.botframework.com/2017/07/18/Saving-State-Azure-Extensions/

**Comment by AmirSasson** [comment]
@EricDahlvang , Gee! i wasnt aware of that at all! Thanks

**Comment by EricDahlvang** [comment]
Closing this issue.  If you need further assistance, please create a new issue.
