### ISSUE TITLE
`builder.IntentDialog().matches()` doesn't support `string[]`

### ISSUE THREAD

**Issue by lijiarui** [Microsoft/BotBuilder#3816]
## Bot Info 
* App ID: 
* SDK Platform: Node.js
* SDK Version: 3.12.0
* Active Channels: Wechat
* Deployment Environment: other

## Issue Description

feature request
I found `botbuilder.d.ts` had defined the `matches` function as follows, it doesn't support string[] here as other matches function. May I ask is there any special reason for this design, or this will be added in the future?

In my situation, sometimes I would like to match several intents here.
```ts
export class IntentDialog extends Dialog {
    /**
     * Invokes a handler when a given intent is detected in the users utterance.
     *
     * > __NOTE:__ The full details of the match, including the list of intents & entities detected, will be passed to the [args](/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentrecognizerresult) of the first waterfall step or dialog that's started.
     * @param intent
     * * __intent:__ _{RegExp}_ - A regular expression that will be evaluated to detect the users intent.
     * * __intent:__ _{string}_ - A named intent returned by an [IIntentRecognizer](/en-us/node/builder/chat-reference/interfaces/_botbuilder_d_.iintentrecognizer) plugin that will be used to match the users intent.
     * @param dialogId
     * * __dialogId:__ _{string} - The ID of a dialog to begin when the intent is matched.
     * * __dialogId:__ _{IDialogWaterfallStep[]}_ - Waterfall of steps to execute when the intent is matched.
     * * __dialogId:__ _{IDialogWaterfallStep}_ - Single step waterfall to execute when the intent is matched. Calling a built-in prompt or starting a new dialog will result in the current dialog ending upon completion of the child prompt/dialog. 
     * @param dialogArgs (Optional) arguments to pass the dialog that started when `dialogId` is a _{string}_.
     */
    matches(intent: RegExp|string, dialogId: string|IDialogWaterfallStep[]|IDialogWaterfallStep, dialogArgs?: any): IntentDialog;
}
```
## Code Example

When I try the following one, It can work as expect
```ts
const aPlacePrompt = new builder.IntentDialog()
    .matches('replyExactPlace', somefunction)
```

While when I try the following one, it will throw an error.(the difference is matches array instead of string.)
```ts
const aPlacePrompt = new builder.IntentDialog()
    .matches(['replyExactPlace'], somefunction)
```

## Error log as follows
I founde error will jump to RegExpRecognizer, while I think maybe it should jump into intentRecognizer.

Error log as follows
```shell
Error: Expression not found for locale 'en'.
    at RegExpRecognizer.onRecognize (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/RegExpRecognizer.js:48:20)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:18:23
    at next (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:50:17)
    at RegExpRecognizer.IntentRecognizer.isEnabled (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:53:9)
    at RegExpRecognizer.IntentRecognizer.recognize (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:10:14)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:68:28
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:181:20
    at replenish (/home/ubuntu/workspace/node_modules/async/lib/async.js:319:21)
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:330:15
    at Object.async.forEachLimit.async.eachLimit (/home/ubuntu/workspace/node_modules/async/lib/async.js:220:35)
    at IntentRecognizerSet.recognizeInParallel (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:66:15)
    at IntentRecognizerSet.onRecognize (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:52:18)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:18:23
    at next (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:50:17)
    at IntentRecognizerSet.IntentRecognizer.isEnabled (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:53:9)
    at IntentRecognizerSet.IntentRecognizer.recognize (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:10:14)
    at IntentDialog.recognize (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentDialog.js:97:26)
    at UniversalBot.Library.findActiveDialogRoutes (/home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:117:24)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:243:31
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:718:13
    at async.forEachOf.async.eachOf (/home/ubuntu/workspace/node_modules/async/lib/async.js:233:13)
    at _parallel (/home/ubuntu/workspace/node_modules/async/lib/async.js:717:9)
    at Object.async.parallel (/home/ubuntu/workspace/node_modules/async/lib/async.js:731:9)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:241:23
    at UniversalBot.Library.recognize (/home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:68:13)
    at UniversalBot.Library.defaultFindRoutes (/home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:236:14)
    at UniversalBot.Library.findRoutes (/home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:85:18)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/UniversalBot.js:387:21
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:181:20
    at Object.async.forEachOf.async.eachOf (/home/ubuntu/workspace/node_modules/async/lib/async.js:233:13)
    at Object.async.forEach.async.each (/home/ubuntu/workspace/node_modules/async/lib/async.js:209:22)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/UniversalBot.js:386:19
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/bots/Library.js:64:17
    at next (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:68:17)
    at IntentRecognizerSet.IntentRecognizer.filter (/home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:71:9)
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:20:31
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:80:17
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:52:16
    at replenish (/home/ubuntu/workspace/node_modules/async/lib/async.js:306:28)
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:326:29
    at /home/ubuntu/workspace/node_modules/async/lib/async.js:44:16
    at /home/ubuntu/workspace/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:72:21
    at TextRequest.<anonymous> (/home/ubuntu/workspace/node_modules/api-ai-recognizer/index.js:86:21)
    at emitOne (events.js:96:13)
    at TextRequest.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/home/ubuntu/workspace/node_modules/apiai/module/json_api_request.js:46:26)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
```

**Comment by lijiarui** [comment]
Oh, I found `matchAny` instead
