### ISSUE TITLE
Bot not working with Telegram

### ISSUE THREAD

**Issue by arunnanjundaswamy** [Microsoft/BotBuilder#384]
Hi,

My bot is not working using the Telegram channel but works fine with the other channels. It show the below message.
"Sorry, BBChatBot is having a problem responding right now"

Thanks

**Comment by tomlm** [comment]
Could it be you have bad dialog state?

BBChatbot BBChatBot InternalServerError
{
  "message": "An error has occurred.",
  "exceptionMessage": "invalid need: expected Wait, have Done",
  "exceptionType": "Microsoft.Bot.Builder.Internals.Fibers.InvalidNeedException",
  "stackTrace": "   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.ValidateNeed(Need need)
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.Microsoft.Bot.Builder.Internals.Fibers.IWait.Post[D](D item)
   at Microsoft.Bot.Builder.Internals.Fibers.Extensions.Post[C,T](IFiber`1 fiber, T item)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__21`1.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DelegatingDialogTask.<PostAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.LocalizedDialogTask.<PostAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DelegatingDialogTask.<PostAsync>d__8`1.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.ScoringDialogTask`1.<PostAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.Extensions.<PostAsync>d__6`2.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__4`1.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__2`1.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BBChatBot.MessageHandler.BbBotMessageHandler.<OnMessage>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BBChatBot.Base.MessageHandler.BaseMessageHandler.<Act>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BBChatBot.Controllers.MessagesController.<Post>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown
---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}

**Comment by arunnanjundaswamy** [comment]
This has been corrected. But the issue still persists even after the Bot restart (hosted in azure) and deleting the conversation in telegram.

**Comment by eanders-MS** [comment]
@arunnanjundaswamy What is the failure you're seeing now?

**Comment by arunnanjundaswamy** [comment]
I am able to access the Bot from other Channels. But still same issue in the Telegram. I restarted the bot hosted in azure and deleted the conversation history in the Telegram for this bot.

Error in Telegram (same error is show under for Telegram channel in "MyBots" page)
"Sorry, BBChatBot is having a problem responding right now."

Thanks

**Comment by arunnanjundaswamy** [comment]
How do I rectify this? Please help.

Thanks

**Comment by eanders-MS** [comment]
From the end-user side, you can issue a /deleteprofile command from Telegram to reset the dialog state for the session. Issue #340 describes a way to reset the dialog state programmatically from within the bot's message controller.

**Comment by eanders-MS** [comment]
Closing this issue. If you're still having trouble just leave a comment here and I'll reopen.
