### ISSUE TITLE
[Skype Calling] TypeError: Cannot read property 'id' of undefined"?

### ISSUE THREAD

**Issue by whoisstan** [Microsoft/BotBuilder#3844]
## Bot Info 
* App ID: 61dc1f31-db23-4ee6-bc5f-a278614c868e
* SDK Platform: Node 8.9.0
* SDK Version: 3.12.0
* Active Channels: Skype
* Deployment Environment: Heroku

## Issue Description
Getting a "TypeError: Cannot read property 'id' of undefined" Exception when in the call response dialog.

TypeError: Cannot read property 'id' of undefined
    at /app/node_modules/botbuilder/lib/bots/UniversalBot.js:144:51
    at /app/node_modules/botbuilder/lib/bots/UniversalBot.js:427:53
    at UniversalBot.tryCatch (/app/node_modules/botbuilder/lib/bots/UniversalBot.js:516:13)
    at next (/app/node_modules/botbuilder/lib/bots/UniversalBot.js:427:23)
    at UniversalBot.eventMiddleware (/app/node_modules/botbuilder/lib/bots/UniversalBot.js:430:9)
    at /app/node_modules/botbuilder/lib/bots/UniversalBot.js:141:23
    at /app/node_modules/botbuilder/lib/bots/UniversalBot.js:472:53
    at UniversalBot.tryCatch (/app/node_modules/botbuilder/lib/bots/UniversalBot.js:516:13)
    at /app/node_modules/botbuilder/lib/bots/UniversalBot.js:472:23
    at UniversalBot.tryCatch (/app/node_modules/botbuilder/lib/bots/UniversalBot.js:516:13)
    at UniversalBot.lookupUser (/app/node_modules/botbuilder/lib/bots/UniversalBot.js:459:14)
    at /app/node_modules/botbuilder/lib/bots/UniversalBot.js:136:19
    at /app/node_modules/async/lib/async.js:181:20
    at replenish (/app/node_modules/async/lib/async.js:319:21)
    at /app/node_modules/async/lib/async.js:330:15
    at Object.async.forEachLimit.async.eachLimit (/app/node_modules/async/lib/async.js:220:35)
    at UniversalBot.receive (/app/node_modules/botbuilder/lib/bots/UniversalBot.js:133:15)
    at ChatConnector.onEventHandler (/app/node_modules/botbuilder/lib/bots/UniversalBot.js:88:60)
    at ChatConnector.onDispatchEvents (/app/node_modules/botbuilder/lib/bots/ChatConnector.js:438:22)
    at ChatConnector.dispatch (/app/node_modules/botbuilder/lib/bots/ChatConnector.js:447:18)
    at /app/node_modules/botbuilder/lib/bots/ChatConnector.js:137:27
    at /app/node_modules/botbuilder/lib/bots/OpenIdMetadata.js:21:17
    at Request._callback (/app/node_modules/botbuilder/lib/bots/OpenIdMetadata.js:58:21)
    at Request.self.callback (/app/node_modules/request/request.js:188:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/app/node_modules/request/request.js:1171:10)
    at emitOne (events.js:116:13)","time":"2017-11-29T15:18:04.581Z","v":0}

## Code Example
```js
var builder = require('botbuilder');

var chatConnector = new builder.ChatConnector({
    appId: appId,
    appPassword: appPassword
});

var chatBot = new builder.UniversalBot(chatConnector)

let greeting = "hi there";
chatBot.dialog('/', [
    (session) => {
        session.send(greeting);
    }]
);
router.route('/botframework_call/' + name)
.post( chatConnector.listen() );
```

## Reproduction Steps
1. Start Server
2. Call

## Expected Behavior
Hear the message

## Actual Results
Exception as above

**Comment by nwhitmont** [comment]
Hi @whoisstan - I am unable to reproduce the error with the provided code snippet. It doesn't look like it is a complete bot. For example the variable `router` is used, but not defined. Can you post your complete bot code?

You can also try deploying this known working Skype Calling bot sample:
https://github.com/nwhitmont/botframework-skype-calling-example-bot

Let me know if it works with the sample app. 

Another thing to note about Skype Calling bot is you need to turn on the "calling" feature in the Skype channel configuration page, and it can sometimes take time for the feature to become available in Skype.

**Comment by nwhitmont** [comment]
Hi @whoisstan  - Were you able to get the calling bot working using the example app?

**Comment by nwhitmont** [comment]
reopen if you are still having issues
