### ISSUE TITLE
Unexpected Exception when run Node/examples/basics-multiTurn/app.js

### ISSUE THREAD

**Issue by zixia** [Microsoft/BotBuilder#385]
When I run multiTurn example, and input `test`, will get this exception.

```javascript
$ node basics-multiTurn/app.js 
test

TypeError: match.handler is not a function
    at LuisDialog.IntentDialog.invokeIntent (/home/ubuntu/git/BotBuilder/Node/lib/dialogs/IntentDialog.js:153:23)
    at SessionConfidenceComparor.callback (/home/ubuntu/git/BotBuilder/Node/lib/dialogs/IntentDialog.js:36:31)
    at SessionConfidenceComparor.next (/home/ubuntu/git/BotBuilder/Node/lib/Session.js:288:18)
    at Session.compareConfidence (/home/ubuntu/git/BotBuilder/Node/lib/Session.js:176:18)
    at /home/ubuntu/git/BotBuilder/Node/lib/dialogs/IntentDialog.js:34:25
    at Request._callback (/home/ubuntu/git/BotBuilder/Node/lib/dialogs/LuisDialog.js:32:21)
    at Request.self.callback (/home/ubuntu/git/BotBuilder/Node/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/home/ubuntu/git/BotBuilder/Node/node_modules/request/request.js:1067:10)
```

It seems come from Session.js here:
https://github.com/Microsoft/BotBuilder/blob/45ad121e625c78ed514a543bf3edb62e1b4619b6/Node/lib/Session.js#L51

After do some dig, I found exception is come from IntentDialog.js
https://github.com/Microsoft/BotBuilder/blob/45ad121e625c78ed514a543bf3edb62e1b4619b6/Node/lib/dialogs/IntentDialog.js#L150

Which caused by `handler: this.getDefaultGroup()._intentHandler(topIntent.intent)` is not a function.
https://github.com/Microsoft/BotBuilder/blob/45ad121e625c78ed514a543bf3edb62e1b4619b6/Node/lib/dialogs/IntentDialog.js#L144
https://github.com/Microsoft/BotBuilder/blob/45ad121e625c78ed514a543bf3edb62e1b4619b6/Node/lib/dialogs/IntentDialog.js#L198

I'm very new to botbuilder, will try to dig deeper.

**Comment by zixia** [comment]
It seems dialog must have a `onDefault` setting to prevent this exception:

```javascript
dialog.onDefault(builder.DialogAction.send(prompts.helpMessage))
```

**Comment by Stevenic** [comment]
Thanks... I checked in fixes inspired by your changes.
