### ISSUE TITLE
Another exception inside Node examples/basics-multiTurn: [sprintf] mixing positional and named placeholders is not (yet) supported

### ISSUE THREAD

**Issue by zixia** [Microsoft/BotBuilder#388]
```shell
$ ~/git/BotBuilder/Node/examples/basics-multiTurn$ node app.js 
who founded ibm?
Sure... no problem.
```

Exception in detail:
```shell
 $ node app.js
who founded ibm?
I don't know '%(company)s'. Pick a company from the list or say 'nevermind'.
[ 'I don\'t know \'%(company)s\'. Pick a company from the list or say \'nevermind\'.%s',
  '\n   1. Microsoft\n   2. Apple\n   3. Google\n   4. Amazon' ]
{ resumed: 1,
  error: 
   Error: [sprintf] mixing positional and named placeholders is not (yet) supported
       at Function.sprintf.parse (/home/ubuntu/git/BotBuilder/Node/node_modules/sprintf-js/src/sprintf.js:159:27)
       at sprintf (/home/ubuntu/git/BotBuilder/Node/node_modules/sprintf-js/src/sprintf.js:19:34)
       at Object.vsprintf (/home/ubuntu/git/BotBuilder/Node/node_modules/sprintf-js/src/sprintf.js:174:24)
       at Session.vgettext (/home/ubuntu/git/BotBuilder/Node/lib/Session.js:227:50)
       at Session.gettext (/home/ubuntu/git/BotBuilder/Node/lib/Session.js:59:21)
       at Message.setText (/home/ubuntu/git/BotBuilder/Node/lib/Message.js:21:52)
       at Prompts.sendPrompt (/home/ubuntu/git/BotBuilder/Node/lib/dialogs/Prompts.js:228:25)
       at Prompts.begin (/home/ubuntu/git/BotBuilder/Node/lib/dialogs/Prompts.js:130:14)
       at Session.beginDialog (/home/ubuntu/git/BotBuilder/Node/lib/Session.js:108:16)
       at beginPrompt (/home/ubuntu/git/BotBuilder/Node/lib/dialogs/Prompts.js:302:13),
  childId: 'BotBuilder.Dialogs.Prompts' }
Sure... no problem.
```

**Comment by Stevenic** [comment]
Good catch... That would have been introduced with a recent change I made. Let me look into that.

**Comment by Stevenic** [comment]
checked in a fix. it was actually a simple type-o. I used the wrong prompt when the entity is missing.
