### ISSUE TITLE
PizzaBot - Quitting a form throws exception 

### ISSUE THREAD

**Issue by ankitbko** [Microsoft/BotBuilder#391]
I was facing issue in my bot where quitting the form throws `System.ArgumentNullException` exception. 
Checked it with PizzaBot Sample and the same issue is present. This seems to be happening after the latest release. Has the way to handle quit changed?

**Comment by ankitbko** [comment]
It does throw FormCancelledException. But it goes through and throws InvalidNextException because next is null in `var next = await leaf.PollAsync(this, context);` in L220 `Fiber.cs` and consequently ArgumentNullException from `SetField.cs` L55 `CheckNull<T>`
I completely forgot to put stack dump when reporting the issue. Sorry for that.
Message from Emulator:
```
{
  "message": "An error has occurred.",
  "exceptionMessage": "Value cannot be null.\r\nParameter name: wait",
  "exceptionType": "System.ArgumentNullException",
  "stackTrace": "   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.Microsoft.Bot.Builder.Internals.Fibers.IAwaiter<T>.GetResult() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Fibers\\Wait.cs:line 325\r\n   at Microsoft.Bot.Builder.Dialogs.Chain.LoopDialog`1.<ResumeAsync>d__3.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\Chain.cs:line 549\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.ThunkResume`1.<Rest>d__4.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\DialogTask.cs:line 118\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.<Microsoft-Bot-Builder-Internals-Fibers-IWait<C>-PollAsync>d__19.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Fibers\\Wait.cs:line 246\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Frame`1.<Microsoft-Bot-Builder-Internals-Fibers-IFrameLoop<C>-PollAsync>d__7.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Fibers\\Fiber.cs:line 114\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Bot.Builder.Internals.Fibers.Fiber`1.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop<C>-PollAsync>d__13.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Fibers\\Fiber.cs:line 233\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__20`1.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\DialogTask.cs:line 246\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.ReactiveDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5`1.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\DialogTask.cs:line 288\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.LocalizedDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__2`1.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\DialogTask.cs:line 343\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.ScoringDialogTask`1.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__6`1.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\Scorable.cs:line 143\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5`1.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\DialogTask.cs:line 367\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5`1.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\DialogTask.cs:line 372\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__4.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\Conversation.cs:line 111\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__2.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Library\\Dialogs\\Conversation.cs:line 82\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at Microsoft.Bot.Sample.PizzaBot.MessagesController.<Post>d__2.MoveNext() in D:\\Experiment\\BotBuilder-master\\BotBuilder\\CSharp\\Samples\\PizzaBot\\Controllers\\MessagesController.cs:line 52\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()\r\n   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
}
```

StackTrace from `this.fail` in `IAwaiter<T>.GetResult()` in `Wait.cs`
```
   at Microsoft.Bot.Builder.Internals.Fibers.SetField.CheckNull[T](String name, T value) in D:\Experiment\BotBuilder-master\BotBuilder\CSharp\Library\Fibers\SetField.cs:line 55
   at Microsoft.Bot.Builder.Internals.Fibers.SetField.NotNull[T](T& field, String name, T value) in D:\Experiment\BotBuilder-master\BotBuilder\CSharp\Library\Fibers\SetField.cs:line 47
   at Microsoft.Bot.Builder.Internals.Fibers.InvalidWaitException..ctor(String message, IWait wait) in D:\Experiment\BotBuilder-master\BotBuilder\CSharp\Library\Fibers\Exceptions.cs:line 49
   at Microsoft.Bot.Builder.Internals.Fibers.InvalidNextException..ctor(IWait wait) in D:\Experiment\BotBuilder-master\BotBuilder\CSharp\Library\Fibers\Exceptions.cs:line 112
   at Microsoft.Bot.Builder.Internals.Fibers.Fiber`1.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop<C>-PollAsync>d__13.MoveNext() in D:\Experiment\BotBuilder-master\BotBuilder\CSharp\Library\Fibers\Fiber.cs:line 225
```

Hope this helps.

**Comment by chrimc62** [comment]
Most likely this is because you do not handle an exception when chaining using a form with Chain.DefaultIfException.  The next step in the chain gets the FormCanceledException and rightly throws an exception because there is no value.  I do see we did not update the documentation, so I will add this.  Please reopen if this does not address your problem.

**Comment by ankitbko** [comment]
@chrimc62 I tried the following three line in Pizza Sample and none of it worked. What am I doing wrong? Also is it possible to update the Pizza sample to demonstrate the correct usage.
```CSharp
//return Chain.From(() => new PizzaOrderDialog(BuildForm)).DefaultIfException<PizzaOrder, FormCanceledException<PizzaOrder>>();
//return Chain.From(() => new PizzaOrderDialog(BuildForm)).DefaultIfException<PizzaOrder, FormCanceledException>();
return Chain.From(() => new PizzaOrderDialog(BuildForm)).DefaultIfException<PizzaOrder>();
```

**Comment by ankitbko** [comment]
@chrimc62 I am very sorry for this but it is now working. Exception is now getting swallowed. I dont know why it was not working last week.
