### ISSUE TITLE
Skype Web Control - not answering calls, throws javascript exceptions

### ISSUE THREAD

**Issue by quadfin** [Microsoft/BotBuilder#3916]
## Bot Info 
Not a Bot issue - but this is the only dev forum for Skype Web Control so here it is..

## Issue Description
Cross posting from 
[Microsoft Community - Skype for Web](https://answers.microsoft.com/en-us/skype/forum/skype_web-skype_callms-skype_audioms/skype-web-control-not-answering-calls-throws/ce78f0d8-6b5d-47db-929c-5ad27c1b04f1)

The Skype Web Control, when used with a data-contact-id (not a bot id) will not (initially) answer skype calls to the identified skype account.  It throws javascript errors as indicated below.

## Code Example
Add the skype web control to a page:

```
<div class="skype-button bubble" data-contact-id="skype-id"></div>
<script src="https://swc.cdn.skype.com/sdk/v1/sdk.min.js"></script>
```

## Reproduction Steps
1. Launch the page, click on the button, and login to skype via the web control UX using the skype-id account.
2. Using skype desktop with a different account call the skype-id account.
3. Open the browser debugger to see the incoming call activity of the web control 
4. The web control incoming call dialog does not display so the call cannot be answered.
5. Note Javascript errors as below.

PluginlessCall[8e945738-8e51-4a70-b1f8-f6e0cabf4121] failed acknowledge call, callId = 8e945738-8e51-4a70-b1f8-f6e0cabf4121 TypeError: Cannot read property 'classList' of null
    at e._showCallingScreen (chat-bundle.min.js:13)
    at e._onRegistryUpdate [as registryUpdateCallback] (chat-bundle.min.js:13)
    at calling-bundle.min.js:8
    at Array.forEach (<anonymous>)
    at e._updateIncomingCalls (calling-bundle.min.js:8)
    at e._onCallStateChanged (calling-bundle.min.js:8)
    at Object.handler (calling-bundle.min.js:8)
    at calling-bundle.min.js:8
    at calling-bundle.min.js:8
    at Array.forEach (<anonymous>)

chat-bundle.min.js:13 Uncaught (in promise) TypeError: Cannot read property 'classList' of null
    at e._showCallingScreen (chat-bundle.min.js:13)
    at e._onRegistryUpdate [as registryUpdateCallback] (chat-bundle.min.js:13)
    at calling-bundle.min.js:8
    at Array.forEach (<anonymous>)
    at e._updateIncomingCalls (calling-bundle.min.js:8)
    at e._onCallStateChanged (calling-bundle.min.js:8)
    at Object.handler (calling-bundle.min.js:8)
    at calling-bundle.min.js:8
    at calling-bundle.min.js:8
    at Array.forEach (<anonymous>)

SignalingAgent::[8e945738-8e51-4a70-b1f8-f6e0cabf4121][ac452066-3570-48b0-a513-e20285852717][Idle] handleIncomingMsg failed with error : Cannot read property 'classList' of nullstack trace : TypeError: Cannot read property 'classList' of null
    at e._closeCalling (https://swc.cdn.skype.com/v/0.41.29/calling-bundle.min.js:8:53618)
    at e._onCallStateChanged (https://swc.cdn.skype.com/v/0.41.29/calling-bundle.min.js:8:64606)
    at Object.handler (https://swc.cdn.skype.com/v/0.41.29/calling-bundle.min.js:8:61972)
    at https://swc.cdn.skype.com/v/0.41.29/calling-bundle.min.js:8:214464
    at https://swc.cdn.skype.com/v/0.41.29/calling-bundle.min.js:8:393139
    at Array.forEach (<anonymous>)
    at n.e.raiseEvents (https://swc.cdn.skype.com/v/0.41.29/calling-bundle.min.js:8:393096)
    at n.t._raiseEventImpl (https://swc.cdn.skype.com/v/0.41.29/calling-bundle.min.js:8:214395)
    at Object.raise (https://swc.cdn.skype.com/v/0.41.29/calling-bundle.min.js:8:214263)
    at n.setCallState (https://swc.cdn.skype.com/v/0.41.29/calling-bundle.min.js:8:315375)

## Expected Behavior
Expectation is for the skype web control to answer the incoming call.

## Actual Results
The call is not answered.

## Additional information

Update 12/12/2018
using the script from 
https://latest-swc.cdn.skype.com/sdk/v1/sdk.min.js
The functionality seems to have been improved - but is not error free as described below.

If, after logging into Skype via the web control interface, a call is placed to the 'skype-id' account then the control will not answer -- it continues to throw the javascript exceptions as identified previously.
However, if one clicks on the video or call icon in the control's toolbar then the control initiates the calling dialog.  Subsequently the control will answer an incoming call without throwing exceptions.

This behavior has changed from a few days ago - so apparently someone is working on the issue.

**Comment by nwhitmont** [comment]
Hi @quadfin - This isn't a forum for Skype Web Control questions not related to Bot Framework. 

Please contact Skype support for further assistance.

**Comment by quadfin** [comment]
Well, there is no support forum for Skype Web Control nor does the “Skype” team respond to issues relating to Skype Web Control – so where does one post related issues? 

Since Skype Bots are dependent (indirectly) upon the Skype Web Control this seems to be the closest match.

I have received other rejections of this “it’s not our problem” nature – who supports this product?
