### ISSUE TITLE
Bot Framework emulator download error

### ISSUE THREAD

**Issue by kenrick95** [Microsoft/BotBuilder#4]
I came across the [Bot Framework emulator download link](http://aka.ms/bf-bc-emulator) from the [Bot Builder for Node.js Getting Started page](http://docs.botframework.com/builder/node/overview/)

I downloaded the `setup.exe`. After running it, an error message "Cannot Start Application: Application download did not succeed" was shown, with the following error details:

```
PLATFORM VERSION INFO
	Windows 			: 10.0.10586.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.6.1038.0 built by: NETFXREL2
	clr.dll 			: 4.6.1073.0 built by: NETFXREL3STAGE
	dfdll.dll 			: 4.6.1038.0 built by: NETFXREL2
	dfshim.dll 			: 10.0.10586.0 (th2_release.151029-1700)

SOURCES
	Deployment url			: http://download.botframework.com/botconnector/tools/emulator/Bot%20Framework%20Emulator.application
						Server		: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
	Deployment Provider url		: file://fuseserver02/public/Intercom/Bot%20Framework%20Emulator/Bot%20Framework%20Emulator.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of http://download.botframework.com/botconnector/tools/emulator/Bot%20Framework%20Emulator.application resulted in exception. Following failure messages were detected:
		+ Downloading file://fuseserver02/public/Intercom/Bot Framework Emulator/Bot Framework Emulator.application did not succeed.
		+ The network path was not found.

		+ The network path was not found.

		+ The network path was not found.


COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	There were no warnings during this operation.

OPERATION PROGRESS STATUS
	* [31/3/2016 02:00:07] : Activation of http://download.botframework.com/botconnector/tools/emulator/Bot%20Framework%20Emulator.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [31/3/2016 02:00:10] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file://fuseserver02/public/Intercom/Bot Framework Emulator/Bot Framework Emulator.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The network path was not found.

		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- The network path was not found.

		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.IOException
		- The network path was not found.

		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.


```

**Comment by jameslew** [comment]
Thank you!  We're currently investigating and will have an update shortly.

**Comment by jameslew** [comment]
This should be fixed now; just try downloading again.

Thanks for the report!

**Comment by Andrea-Orimoto** [comment]
Closing this issue. Please let us know if you still have problems.
Thanks a lot for reporting it!
