### ISSUE TITLE
[Direct Line] Getting "502 Bad Gateway" error on POST

### ISSUE THREAD

**Issue by GhassenRjab** [Microsoft/BotBuilder#4081]
## Bot Info
* SDK Platform: Node.js
* SDK Version: 3.13.1
* Active Channels: Direct Line
* Deployment Environment: Azure Bot Service

## Issue Description
The ChatBot do not respond to messages received via DirectLine

## Code Example
There is no bot code responsible for the issue, the issue can happen in any dialog and in any message

## Reproduction Steps
1. Send messages to the ChatBot via DirectLine

## Expected Behavior
The ChatBot responds to DirectLine without any errors

## Actual Results
An error message is outputted in the log
```
Error: POST to 'https://directline.botframework.com/v3/conversations/3fpyylYnDK2HHm3z0h1yjo/activities/3fpyylYnDK2HHm3z0h1yjo%7C0000058' failed: [502] Bad Gateway
    at Request._callback (/var/www/quicktext-bot/node_modules/botbuilder/lib/bots/ChatConnector.js:545:46)
    at Request.self.callback (/var/www/quicktext-bot/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/var/www/quicktext-bot/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/var/www/quicktext-bot/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
```

**Comment by GhassenRjab** [comment]
I am closing the issue because it has been resolved through Microsoft Customer Services

**Comment by shorya12121212** [comment]
@GhassenRjab How do you resolved your error?

**Comment by GhassenRjab** [comment]
@shorya12121212 At the time it was a global issue that caused Azure's Active Directory to stop working.
They got it resolved that day
