### ISSUE TITLE
[Node.js SDK, MSTeams] - Node.js Bot works with Bot Framework Emulator but not with MS Teams (Bad Request)

### ISSUE THREAD

**Issue by giuleon** [Microsoft/BotBuilder#4086]
## Bot Info
* SDK Platform: Node.js
* Active Channels: Skype, MS Teams, Direct Line
* Deployment Environment: Azure Bot Service, Azure App Service, local development with Emulator

## Issue Description
Hi @RichMoeMSFT, I'm facing an issue with my Node.js Bot, everything works with Bot Framework Emulator but not with MS Teams:

"dependencies": {
"adal-node": "^0.1.27",
"axios": "^0.17.1",
"botbuilder": "^3.13.1",
"botbuilder-azure": "^3.0.4",
"es6-promise": "^4.2.2",
"lodash": "^4.17.4",
"restify": "^5.2.1"
},

## Reproduction Steps
1.Create a new Node.js Bot and host it on Azure

## Expected Behavior
The Bot must interact also with MS Teams when the channel is enabled

## Actual Results
Error: POST to 'https://smba.trafficmanager.net/emea-client-ss.msg/v3/conversations/a%3A1Xnq4KhIrUJkVEd3yT67GYcPPJklI3BrH-gR4X3lemfZqxMBkqrRY4DmH2Eu0f1NQKgBZEIT-H2Xp7gpf4sZYvqxTgRSN3goFgqQyFCPq5K8ekxVDlr61bT0jM6Zynyny/activities/1516745027476' failed: [400] Bad Request
at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:545:46)
at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:188:22)
at emitTwo (events.js:106:13)
at Request.emit (events.js:191:7)
at Request. (D:\home\site\wwwroot\node_modules\request\request.js:1171:10)
at emitOne (events.js:96:13)
at Request.emit (events.js:188:7)
at IncomingMessage. (D:\home\site\wwwroot\node_modules\request\request.js:1091:12)
at IncomingMessage.g (events.js:291:16)
at emitNone (events.js:91:20)

**Comment by giuleon** [comment]
I recreated the Bot and now it's working also on Teams

**Comment by giuleon** [comment]
After a couple of hours of interaction I have the same issue

**Comment by fanidamj** [comment]
Can you please let us know if the issue still persists?

**Comment by giuleon** [comment]
The issue is solved
