### ISSUE TITLE
[QnAMaker, LUIS] QnA Breaking App: ERROR: steps[0] is not a function

### ISSUE THREAD

**Issue by limsammy** [Microsoft/BotBuilder#4220]
## Bot Info
* SDK Platform: Node
* SDK Version: 3.14.0
* Active Channels: N/A
* Deployment Environment: Emulator

## Issue Description
Whether it's LUIS recognizers or a regex trigger, the bot errors out with the error `/ - ERROR: steps[0] is not a function`. It fixes itself when I remove my QnA SmallTalk module.

## Code Example
Here is where I match the intent:

```javascript
dialog.matches("SmallTalk", [qnaClient]);
```

And here is the `qnaClient()` method:

```javascript
function qnaClient(session, results, next) {
    qnaClient.post({ question: session.message.text }, function (err, res) {
        if (err) {
            console.error('Error from callback:', err);
            session.send('Oops - something went wrong.');
            return;
        }

        if (res) {
            // Send reply from QnA back to user
            session.send(res);
        } else {
            // Confidence in top result is not high enough - discard result
            session.send('Hmm, I didn\'t quite understand you there. Care to rephrase?')
        }
    });
}
```

## Reproduction Steps
1. Set up a dialog recognizer for a QnA service and SmallTalk intent (Using this method: [click here](https://github.com/alyssaong1/botframework-smalltalk)
2. Run REST server 
3. Try to execute any command, whether it be NLP or a hardcoded regex string

## Actual Results
Here are my console logs:

When running 'Hello' which maps to my SmallTalk intent:

```bash
UniversalBot("*") routing "Hello" from "emulator"
Session.beginDialog(/)
/ - IntentDialog.matches(SmallTalk)
/ - waterfall() step 1 of 1
TypeError: steps[0] is not a function
    at Object.waterfallHandler [as SmallTalk] (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:139:29)
    at IntentDialog.invokeIntent (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentDialog.js:163:44)
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentDialog.js:71:27
    at next (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:68:17)
    at IntentRecognizerSet.IntentRecognizer.filter (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:71:9)
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:20:31
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:80:17
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/node_modules/async/lib/async.js:52:16
    at replenish (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/node_modules/async/lib/async.js:306:28)
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/node_modules/async/lib/async.js:326:29
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/node_modules/async/lib/async.js:44:16
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:72:21
    at next (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:68:17)
    at LuisRecognizer.IntentRecognizer.filter (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:71:9)
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:20:31
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/LuisRecognizer.js:63:25
    at Request._callback (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/LuisRecognizer.js:109:25)
    at Request.self.callback (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

/ - ERROR: steps[0] is not a function
/ - Session.endConversation()
Session.sendBatch() sending 2 message(s)
```

And just for good measure here is a debug command I have hardcoded:

```bash
ChatConnector: message received.
UniversalBot("*") routing "luis_test" from "emulator"
Session.beginDialog(/)
/ - IntentDialog.matches(/^luis_test$/i)
/ - waterfall() step 1 of 1
TypeError: steps[0] is not a function
    at Object.waterfallHandler [as /^luis_test$/i] (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/WaterfallDialog.js:139:29)
    at IntentDialog.invokeIntent (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentDialog.js:163:44)
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentDialog.js:71:27
    at next (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:68:17)
    at IntentRecognizerSet.IntentRecognizer.filter (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:71:9)
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:20:31
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:80:17
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/node_modules/async/lib/async.js:52:16
    at replenish (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/node_modules/async/lib/async.js:306:28)
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/node_modules/async/lib/async.js:326:29
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/node_modules/async/lib/async.js:44:16
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizerSet.js:72:21
    at next (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:68:17)
    at LuisRecognizer.IntentRecognizer.filter (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:71:9)
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/IntentRecognizer.js:20:31
    at /Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/LuisRecognizer.js:63:25
    at Request._callback (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/botbuilder/lib/dialogs/LuisRecognizer.js:109:25)
    at Request.self.callback (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/request/request.js:186:22)
    at Request.emit (events.js:159:13)
    at Request.<anonymous> (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:159:13)
    at IncomingMessage.<anonymous> (/Users/sam/lifeai/therealdeal/bots/location-assistant-bot/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:254:19)
    at IncomingMessage.emit (events.js:164:20)
    at endReadableNT (_stream_readable.js:1054:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)

/ - ERROR: steps[0] is not a function
/ - Session.endConversation()
Session.sendBatch() sending 2 message(s)
```

**Comment by stevengum97** [comment]
Can you provide the code you're using to instantiate your IntentDialog and the recognizers you're plugging into it?

**Comment by stevengum97** [comment]
Closing due to inactivity.
