### ISSUE TITLE
BotBuilder in node.js doesn't resolve session.message.user.name

### ISSUE THREAD

**Issue by CheapHead** [Microsoft/BotBuilder#4245]
## Bot Info
* SDK Platform: Node.js 
* SDK Version: 3.14.0
* Active Channels: WebChat(DirectLine)
* Deployment Environment: Azure Bot Service

## Issue Description
I'm trying to make a bot using node.js and embedded in SharePoint using below script.

<script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script> <script>
  BotChat.App({
    directLine: { secret: ****** },
    user: { id: 'user12345', name : 'user1' },
    bot: { id: 'na' },
    resize: 'detect'
  }, document.getElementById("bot"));
  document.oncontextmenu = function(){return false;};
</script>

Once the user opens bot window, the bot send welcome message using conversationUpdate, however
session.message.user.name is 'undefined'
In case of check this on Emulator, session.message.user.name works fine!
Please let me know how to pass the user.name to the opening message from the bot.

## Code Example
bot.on('conversationUpdate',(session,activity,message) => {
    console.log('session.message.user.name = ' + session.message.user.name);
    if(session.membersAdded){
        session.membersAdded.forEach(function (identity) {
            if(identity.id === session.address.bot.id){
                bot.beginDialog(session.address,'Welcome');
                //session.send(session.user.name)
                //session.send('this is welcome message')
            }
        });
    }
})

## Reproduction Steps
1. Opens the chat window
2. Welcome message shows Welcome 'undefined' user 

## Expected Behavior
Expect the user: { id: 'user12345', name : 'user1' } passed correctly.

## Actual Results
session.message.user.name is not 'undefined' or error with below stack trace.
-----------------------------------------------------------------------------------
TypeError: Cannot read property 'user' of undefined
    at UniversalBot.bot.on (D:\home\site\wwwroot\app.js:72:65)
    at emitOne (events.js:96:13)
    at UniversalBot.emit (events.js:188:7)
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:156:31
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:427:53
    at UniversalBot.tryCatch (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:516:13)
    at next (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:427:23)
    at UniversalBot.eventMiddleware (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:430:9)
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:141:23
    at D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\UniversalBot.js:472:53

**Comment by EricDahlvang** [comment]
Hi @CheapHead 

This is a known issue:
https://github.com/Microsoft/BotFramework-WebChat/issues/364
https://github.com/Microsoft/BotFramework-WebChat/issues/848
https://github.com/Microsoft/BotFramework-WebChat/issues/536

A workaround is to create a BotChat.DirectLine object for BotChat.App, and post an event activity in client side code.  Then in the bot code, respond to the event with the desired welcome message.

web page:
```

<!DOCTYPE html>

<html>
<head>
    <link href="https://cdn.botframework.com/botframework-webchat/latest/botchat.css" rel="stylesheet" />
</head>
<body>
    <div>
        <div id="bot" />
    </div>

    <script src="https://cdn.botframework.com/botframework-webchat/latest/botchat.js"></script>
    <script>

        var user = {
            id: 'user-id',
            name: 'user name'
        };

        var botConnection = new BotChat.DirectLine({
            token: '[DirectLineSecretHere]',
            user: user
        });

        BotChat.App({
            user: user,
            botConnection: botConnection,
            bot: { id: 'bot-id', name: 'bot name' },
            resize: 'detect'
        }, document.getElementById("bot"));

        botConnection
            .postActivity({
                from: user,
                name: 'requestWelcomeDialog',
                type: 'event',
                value: ''
            })
            .subscribe(function (id) {
                console.log('"trigger requestWelcomeDialog" sent');
            });
    </script>
</body>
</html>

```
 

bot code:
```js

const connector = new builder.ChatConnector({
	appId: 'MicrosoftAppIdHere',
	appPassword: 'MicrosoftAppPasswordHere'
});
const server = restify.createServer();
server.listen(process.env.port || process.env.PORT || 3979, () => {
	console.log(`${server.name} listening to ${server.url}`);
});
server.post('/api/messages', connector.listen());
var bot = new builder.UniversalBot(connector); 

bot.on('event', function(message) { 
	if(message.name == 'requestWelcomeDialog'){
		bot.beginDialog(message.address, '/');
	}
});
```
```
bot.dialog('/', [function(session, args, next) {
try {
	builder.Prompts.choice(session, 'Hey, I'm a bot.  Ask me about:', 'Item 1|Item 2|Other', 
{listStyle: builder.ListStyle["button"]});
} catch (err) {}
},
function(session, results) {
	switch (results.response.entity) {
	case "Item 1":
		session.replaceDialog("/Item1Dialog");
		break;
	case "Item 2":
		session.replaceDialog("/Item2Dialog");
		break;
	case "Other":
		session.replaceDialog("/Other");
		break;
	default:
		session.replaceDialog("/");
	break;
	}
}
]);

 

bot.dialog('/Item1Dialog', [function(session, args, next) {
	try {
		session.send('in item 1 dialog');
	} catch (err) {}
}]);

```

**Comment by CheapHead** [comment]
I fixed this issue and apologize I lack of search for past issues.
Many thanks for your help.

**Comment by Chitma** [comment]
Hi @EricDahlvang , how can i make it work on WebChat? It worked flawlessly on DirectLine.
