### ISSUE TITLE
Unexpected token on running this code

### ISSUE THREAD

**Issue by SiarheiAbr** [Microsoft/BotBuilder#436]
I get the following error on running this code:
\node_modules\skype-sdk\index.js:28
    BotService,
              ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (d:\MyDocuments\General\JavaScript\nodejs\bishop\server.js:49:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)

**Comment by Stevenic** [comment]
This looks like an issue in the Skype SDK itself.

**Comment by v-thgratMSGit** [comment]
Closing this issue due to age. Thanks! @SiarheiAbr - if you are continuing to experience this, please open a new issue.
