### ISSUE TITLE
Skype API Unauthorized issue after 1-2 days of inactivity

### ISSUE THREAD

**Issue by pryabov** [Microsoft/BotBuilder#4396]
## Bot Info
* SDK Platform: .NET
* SDK Version: 4.0.0-alpha201802123
* Active Channels: 
* Deployment Environment: issue reproduced on Azure Bot Channels Registration and App Service
## Issue Description
018-03-29 15:54:30.224 +00:00 [Error] SchedulerBot.Business.Services.ScheduledMessageProcessorService: Sending message was failed due Exception Message: 'Operation returned an invalid status code 'Unauthorized'', StackTrace: '   at Microsoft.Bot.Connector.Conversations.<SendToConversationWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<SendToConversationAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SchedulerBot.Infrastructure.BotConnector.MessageProcessor.<SendMessageAsync>d__3.MoveNext() in C:\Users\a.krauchuk\source\repos\scheduler-bot\SchedulerBot\SchedulerBot.Infrastructure.BotConnector\MessageProcessor.cs:line 49
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SchedulerBot.Business.Services.ScheduledMessageProcessorService.<ProcessScheduledMessagesAsync>d__11.MoveNext() in C:\Users\a.krauchuk\source\repos\scheduler-bot\SchedulerBot\SchedulerBot.Business.Services\ScheduledMessageProcessorService.cs:line 138', 
```json
Request: {
  "Method": {
    "Method": "POST"
  },
  "RequestUri": "https://smba.trafficmanager.net/apis/v3/conversations/19%3A94444c1ae660408d9f93ccd336a712ef%40thread.skype/activities",
  "Properties": {},
  "Content": "{\r\n  \"type\": \"message\",\r\n  \"serviceUrl\": \"https://smba.trafficmanager.net/apis/\",\r\n  \"channelId\": \"skype\",\r\n  \"from\": {\r\n    \"id\": \"28:------------------hided-------------------\",\r\n    \"name\": \"------------------hided-------------------\"\r\n  },\r\n  \"conversation\": {\r\n    \"id\": \"------------------hided-------------------@thread.skype\"\r\n  },\r\n  \"recipient\": {\r\n    \"id\": \"------------------hided-------------------",\r\n    \"name\": \"Pavel\"\r\n  },\r\n  \"text\": \"------------------hided-------------------\",\r\n  \"attachments\": [],\r\n  \"entities\": []\r\n}",
  "Headers": {
    "User-Agent": [
      "FxVersion/4.6.26212.01",
      "Microsoft.Bot.Connector.ConnectorClient/4.0.0.6",
      "Microsoft-BotFramework/4.0",
      "(BotBuilder .Net/4.0.0.6)"
    ],
    "x-ms-request-root-id": [
      "------------------hided-------------------"
    ],
    "x-ms-request-id": [
      "------------------hided-------------------"
    ],
    "Request-Id": [
      "------------------hided-------------------"
    ],
    "Content-Type": [
      "application/json; charset=utf-8"
    ],
    "Content-Length": [
      "519"
    ]
  }
}, 
Response: {
  "StatusCode": 401,
  "ReasonPhrase": "Unauthorized",
  "Content": "{\"message\":\"Authorization has been denied for this request.\"}",
  "Headers": {
    "Connection": [
      "close"
    ],
    "Date": [
      "Thu, 29 Mar 2018 15:54:29 GMT"
    ],
    "Server": [
      "Microsoft-HTTPAPI/2.0"
    ],
    "Content-Length": [
      "61"
    ],
    "Content-Type": [
      "application/json; charset=utf-8"
    ]
  }
}
```

## Description
We have a recurring task which should send messages to chat by schedule. Everything is working well during the first 1-2 days but after that period of time we recive the issue above. The main condition to reproduce this [do not call method](https://github.com/Scheduler-Bot/scheduler-bot/blob/b2b0a06ae274ba5c3e6427697ecdef732858d20d/SchedulerBot/SchedulerBot/Controllers/MessagesController.cs#L62). It means as ssoon as we are doing any (it can be not valid) request to bot in any channel (e.g. `@bot-name say hi`). Everything start working. And fail after 1-2 days of inactivity for executing mentioned method.

## Code Example
https://github.com/Scheduler-Bot/scheduler-bot/blob/b2b0a06ae274ba5c3e6427697ecdef732858d20d/SchedulerBot/SchedulerBot.Infrastructure.BotConnector/MessageProcessor.cs#L37

```c#
		public async Task SendMessageAsync(ScheduledMessage scheduledMessage, CancellationToken cancellationToken)
		{
			if (!cancellationToken.IsCancellationRequested)
			{
				MicrosoftAppCredentials credentials = BuildMicrosoftAppCredentials();

				Uri serviceUri = new Uri(scheduledMessage.Details.ServiceUrl);
				Activity activity = CreateBotMessageActivity(scheduledMessage);

				using (ConnectorClient connector = new ConnectorClient(serviceUri, credentials))
				{
					logger.LogInformation($"Sending message to conversation RecipientId: ${activity.Recipient.Id}.");
					await connector.Conversations.SendToConversationAsync(activity, cancellationToken);
				}
			}
			else
			{
				logger.LogInformation("CancellationToken is in CancellationRequested state.");
			}
		}
```

**Comment by pryabov** [comment]
Finally after reviewing source code of BotFramework we determined that the issue was related with
`MicrosoftAppCredentials._trustedHostNames` dictionary.

By default when authentication for BotController is working are called method 
```c#
public static void TrustServiceUrl(string serviceUrl)
{
  MicrosoftAppCredentials.TrustServiceUrl(serviceUrl, DateTime.UtcNow.Add(TimeSpan.FromDays(1.0)));
}
```
And as you can see there used default `TimeSpan` for valid period of `serviceUrl`. If there is no requests to `MessageController` after one day serviceUrl becomes untrusted and to header do not added Bearer token.

Was fixed in commit: https://github.com/Scheduler-Bot/scheduler-bot/commit/ae2c31271387c5dd22eee2df02ab125f682456e7

by adding:
```c#
if (!MicrosoftAppCredentials.IsTrustedServiceUrl(serviceUrl))
{
    MicrosoftAppCredentials.TrustServiceUrl(serviceUrl);
}
```
