### ISSUE TITLE
Unauthorized Error on IPostToBot.PostAsync

### ISSUE THREAD

**Issue by muebele** [Microsoft/BotBuilder#4447]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Active Channels: Slack
* Deployment Environment:  Azure

## Issue Description
We've had a bot in production for several months that now just suddenly stopped working. It works normally on the Bot Framework Emulator, but on Azure, it returns a 500 Internal Server Error (see stack trace below)

## Code Example
The bot authenticates fine, but it crashes as soon as it attempts to go into a Dialog. 

```
if (activity.Type == ActivityTypes.Message)
{
           await Conversation.SendAsync(activity, () => new RootDialog());
 }
```

That ends up crashing on the IPostToBot.PostAsync call:

```
public class PostUnhandledExceptionToUser : IPostToBot
    {
        private readonly ResourceManager resources;
        private readonly IPostToBot postToBot;
        private readonly IBotToUser botToUser;
        private readonly TraceListener trace;

        public PostUnhandledExceptionToUser(IPostToBot inner, IBotToUser botToUser, ResourceManager resources, TraceListener trace)
        {
            SetField.NotNull(out this.postToBot, nameof(inner), inner);
            SetField.NotNull(out this.botToUser, nameof(botToUser), botToUser);
            SetField.NotNull(out this.resources, nameof(resources), resources);
            SetField.NotNull(out this.trace, nameof(trace), trace);
        }

        async Task IPostToBot.PostAsync(IActivity activity, CancellationToken token)
        {
            try
            {
                await this.postToBot.PostAsync(activity, token); // <---- Crashes here
            }
            catch (Exception ex) {......}}
```

Here's the Stack Trace for the error thrown:

```
Unauthorized at Microsoft.Bot.Connector.MicrosoftAppCredentials.<RefreshTokenAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Connector.MicrosoftAppCredentials.<GetTokenAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Connector.MicrosoftAppCredentials.<ProcessHttpRequestAsync>d__26.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
at Microsoft.Bot.Connector.BotState.<GetConversationDataWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Connector.BotStateExtensions.<GetConversationDataAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.ConnectorStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-LoadAsync>d__2.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotData.cs:line 203
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<LoadFromInnerAndCache>d__11.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotData.cs:line 372
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.CachingBotDataStore.<Microsoft-Bot-Builder-Dialogs-Internals-IBotDataStore<Microsoft-Bot-Connector-BotData>-LoadAsync>d__9.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotData.cs:line 350
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase`1.<LoadData>d__16.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotData.cs:line 553
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.BotDataBase`1.<LoadAsync>d__8.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotData.cs:line 514
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.DialogTaskManagerBotDataLoader.<LoadAsync>d__11.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotData.cs:line 473
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__3.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\Dialogs\DialogTask.cs:line 478
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.ExceptionTranslationDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__2.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\Dialogs\DialogTask.cs:line 403
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Bot.Builder.Dialogs.Internals.SerializeByConversation.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__4.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\PostToBot.cs:line 129
--- End of stack trace from previous location where exception was thrown ---

at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
at Az.Eller.eSMS.WebApi.Extensions.PostUnhandledExceptionToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5.MoveNext() in C:\Users\muebele\Documents\SecretSauce\eSMS\Az.Eller.eSMS.WebApi\Extensions\BotDialogs.cs:line 507
```

The Exception message just says "Unauthorized" so we're not sure what's going wrong since that happens after the bot has successfully authenticated and just last week there was no problem at all. 

Any insight into this issue would be appreciated, thanks!

**Comment by EricDahlvang** [comment]
Is the time on your server set correctly?

What is your BotHandle and MicrosoftAppId?

**Comment by muebele** [comment]
Handle: esmsbot_dev_01
App Id: ba0eae0f-f0e5-4a5e-9ec6-143d1447b463

For the server, we're using an Azure web app, which I believe the time automatically configures to UTC?

**Comment by EricDahlvang** [comment]
Does restarting the app service fix the issue?

**Comment by muebele** [comment]
We've tried restarting the service - no change in behavior unfortunately.

**Comment by EricDahlvang** [comment]
Is this bot using the default state service?  This service is being deprecated: https://blog.botframework.com/2018/04/02/reminder-the-bot-framework-state-service-has-been-retired-what-you-need-to-know/

Here is a blog that describes how to use Bot Builder Azure Extensions to implement a custom state:
https://blog.botframework.com/2017/07/18/Saving-State-Azure-Extensions/

---
This should not be causing the Unauthorized exception you are seeing, but if you ARE using the default state service and that is where the exception is occurring, then implementing a custom state client will "fix" the issue.

**Comment by muebele** [comment]
What exactly is the default state service and how can I tell if I'm using it? We store all of our bot's data internally, but we do use serialized class variables to manage conversation flow; I didn't think that was part of the state service, but correct me if I'm wrong!

**Comment by EricDahlvang** [comment]
i'm confused about why the bot would suddenly stop working, and why it would be throwing unauthorized exceptions.  Are you using v3.14.1.1 of Microsoft.Bot.Builder AND  v3.14.1.1 of Microsoft.Bot.Connector ?

Dialog fields are persisted in the state store, as well as UserData, ConversationData and PrivateConversationData.  If you have not implemented a custom state client, then you are using the default state service.  More information can be found here: https://docs.microsoft.com/en-us/azure/bot-service/dotnet/bot-builder-dotnet-state

**Comment by muebele** [comment]
Yes, we're on v3.14.1.1 on both. 

I'm still not entirely sure what exactly is going wrong, but I've identified the source of the problem at least:

We're using our own customized mechanism for authentication - rather than storing the app id and password in the web.config file, we pull them dynamically from a secure storage and match them against the request (we have multiple bots running on the same code base, so we have to be able to authentication for multiple bots) . 

I don't know why, but if I replace this with the web.config method of authentication, then the bot functions properly as before. (our logs show that our calls are pulling the correct values for the App Id and Password)

The code we're using can be seen below:

```
[BotAuthentication(CredentialProviderType = typeof(CustomCredentialProvider))]
    public class BotFrameworkController : ApiController
    {
        BotService BotService = new BotService();
        private static bool configured = false;

        /// <summary>
        /// POST: api/BotFramework
        /// Receive a message from a user and reply to it
        /// </summary>
        public async Task<HttpResponseMessage> Post([FromBody]Activity activity)
        {
            if (!configured)
            {
                var builder = new ContainerBuilder();

                // Get authentication values
                string MicrosoftAppId = await BotService.GetMicrosoftAppIdAsync();
                string MicrosoftAppPassword = await BotService.GetMicrosoftAppPasswordAsync();
                builder.Register(c => new MicrosoftAppCredentials(MicrosoftAppId, MicrosoftAppPassword)).SingleInstance();

                // Override default exception handling with our own class
                builder.RegisterModule(new DefaultExceptionMessageOverrideModule());

                builder.Update(Conversation.Container);

                configured = true;
            }

        if (activity.Type == ActivityTypes.Message)
        ....
     }
```

And the CustomCredentialProvider class:

```
/// <summary>
    /// Custom class for authenticating requests to our bot
    /// </summary>
    public class CustomCredentialProvider : ICredentialProvider
    {

        /// <summary>
        /// Verifies app id
        /// </summary>
        public async Task<bool> IsValidAppIdAsync(string appId)
        {
            BotService botService = new BotService();
            string MicrosoftAppId = await botService.GetMicrosoftAppIdAsync(); // Pulls our app id from secure location

            return await Task.FromResult(appId == MicrosoftAppId);
        }

        /// <summary>
        /// Verifies password
        /// </summary>
        public async Task<string> GetAppPasswordAsync(string appId)
        {
            BotService botService = new BotService();
            string MicrosoftAppPassword = await botService.GetMicrosoftAppPasswordAsync(); // Pulls our app password from secure location

            return await Task.FromResult(MicrosoftAppPassword);
        }
}
```

**Comment by muebele** [comment]
Replaced my configuration code with what you have in Global.Asax.cs and it's working again! Thanks so much for the help!
