### ISSUE TITLE
RichCard with thumbnails can not retrieve image on hosted version IIS

### ISSUE THREAD

**Issue by Daddymarto01** [Microsoft/BotBuilder#4649]
## Bot Info
* SDK Platform:  .NET  
* Active Channels: Messenger, Skype
* Deployment Environment:  local development with Emulator

## Issue Description
I have a locally working code with rich cards well implemented. After publishing, the bot from my channel can not read referenced image from local folder. The bot fails with message "Failed with message: Operation returned an invalid status code 'BadRequest'"

## Code Example
```cs
                 GetRideType(

                     "Basic",
                     "MIN FARE: 200/=, MAX PASS: 4",
                     "Click on the button to request basic ride type.",
                          new CardImage(System.Web.HttpContext.Current.Server.MapPath("~/App_Data/images/_footer-logo.png")),
                         new CardAction(ActionTypes.ImBack, "Basic", value: "Basic"),
                         new CardAction(ActionTypes.ImBack, "Basic", value: "Basic")
                     ),


private static Attachment GetRideType(string title, string subttitle, string text, CardImage cardImage, CardAction cardAction, CardAction action2)
        {
            try
            {
                var card = new ThumbnailCard
                {
                    Title = title,
                    Subtitle = subttitle,
                    Text = text,
                    Images = new List<CardImage>() { cardImage },
                    Buttons = new List<CardAction>() {

                        new CardAction ()
                            {
                                Value = title,
                                Type = "postBack",
                                Title = "Request Ride"
                            }, 
                            new CardAction ()
                            {
                                Value = "Help",
                                Type = "postBack",
                                Title = "Help"
                            },


                    },
                    Tap = action2
                };
                return card.ToAttachment();
            }
            catch (Exception ex)
            {
                #region   saveException
                var filePath = System.Web.HttpContext.Current.Server.MapPath("~/App_Data/ErrorLogs.txt");

                using (StreamWriter writer = new StreamWriter(filePath, true))
                {
                    writer.WriteLine("Created By :" + "SYSTEM" + Environment.NewLine + "Date Created :" + DateTime.Now.ToString() + Environment.NewLine + "Message :" + ex.Message + Environment.NewLine + "StackTrace :" + ex.StackTrace);
                    writer.WriteLine(Environment.NewLine + "-----------------------------------------------------------------------------" + Environment.NewLine);
                }
                #endregion
                return null;
            } 
        }
```        

## Reproduction Steps
I am calling the my card as shown above. I have everything working perfectly well on emulator but upon posting no image is retrieved. Commenting out the image call url makes the card appear just fine.
  
## Expected Behavior
I expect the card with thumbnails attached to appear
## Actual Results
Created By :SYSTEM
Date Created :5/23/2018 2:55:29 PM
Message :Operation returned an invalid status code 'BadRequest'
StackTrace :   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.AlwaysSendDirect_BotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__4.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotToUser.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.InputHintQueue.<Microsoft-Bot-Builder-Dialogs-Internals-IMessageQueue-QueueMessageAsync>d__4.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotToUser.cs:line 184
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.AutoInputHint_BotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__3.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotToUser.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.MapToChannelData_BotToUser.<PostAsync>d__3.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\BotToUser.cs:line 295
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.LogBotToUser.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__4.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\ConnectorEx\IActivityLogger.cs:line 131
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogContext.<Microsoft-Bot-Builder-Dialogs-Internals-IBotToUser-PostAsync>d__12.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\Dialogs\DialogContext.cs:line 87
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BotAppTut.Dialogs.BookRide.BookRideDialog.<MessageReceivedAsync>d__14.MoveNext() in E:\MARTO-WORKS\Projects\BOT APPLICATIONS\LITTLE\LittleBot\LittleBot\Dialogs\BookRide\BookRideDialog.cs:line 353
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.DialogTask.ThunkResume`1.<Rest>d__5.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\Dialogs\DialogTask.cs:line 164
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.<Microsoft-Bot-Builder-Internals-Fibers-IWait<C>-PollAsync>d__19.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\Fibers\Wait.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Frame`1.<Microsoft-Bot-Builder-Internals-Fibers-IFrameLoop<C>-PollAsync>d__9.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\Fibers\Fiber.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Internals.Fibers.Fiber`1.<Microsoft-Bot-Builder-Internals-Fibers-IFiberLoop<C>-PollAsync>d__16.MoveNext() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\Fibers\Fiber.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Bot.Builder.Internals.Fibers.Wait`2.Microsoft.Bot.Builder.Internals.Fibers.IAwaiter<T>.GetResult() in D:\a\1\s\CSharp\Library\Microsoft.Bot.Builder\Fibers\Wait.cs:line 378
   at LittleBot.Dialogs.RootDialog.<ResumeAfterOptionDialog>d__5.MoveNext() in E:\MARTO-WORKS\Projects\BOT APPLICATIONS\LITTLE\LittleBot\LittleBot\Dialogs\RootDialog.cs:line 178

-----------------------------------------------------------------------------

**Comment by JasonSowers** [comment]
What code is here `BookRideDialog.cs:line 353` from your stack trace?
When I tested locally the following code worked on the emulator:

```cs
            var card = new ThumbnailCard
            {
                Title = "title",
                Subtitle = "subttitle",
                Text = "text",
                Images = new List<CardImage> { new CardImage(@"C:\Users\v-jassow\pictures\bomb300.png")},
                Buttons = new List<CardAction>() {

                    new CardAction ()
                    {
                        Value = "title",
                        Type = "postBack",
                        Title = "Request Ride"
                    },
                    new CardAction ()
                    {
                        Value = "Help",
                        Type = "postBack",
                        Title = "Help"
                    },
                },
            };
```

I'm not 100% positive, but I think I ran into a similar issue here on GitHub a while back #4037.  And the reason you are running into this has to do with absolute vs relative paths when hosting your bot iirc.   The issue that I was working on had to do with clickable images, and I wish I could remember the full details, but let me share some thoughts as It might help you.  [You can find the project I made to resolve that customers issue here](https://github.com/JasonSowers/HeroCardOpenUrl).

You may want to try sending the image as a base64 string.  I am including the try catch here because it's a good way to diagnose if the method you are using to get the image filepath  is what is causing the problem:
```cs
            string base64String;
            string image64;
            try
            {
                using (Image image = Image.FromFile(HttpContext.Current.Server.MapPath("~/App_Data/images/_footer-logo.png")))
                {
                    using (MemoryStream m = new MemoryStream())
                    {
                        image.Save(m, image.RawFormat);
                        byte[] imageBytes = m.ToArray();

                        // Convert byte[] to Base64 String
                        base64String = Convert.ToBase64String(imageBytes);
                    }
                }
                image64 = "data:image/png;base64," + base64String;
            }
            catch (Exception e)
            {
                Console.WriteLine(e);
                throw;
            }
```
then add it to your herocard like this:
               `Images = new List<CardImage>{ new CardImage(url: image64)},`

Let me know your results with this , if it doesnt work we can continue looking into it.

**Comment by JasonSowers** [comment]
Update: I was able to reproduce the issue in skype of the thumbnail not showing up and I fixed it using the base64 method.

Original code:
![image](https://user-images.githubusercontent.com/6301037/40456737-c5ce1318-5ea7-11e8-9484-d34a6a838d5b.png)

Base64String:
![image](https://user-images.githubusercontent.com/6301037/40456763-e50534c8-5ea7-11e8-9bad-75c937e2ed72.png)
