### ISSUE TITLE
Accessing the LUIS.AI site behind corp. proxy

### ISSUE THREAD

**Issue by jonah-dawg** [Microsoft/BotBuilder#4660]
## Issue Description
- Unable to access the luis.ai website.  Previously able to but now page won't load up and seeing errors in console.

## Reproduction Steps
1. Visit https://www.luis.ai/

## Actual Results

BROWSER CONSOLE OUTPUT BELOW
-------------------------------
HTML1300: Navigation occurred.
www.luis.ai
CSP14309: Unknown directive 'frame-ancestors' in Content-Security-Policy - directive will be ignored.
CSP14303: Content-Security-Policy policy was empty.
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,9288)
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,9392)
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,9500)
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,9606)
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,9713)
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,9818)
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,9925)
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,10036)
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,10138)
CSS3120: No fonts available for @font-face rule
WebCore.4.15.2.ltr.light.min.css (78,10246)
SEC7111: HTTPS security is compromised by null
SEC7120: Origin https://www.luis.ai not found in Access-Control-Allow-Origin header.
www.luis.ai
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.
www.luis.ai
HTTP403: FORBIDDEN - The server understood the request, but is refusing to fulfill it.
(XHR)GET - https://luisweb.blob.core.windows.net/prod-assets/adminSettings/adminSettings.json
HTTP401: DENIED - The requested resource requires user authentication.
(XHR)GET - https://api.luis.ai/webapi/v2.0/auth/authinfo
HTTP401: DENIED - The requested resource requires user authentication.
(XHR)GET - https://api.luis.ai/webapi/v2.0/token/arm
EXCEPTION: Uncaught (in promise): A server error occured. Please refresh the page and try again
vendor.626dacbc7b881d1f60b9.js (1221,243)
ORIGINAL STACKTRACE:
vendor.626dacbc7b881d1f60b9.js (1221,243)
Error: Uncaught (in promise): A server error occured. Please refresh the page and try again
   at resolvePromise (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1381) [angular]
   at resolvePromise (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1144) [angular]
   at Anonymous function (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1858) [angular]
   at onInvokeTask (https://www.luis.ai/vendor.626dacbc7b881d1f60b9.js:554:2627) [angular]
   at Zone.prototype.runTask (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:4925) [<root> => angular]
   at drainMicroTaskQueue (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:614) [<root>]
   at invoke (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:8916) [<root>]
   at n.args[0] (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:29:96) [<root>]
vendor.626dacbc7b881d1f60b9.js (1221,243)
Unhandled Promise rejection: A server error occured. Please refresh the page and try again ; Zone: angular ; Task: Promise.then ; Value: A server error occured. Please refresh the page and try again undefined
polyfills.626dacbc7b881d1f60b9.js (50,302)
Error: Uncaught (in promise): A server error occured. Please refresh the page and try again
polyfills.626dacbc7b881d1f60b9.js (50,302)
   {
      [functions]: ,
      __proto__: { },
      description: "Uncaught (in promise): A server error occured. Please refresh the page and try again",
      message: "Uncaught (in promise): A server error occured. Please refresh the page and try again",
      name: "Error",
      originalStack: "Error: Uncaught (in promise): A server error occured. Please refresh the page and try again
   at ZoneAwareError (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:2118)
   at resolvePromise (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1381)
   at resolvePromise (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1144)
   at Anonymous function (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1858)
   at ZoneDelegate.prototype.invokeTask (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:7609)
   at onInvokeTask (https://www.luis.ai/vendor.626dacbc7b881d1f60b9.js:554:2627)
   at ZoneDelegate.prototype.invokeTask (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:7609)
   at Zone.prototype.runTask (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:4925)
   at drainMicroTaskQueue (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:614)
   at invoke (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:8916)
   at n.args[0] (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:29:96)",
      promise: { },
      rejection: "A server error occured. Please refresh the page and try again",
      stack: "Error: Uncaught (in promise): A server error occured. Please refresh the page and try again
   at resolvePromise (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1381) [angular]
   at resolvePromise (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1144) [angular]
   at Anonymous function (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1858) [angular]
   at onInvokeTask (https://www.luis.ai/vendor.626dacbc7b881d1f60b9.js:554:2627) [angular]
   at Zone.prototype.runTask (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:4925) [<root> => angular]
   at drainMicroTaskQueue (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:614) [<root>]
   at invoke (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:8916) [<root>]
   at n.args[0] (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:29:96) [<root>]",
      task: { },
      zone: { },
      zoneAwareStack: "Error: Uncaught (in promise): A server error occured. Please refresh the page and try again
   at resolvePromise (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1381) [angular]
   at resolvePromise (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1144) [angular]
   at Anonymous function (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:1858) [angular]
   at onInvokeTask (https://www.luis.ai/vendor.626dacbc7b881d1f60b9.js:554:2627) [angular]
   at Zone.prototype.runTask (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:4925) [<root> => angular]
   at drainMicroTaskQueue (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:614) [<root>]
   at invoke (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:50:8916) [<root>]
   at n.args[0] (https://www.luis.ai/polyfills.626dacbc7b881d1f60b9.js:29:96) [<root>]"
   }

SEC7120: Origin https://www.luis.ai not found in Access-Control-Allow-Origin header.
www.luis.ai
SCRIPT7002: XMLHttpRequest: Network Error 0x80700013, Could not complete the operation due to error 80700013.
www.luis.ai
HTTP403: FORBIDDEN - The server understood the request, but is refusing to fulfill it.
(XHR)GET - https://luisweb.blob.core.windows.net/prod-assets/adminSettings/adminSettings.json
[www.luis.ai-1527256992872.log](https://github.com/Microsoft/BotBuilder/files/2039648/www.luis.ai-1527256992872.log)

**Comment by fanidamj** [comment]
Can you please share .HAR file from the chrome developer console and the email id with which you are logging to luisuservoice@microsoft.com so that we can investigate further.

**Comment by fanidamj** [comment]
We reproduced on our end and it works fine. Can you please let us know if the issue still persists?
