### ISSUE TITLE
[.NET Core, v4] Submit Action in Adaptive Cards causing a Middleware Exception in .NET Core Project, Emulator Giving 500 Error 

### ISSUE THREAD

**Issue by SHUBHAMARORA731** [Microsoft/BotBuilder#4694]
SDK Platform: .NET 
Adaptive Cards
Active Channels: Direct Line
Deployment Environment: local development with Emulator

**Comment by JasonSowers** [comment]
Can you please share your code? What version of the SDK are you using? What is your expected result vs actual result?

**Comment by SHUBHAMARORA731** [comment]
Hi Jason,

We are using Microsoft.Bot.Builder.Core version 4.0.0-preview and AdaptiveCards v 1.0.0 in solution.

we are creating a Simple Adaptive card using Adaptive Cards nuget package (c#) as shown in https://adaptivecards.io/explorer/Action.Submit.html .  In emulator, if we click on submit button we are getting  POST500directline.postActivity (An unhandled exception occurred while processing the request.) .

Solution is catching a middleWare Exception : 

{System.ArgumentNullException: Value cannot be null.
Parameter name: utterance
   at Microsoft.Bot.Builder.Ai.LUIS.LuisRecognizer.RecognizeInternal(String utterance, CancellationToken ct)
   at Microsoft.Bot.Builder.Ai.LUIS.LuisRecognizer.<Recognize>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Ai.LUIS.LuisRecognizerMiddleware.<OnTurn>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Core.Extensions.BotState`1.<OnTurn>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Core.Extensions.CatchExceptionMiddleware`1.<OnTurn>d__2.MoveNext()} 




how to handle Submit action from adaptive cards and capture the reponse selected by user.

**Comment by mennolaan** [comment]
Running into the same issue as above. The change from the previous version to this made this more into an adventure as documentation is no reflecting the examples in GitHub. So it's more of an hit or miss scenario. I'm going to subscribe to this as well, hopefully we will see a solution shortly.

**Comment by SHUBHAMARORA731** [comment]
Hi menno , 

The issue is because of Luis recognizer which is being called even if we have a submit action and utterance is null.
Please check this  https://github.com/Microsoft/botbuilder-dotnet/issues/572 
they did resolve this by doing a null check before calling Luis recognizer but still not published to NuGet gallery.

for the time being, I am referring to Microsoft.Bot.Builder.Ai.LUIS class locally  (https://github.com/Microsoft/botbuilder-dotnet/tree/master/libraries/Microsoft.Bot.Builder.Ai.LUIS) instead of getting from NuGet 

Hope this helps!

**Comment by mennolaan** [comment]
Good call, I will try that out right away.

**Comment by mennolaan** [comment]
Do note in order to use the Luis project in your solution with VSTS, you need to include the Strong Name Key (35MSSharedLib1024) in your project, otherwise automatic builds will fail.

**Comment by stevengum** [comment]
@mennolaan did SHUBHAMARORA731's solution address the issue?

**Comment by stevengum** [comment]
Closing due to inactivity.
