### ISSUE TITLE
 Invalid token exception

### ISSUE THREAD

**Issue by Skreet2k** [Microsoft/BotBuilder#4900]
## Bot Info
* SDK Platform: .NET
* SDK Version: 3.14.1.1
* Active Channels: MS Teams
* Deployment Environment: custom server

## Issue Description
Bot work with ms teams about 3-4 months without changes, and now stoped working.
When i attach to iis process, break point at MessagesController.Post doesn't trigger, application down after constructor was successfully worked with exception in output.
The application was configured.
Web.config contains MicrosoftAppId and MicrosoftAppPassword. Values copied from https://dev.botframework.com.

When i remove [BotAuthentication] attribute from Controller, break point at MessagesController.Post triggered but with some authorization problem.

App was recreated some times for testing what wrong.

## Actual Results
w3wp.exe Warning: 0 : Invalid token. Microsoft.IdentityModel.Tokens.SecurityTokenNotYetValidException: IDX10222: Lifetime validation failed. The token is not yet valid. ValidFrom: '[PII is hidden]', Current time: '[PII is hidden]'.
   at Microsoft.IdentityModel.Tokens.Validators.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, SecurityToken securityToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateLifetime(Nullable`1 notBefore, Nullable`1 expires, JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.ValidateTokenPayload(JwtSecurityToken jwtToken, TokenValidationParameters validationParameters)
   at Microsoft.Bot.Connector.JwtTokenExtractor.<ValidateTokenAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Connector.JwtTokenExtractor.<GetIdentityAsync>d__11.MoveNext()

**Comment by Skreet2k** [comment]
Problem was with time at server machine. The time not synchronize with internet time. It's was problem.
