### ISSUE TITLE
 GetTokenAsync throws exception : A connection attempt failed because the connected party did not properly respond after a period of time

### ISSUE THREAD

**Issue by huyjack178** [Microsoft/BotBuilder#4994]
I got this error after running well for a long time. Please help check
I use Microsoft.Bot.Connector.MicrosoftAppCredentials.GetTokenAsync(Boolean forceRefresh)
```
 A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.CreateConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.WaitForCreatedConnectionAsync(ValueTask`1 creationTask)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Bot.Connector.MicrosoftAppCredentials.RefreshTokenAsync()
   at Microsoft.Bot.Connector.MicrosoftAppCredentials.GetTokenAsync(Boolean forceRefresh)
```

**Comment by Zerryth** [comment]
Hi, @huyjack178!

Could you please provide the following information? That way we can reproduce the issue and drill down to a solution :) :

1. Steps taken (repro)
2. What actually happens (I see you've provided the error)
3. What results are desired?
4. What version of the SDK are you using (V3 vs. V4?)

~ Ashley

**Comment by huyjack178** [comment]
Sorry, root cause is my deploy server can not connect to the internet. I will close this issue
