### ISSUE TITLE
[NodeJs] Getting 'Intent recognition error: Unexpected end of input' when using LUIS

### ISSUE THREAD

**Issue by SamAlbuga** [Microsoft/BotBuilder#50]
I'm getting this error when trying the LuisDialog example in the tutorial. Note that I'm using the latest version 0.6.5:
` events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: Intent recognition error: Unexpected end of input
    at C:\Users\Admin\Documents\AWBot\node_modules\botbuilder\lib\dialogs\IntentDialog.js:42:44
    at Request._callback (C:\Users\Admin\Documents\AWBot\node_modules\botbuilder\lib\dialogs\LuisDialog.js:37:17)
    at Request.self.callback (C:\Users\Admin\Documents\AWBot\node_modules\botbuilder\node_modules\request\request.js:199:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\Admin\Documents\AWBot\node_modules\botbuilder\node_modules\request\request.js:1036:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\Admin\Documents\AWBot\node_modules\botbuilder\node_modules\request\request.js:963:12)
    at emitNone (events.js:72:20) `

**Comment by Stevenic** [comment]
Which example are you using specifically and does it throw that error regardless of the text you type in?  I ask because looking at where the error is being raised its coming from the request we make to the LUIS service. It looks like either the LUIS service is returning this error or as the error message says, something is wrong with the input. Are you just pressing "enter" by chance?

**Comment by Stevenic** [comment]
So I got this same error today when I had a bad LUIS url. We had a bad URL in the multiTurn example that I fixed the other day so I'm assuming that's the issue you're running into. Please pull the latest version of the examples and if that doesn't resolve the issue please feel free to re-open this issue.

**Comment by SamAlbuga** [comment]
Thanks! I had a bad LUIS url
