### ISSUE TITLE
All buttons should work whenever the user presses them, chatbot node.js

### ISSUE THREAD

**Issue by kamuops** [Microsoft/BotBuilder#5065]
## Bot Info
* SDK Platform: 
* SDK Version: 
* Active Channels: <MS Teams,etc. -->
* Deployment Environment: < local development with Emulator? -->

## Issue Description

Whenever I click the button it is not returning to the same menu options, it is throwing the error as Error: Dialog[end] already exists in library[*].

## Code Example
        let card = new builder.HeroCard(session)
			.title('Bot for Global service Desk')
			.text('Select any option')
			.buttons([
			builder.CardAction.dialogAction(session, 'Desktop', 'Desktop Support', 'Desktop Support'),
			builder.CardAction.dialogAction(session, 'Application', 'Application Support', 'Application Support'),
			builder.CardAction.dialogAction(session, 'Network ', 'Network Support', 'Network Support'),
		]);
        let message = new builder.Message(session)
           .addAttachment(card);
        session.send(message);

   bot.dialog('Desktop Support', (session) => {
    session.endConversation(`The Desktop Dialog`)
}).triggerAction( { matches: /desktop/ } );
 bot.dialog('Application Support', (session) => {
    session.endConversation(`The Application Dialog`)
}).triggerAction( { matches: /application/ } );

bot.dialog('Network Support', (session) => {
    session.endConversation(`The Network Dialog`)
}).triggerAction ( { matches: /network/ } );  
 	
bot.beginDialogAction('Desktop', 'Desktop Support',{
	onSelectAction: (session, args, next) => {
    session.clearDialogStack();
    next();
	}
bot.beginDialogAction('Application', 'Application Support',{
	{
	onSelectAction: (session, args, next) => {
     session.clearDialogStack();
    next();
	}
bot.beginDialogAction('Network', 'Network Support',{
	onSelectAction: (session, args, next) => {
    session.clearDialogStack();
    next();
  }
});

## Reproduction Steps
1.
2.
3.

## Expected Behavior
All buttons should work whenever the user presses them, even if they scroll back in the conversation and press the same button again.

## Actual Results
Error: Dialog[end] already exists in library[*].
    at UniversalBot.Library.dialog (D:\Bot\node_modules\botbuilder\lib\bots\Library.js:384:23)
    at getName (D:\Bot\menu_modify.js:130:5)
    at Array.<anonymous> (D:\Bot\menu_modify.js:51:9)
    at D:\Bot\node_modules\botbuilder\lib\dialogs\WaterfallDialog.js:67:39
    at next (D:\Bot\node_modules\botbuilder\lib\dialogs\WaterfallDialog.js:92:21)
    at WaterfallDialog.beforeStep (D:\Bot\node_modules\botbuilder\lib\dialogs\WaterfallDialog.js:99:9)
    at WaterfallDialog.doStep (D:\Bot\node_modules\botbuilder\lib\dialogs\WaterfallDialog.js:61:14)
    at WaterfallDialog.begin (D:\Bot\node_modules\botbuilder\lib\dialogs\WaterfallDialog.js:29:14)
    at Session.beginDialog (D:\Bot\node_modules\botbuilder\lib\Session.js:254:16)
    at Session.routeToActiveDialog (D:\Bot\node_modules\botbuilder\lib\Session.js:528:22)
ERROR: Dialog[end] already exists in library[*].
Session.endConversation()
Session.sendBatch() sending 2 message(s)
Session.sendBatch() sending 2 message(s)
The Bot State API is deprecated.  Please refer to https://aka.ms/I6swrh for details on how to replace with your own storage.

**Comment by amitbend** [comment]
read the error `Error: Dialog[end] already exists in library[].`
you need have a dialog with the same name

**Comment by kamuops** [comment]
hi @jwiley84 Thanks for your response, my requirement here is I have used ThumbnailCard for creating buttons using node.js and the conversation flow is working fine. 
To ensure consistent throughout the usage of the bot, buttons should work whenever the user presses them, even if they scroll back in the conversation and press the same button again.I am completely new to Bot framework, Kindly help me with this.


Below the sample code.

bot.dialog('/', function (session, args) {
	 if (!session.userData.name)
    {
        console.log('Start conversation');
        getName(session);
    }
    else if(!session.userData.option)
    {
        console.log('User selected option');
        getOption(session);
    }
  else {
        session.userData = null;
    }
    session.endDialog(); 
});
function getName(session) {
		name = session.message.text;
		session.userData.name = name;
		session.send("Hello ,"+userName +"\nI can help you with the following")
        const card = new builder.ThumbnailCard(session)
            .buttons([
                builder.CardAction.imBack(session, 'user Support','user Support'),
                builder.CardAction.imBack(session, 'system Support','system Support'),
            ]);
        const message = new builder.Message(session)
           .addAttachment(card)
        session.send(message);	
}
	
 function getOption(session){
		option = session.message.text;
		session.userData.option = option;
		
		 if(option == "user Support")
				{
						const card = new builder.ThumbnailCard(session)
						 .text("You have Selected User Support")
						.buttons([
							builder.CardAction.imBack(session, 'login issue', 'login issue'),
                                                       builder.CardAction.imBack(session, 'other issue', 'other issue'),
						]);
					const message = new builder.Message(session)
						.addAttachment(card);
					session.endConversation(message);	     
				}
				else if(option == "system Support"){
						  const card = new builder.ThumbnailCard(session)
						 .text("You have Selected "+option)
						.buttons([
							builder.CardAction.imBack(session, 'Clean Profile', 'Clean Profile'),
							builder.CardAction.imBack(session, 'Clean PST', 'Clean PST'),
							builder.CardAction.imBack(session, 'Clean Reminders', 'Clean),
					const message = new builder.Message(session)
					.addAttachment(card);
					session.endConversation(message);
							}
}

**Comment by jwiley84** [comment]
I was able to reproduce the error you were having by using your code. The problem seemed to be that you had your cards tucked into functions, and once the getName function was completed, the card was now essentially out of scope of the dialog. It was looking for one of the options given in the getOptions function, and by clicking on the earlier buttons, you were trying to pass an option from getName.

By removing the functions, and making them anonymous functions instead, it returned the ability to click repeatedly on the buttons as needed. 

Here is a rough version of what I was able to get to work as you expected: 

`bot.dialog('/', function (session, args) {
    if (!session.userData.name) {
        userName = session.message.text;
        session.userData.name = userName;
    }
        session.send("Hello, " + userName + "\nI can help you with the following")
        const card = new builder.ThumbnailCard(session)
            .buttons([
                builder.CardAction.dialogAction(session, '1', 'user support', 'User Support'),
                builder.CardAction.dialogAction(session, '2','system support', 'System Support'),
            ]);
        const message = new builder.Message(session)
            .addAttachment(card)
        session.send(message); 
});

//bot dialogs actions
bot.beginDialogAction('1', 'user support', {
    onSelectAction: (session, args, next) => {
        const card = new builder.ThumbnailCard(session)
            .text("You have selected User Support")
            .buttons([
                builder.CardAction.imBack(session, 'login issue', 'login issue'),
                builder.CardAction.imBack(session, 'other issue', 'other issue'),
            ]);
        const message = new builder.Message(session)
            .addAttachment(card);
        session.send(message);
    }
});

bot.beginDialogAction('2', 'system support', {
    onSelectAction: (session, args, next) => {
        const card = new builder.ThumbnailCard(session)
            .text("You have selected User Support")
            .buttons([
                builder.CardAction.imBack(session, 'Clean Profile', 'Clean Profile'),
                builder.CardAction.imBack(session, 'Clean PST', 'Clean PST'),
                builder.CardAction.imBack(session, 'Clean Reminders', 'Clean'),
            ]);
        const message = new builder.Message(session)
            .addAttachment(card);
        session.send(message);
    }
});`


And here is the screenshot: 

![image](https://user-images.githubusercontent.com/17333688/46044650-3f263800-c0d0-11e8-874e-ac72fa67e62d.png)

**Comment by kamuops** [comment]
@jwiley84 Appreciate your response, will modify my code accordingly and keep you posted with the status. Thank you.

**Comment by kamuops** [comment]
@jwiley84 Good Morning Jesicca.. Could you please help me with the above issue.
