### ISSUE TITLE
Make API calls inside LUIS Dialog

### ISSUE THREAD

**Issue by DavePilks** [Microsoft/BotBuilder#513]
I have a bot that has a `LuisDialog`.

If, in one of the processing methods, I try to call an externally hosted API, I get an `AccessDenied` exception.

> 2016-06-21 09:57:40.9272|ERROR|MyBot.Controllers.MessagesController+<Post>d__2|Microsoft.Rest.HttpOperationException: Access Denied
   at Microsoft.Bot.Connector.ErrorHandling.HandleError[ObjectT](HttpOperationResponse`1 result)
   at Microsoft.Bot.Connector.BotsExtensions.<SetConversationDataAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<PersistBotData>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Internals.PersistentDialogTask.<Microsoft-Bot-Builder-Dialogs-Internals-IPostToBot-PostAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Bot.Builder.Dialogs.Conversation.<SendAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MyBot.Controllers.MessagesController.<Post>d__2.MoveNext()

What could be causing this?

	[LuisIntent(LuisIntents.GetData)]
	public async Task GetDataTask(IDialogContext context, LuisResult result)
	{
		var entities = result.GetEntitiesAsDictionary();

		var term = entities.FirstOrDefault(pair => pair.Key.Equals(LuisEntities.Term)).Value;
		var name = entities.FirstOrDefault(pair => pair.Key.Equals(LuisEntities.Name)).Value;

		if (string.IsNullOrWhiteSpace(term) || string.IsNullOrWhiteSpace(name))
		{
			await context.PostAsync(GeneralConstants.EntityResolutionError);
			context.Wait(MessageReceived);
		}
		else
		{
			LogManager.GetCurrentClassLogger().Info("In the dialog");
			var apiResponse = await _DataApi.GetDataFromApiAsync(name, term);
			LogManager.GetCurrentClassLogger().Info("Got a response");
			await context.PostAsync($"The {name}'s {term} is {apiResponse}", "en");

			context.Wait(MessageReceived);
		}
	}

It doesnt get to log the "Got a response", but does log the first bit.

**Comment by DavePilks** [comment]
last time this was mentioned, it seemed that the bot may have been timing out. How can I see if this is the case?  If it is the case how can I increase this timeout limit?

The botid is :roboassistant

**Comment by willportnoy** [comment]
You're getting AccessDenied from the _DataApi.GetDataFromApiAsync call?

**Comment by DavePilks** [comment]
@willportnoy no. Let me go into a little more details.

The `_DataApi.GetDataFromApiAsync` call is not even completed. Inside that method I simple return a string. I also have  `Log` statement inside that method to see if I can even get inside there and it doesn't. So the `AccessDenied` seems to be the result of simply trying to call the async method.

This bot is hosted on Azure and I am trying to reach it via the DirectLine channel. If I install the emulator on the VM, and use that to communicate with the bot, it works perfectly. However, if I try and use the WebChat or DirectLine, it falls over with the above mentioned error.

**Comment by willportnoy** [comment]
I don't think the SDK is interfering with async calls in any way.  If you happen to have an active SynchronizationContext on the thread, and you synchronously wait on that thread somewhere in the implementation of GetDataFromApiAsync, it's possible you might see a deadlock (e.g. http://blogs.msdn.com/b/pfxteam/archive/2012/04/13/10293638.aspx).

**Comment by DavePilks** [comment]
It write to a text file. What I posted in the original comment is what is written in the logs.

What I find odd is this.

the `GetDataFromApiAsync` simply returns a static string at this point. If I use the emulator that is running on the server, the call works perfectly. If I try via the WebChat client. I get that error as it  has to go through the DirectLine api.

If I remove that `async` call and simply return a string right away, both cases work.

Unfortunately this is not an option for me as I have to actually make a service call in that method and the static string is just a place holder for the moment.

**Comment by willportnoy** [comment]
@dandriscoll do you have any insights into the AccessDenied error?

**Comment by DavePilks** [comment]
@willportnoy @dandriscoll Any ideas on this, it is really hampering me as I cannot do anything more until I am able to resolve this situation.

**Comment by willportnoy** [comment]
Can you attach a debugger to your bot?  It seems so much more likely that an exception is coming from PostMessage than your GetDataFromApiAsync or the await of that returned task.

**Comment by willportnoy** [comment]
@DavePilks just to be clear, how do you set your bot credentials?  (Ignoring for a moment that the exception seems to be coming from the await statement)

When more than one message is sent, we save the last message to return inline with the incoming http request from the connector.  All of the messages other than the last message are sent directly to the connector through the IConnectorClient.

So sending two messages is a code path that exercises IConnectorClient, and using the IConnectorClient requires authentication through ConnectorClientCredentials.  The default ConnectorClientCredentials constructor looks like for credentials stored in the app.config – it doesn’t use the credentials referenced in the BotAuthentication attribute, for example.

**Comment by v-thgratMSGit** [comment]
Closing this issue. Thanks!

**Comment by willportnoy** [comment]
Thank you for the followup link!

**Comment by ChefGillani** [comment]
this is what i did additional to first two values in the class attribute, end point change and staging true or false to make it work with Azure end point keys.

where i picked domain name: Azure portal overview tab for LUIS service.
where i picked staging true or not: after adding Azure key to my keys inside My App, i went to Luis.AI >> my app >> publish >> both staging and production end points

Reason is by default LUIS dialog calls the test endpoint of cognitive services for which only programmatic key can be used. if you want to use your azure keys then you must change the endpoint and also tell that you want to send request to stging or production end point.

hope it helps.

 [LuisModel("55810954-96b3-4427-b653-11111111", "21111156694649469db32581520e9d38",**domain: "eastus2.api.cognitive.microsoft.com"**,**staging: true**)]    
    [Serializable]
    public class LocalLUISDialog : LuisDialog<object>
    {

Shimail Gillani
Cloud Solution Architect
Microsoft Education North America
