### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by kolanos** [Microsoft/BotBuilder#52]
While running the basics-multiTurn example, I get the following error on 0.6.5.

    .../node_modules/botbuilder/lib/Session.js:123
            r.childId = ss.callstack[ss.callstack.length - 1].id;
                                                             ^

    TypeError: Cannot read property 'id' of undefined
        at Session.endDialog (../node_modules/botbuilder/lib/Session.js:123:58)
        at ../node_modules/botbuilder/lib/dialogs/IntentDialog.js:42:25
        at Request._callback (../node_modules/botbuilder/lib/dialogs/LuisDialog.js:37:17)
        at Request.self.callback (../node_modules/botbuilder/node_modules/request/request.js:199:22)
        at emitTwo (events.js:87:13)
        at Request.emit (events.js:172:7)
        at Request.<anonymous> (../node_modules/botbuilder/node_modules/request/request.js:1036:10)
        at emitOne (events.js:82:20)
        at Request.emit (events.js:169:7)
        at IncomingMessage.<anonymous> (../node_modules/botbuilder/node_modules/request/request.js:963:12)

**Comment by Stevenic** [comment]
Thanks... Let me look into this.

**Comment by Stevenic** [comment]
To go along with this I did fix a bug over the weekend with a bad LUIS url in the multi-turn example. Could you make sure you've pulled the latest,

**Comment by Stevenic** [comment]
I can't get this to reproduce... Please try making sure you've pulled the latest version of examples if it still persist please re-open the issue,

**Comment by patsplat** [comment]
@Stevenic encountered this error when testing from the command-line and hitting enter on a blank line, or hitting enter twice.

**Comment by Stevenic** [comment]
Should be fixed in v0.9.0
