### ISSUE TITLE
Error: Cannot find module 'jwa'

### ISSUE THREAD

**Issue by gfpacheco** [Microsoft/BotBuilder#651]
I setup an Azure Web App with deployment form GitHub.
Pushed the sample bot code from [Core Concepts](http://docs.botframework.com/en-us/node/builder/guides/core-concepts/).
Registered a new bot in https://dev.botframework.com.

But when I test connection to my bot the answer is `InternalServerError`.

The Azure log stream says:

```
Application has thrown an uncaught exception and is terminated:
Error: Cannot find module 'jwa'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\home\site\wwwroot\node_modules\botbuilder\node_modules\jsonwebtoken\node_modules\jws\lib\sign-stream.js:4:11)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by danmarshall** [comment]
Hi @gfpacheco , can you show the code in your module.js ?

**Comment by gfpacheco** [comment]
Weird, disconnecting the deployment source from Azure and connecting again solved the problem.

**Comment by suvamsh** [comment]
I'm seeing a very similar issue:

Fri Feb 24 2017 06:25:32 GMT+0000 (Coordinated Universal Time): Application has thrown an uncaught exception and is terminated:
SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Program Files (x86)\iisnode\interceptor.js:459:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)

I tried disconnecting from source and reconnecting but the problem persists. Any ideas? The code works locally using the emulator.
