### ISSUE TITLE
[v3.1.1 Node] [Messenger] new 500 errors when using 3.1.0, 3.1.1

### ISSUE THREAD

**Issue by dudeofawesome** [Microsoft/BotBuilder#781]
I had a bot working with v3.0.1, but needed to update to 3.1.x to get a bugfix. Now, on 3.1.x, I'm getting 500 errors like the one below whenever I try to send messages from the bot.

I haven't changed anything about my bot except the version of botbuilder it is running.

Here's an error that it is throwing.

```
Error: Request to 'https://facebook.botframework.com/v3/conversations/1084613888243541-1063346527086061/activities/mid.1469080260144%3Ab45627fe553f667216' failed: [500] Internal Server Error
    at Request._callback (/Users/DudeOfAwesome/Github/hello-bot/node_modules/botbuilder/lib/bots/ChatConnector.js:356:46)
    at Request.self.callback (/Users/DudeOfAwesome/Github/hello-bot/node_modules/request/request.js:200:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/DudeOfAwesome/Github/hello-bot/node_modules/request/request.js:1067:10)
    at emitOne (events.js:101:20)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/DudeOfAwesome/Github/hello-bot/node_modules/request/request.js:988:12)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:973:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

Are there some breaking changes that I missed reading about?

**Comment by randa1** [comment]
I'm having this issue too. Any message my bot tries to send via Facebook Messenger results in this error.

Is there any known issue with the service?

**Comment by alyssaong1** [comment]
Ditto, having this issue here too :(

**Comment by matts310** [comment]
+1

**Comment by KirinDave** [comment]
+1

**Comment by kichingxx** [comment]
+1

**Comment by dudeofawesome** [comment]
I just tried it again, and it looks like the 500 error has disappeared when using 3.1.1

Make sure that you're not using 3.0.1 though, because then no messages get through at all, and no errors are displayed either.

**Comment by alyssaong1** [comment]
Works for me now too. (also found out that node_modules wasn't being ignored for some reason and that was causing problems too I think)

**Comment by plkumar** [comment]
+1

i'm seeing this issue with Sky.

Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1lm8ymLQhQ5WvPYm55K2BAd5u6klEeaEJuZBvHXgskBI/activities' failed: [500] Internal Server Error
    at Request._callback (/Users/lakshman/Documents/StockBot/node_modules/botbuilder/lib/bots/ChatConnector.js:356:46)
    at Request.self.callback (/Users/lakshman/Documents/StockBot/node_modules/request/request.js:187:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/Users/lakshman/Documents/StockBot/node_modules/request/request.js:1044:10)
    at emitOne (events.js:90:13)
    at Request.emit (events.js:182:7)
    at IncomingMessage.<anonymous> (/Users/lakshman/Documents/StockBot/node_modules/request/request.js:965:12)
    at emitNone (events.js:85:20)
    at IncomingMessage.emit (events.js:179:7)

**Comment by APXEOLOG** [comment]
Any comments for this one? Same problem for me

**Comment by APXEOLOG** [comment]
Using 3.2.3, extended error message:
`{ errorCode: -1,
  message: 'ExceptionContext::MS.Msn.Messenger.ConnectionGateway.WebApi.Models.ResourceMri GetDecryptedIdentity(MS.Msn.Messenger.ConnectionGateway.WebApi.Models.ResourceMri, MS.Msn.Messenger.Runtime.MessengerResourceIdentifier, MS.Msn.Messenger.Runtime.Agents.ApsAgentCache)' }
`

**Comment by VishalWaman** [comment]
+1
Finding..
1. Generally occurs when we try to send receipt/hero/thumbnail card
2. Once error occurs, that conversation ID has this error... Others conversation work well.
3. Told don't happen with emulator 
4. As of now error found in skype and Facebook

**Comment by APXEOLOG** [comment]
Any updates on this?

**Comment by somprabhsharma** [comment]
I am also getting the same error in messenger :-(

**Comment by dandriscoll** [comment]
Hi @APXEOLOG, the MS.Msn.Messenger code is completely foreign to me. Are you using the Bot Builder SDK and the Bot Framework service?

**Comment by APXEOLOG** [comment]
Hi @dandriscoll , yes. This message code i got while debugging the source of the nodejs botbuilder sdk. The interesting thing is that it works with "Web Chat" channel, but doesn't work with Skype

**Comment by ceohockey60** [comment]
I'm getting the same error on skype as well. Any update?

**Comment by chrimc62** [comment]
Closing because of age.  Please open a new issue if you are still seeing the same problem with the latest SDK and service release.
