### ISSUE TITLE
Emulator doesnt work. An error occurred while sending the request.

### ISSUE THREAD

**Issue by bluekite2000** [Microsoft/BotBuilder#80]
Sometimes the emulator works. Sometime it doesnt. The error is.
> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:3978
>    at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
>    at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
>    --- End of inner exception stack trace ---
>    at System.Net.HttpWebRequest.EndGetRequestStream(IAsyncResult asyncResult, TransportContext& context)
>    at System.Net.Http.HttpClientHandler.GetRequestStreamCallback(IAsyncResult ar)
>    --- End of inner exception stack trace ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
>    at BotFrameworkEmulator.SessionModel.<SendMessageAsync>d__46.MoveNext()

**Comment by tomlm** [comment]
This error happens if your web server is not running.  Please make sure your server is listening at that port.

**Comment by bluekite2000** [comment]
@tomlm what do you mean? I  can go to 127.0.0.1:3978 on my browser and it works fine. I only get the An error occurred while sending the request when I run the simulator

**Comment by afarvardin** [comment]
@tomlm, I have the same problem. Already everything works fine. I got respond from emulator but now I have the same issue of @bluekite2000.

**Comment by GauravSharma531** [comment]
I also have the same issue verified server is running still getting this error.

**Comment by GauravSharma531** [comment]
@tomlm I also have the same issue verified server is running still getting this error. can you reopen this issue.

**Comment by GauravSharma531** [comment]
BFEmulator.exe Information: 0 : System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000d1] in <affe4060066c42de8cdd6027cdb92b56>:0 
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0019b] in <affe4060066c42de8cdd6027cdb92b56>:0 
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x00043] in <affe4060066c42de8cdd6027cdb92b56>:0 
  at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult, System.Net.TransportContext& transportContext) [0x00003] in <affe4060066c42de8cdd6027cdb92b56>:0 
  at (wrapper remoting-invoke-with-check) System.Net.HttpWebRequest:EndGetRequestStream (System.IAsyncResult,System.Net.TransportContext&)
  at System.Net.Http.HttpClientHandler.GetRequestStreamCallback (System.IAsyncResult ar) [0x0003a] in <72bd8f9e99df4e75a5c72952f3a9348e>:0 
   --- End of inner exception stack trace ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at Microsoft.Bot.Connector.Emulator.ConversationModel+<>c__DisplayClass44_0+<<SendActivityToBot>b__0>d.MoveNext () [0x002a0] in <d4c6ccc0f34747dbaeb11c89a61800fc>:0 
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Error: ConnectFailure (Connection refused) ---> System.Net.Sockets.SocketException: Connection refused
  at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000d1] in <affe4060066c42de8cdd6027cdb92b56>:0 
  at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0019b] in <affe4060066c42de8cdd6027cdb92b56>:0 
   --- End of inner exception stack trace ---
  at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x00043] in <affe4060066c42de8cdd6027cdb92b56>:0 
  at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult, System.Net.TransportContext& transportContext) [0x00003] in <affe4060066c42de8cdd6027cdb92b56>:0 
  at (wrapper remoting-invoke-with-check) System.Net.HttpWebRequest:EndGetRequestStream (System.IAsyncResult,System.Net.TransportContext&)
  at System.Net.Http.HttpClientHandler.GetRequestStreamCallback (System.IAsyncResult ar) [0x0003a] in <72bd8f9e99df4e75a5c72952f3a9348e>:0 
   --- End of inner exception stack trace ---
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0004e] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x0002e] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x0000b] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <94fd79a3b7144c54b4cb162b50fc7761>:0 
  at Microsoft.Bot.Connector.Emulator.ConversationModel+<>c__DisplayClass44_0+<<SendActivityToBot>b__0>d.MoveNext () [0x002a0] in <d4c6ccc0f34747dbaeb11c89a61800fc>:0 <---

**Comment by dandriscoll** [comment]
Make sure to pay close attention to the port numbers. Your bot must be running and must be accessible on the URL specified in the Bot Url field in the emulator UI.

Even though the trace is long, the error is very simple -- it's in this line: "No connection could be made because the target machine actively refused it 127.0.0.1:3978"
