### ISSUE TITLE
Getting Cannot find module 'sprintf-js' whenever I try to run any of the Node examples

### ISSUE THREAD

**Issue by nechmads** [Microsoft/BotBuilder#82]
Whenever I'm trying to run any of the Node examples (including the most simple ones like the hello text bot) I get the following message:
Cannot find module 'sprintf-js'.

Running on Mac OS X 10.11.4 and Node version 5.0.

I tried to install the sprintf-js module globally but of course it didn't help.
Full error stack:
module.js:339
    throw err;
    ^

Error: Cannot find module 'sprintf-js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/nechmads/Downloads/BotBuilder-master/Node/lib/Session.js:7:15)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

**Comment by Stevenic** [comment]
run "npm install" from the /node directory

**Comment by nechmads** [comment]
First thing I tried :)

**Comment by nechmads** [comment]
Oh wait. My mistake. Did it just on the example directory itself. Thanks!! That solved it.
