### ISSUE TITLE
Void Microsoft.Rest.HttpOperationException.set_Request(System.Net.Http.HttpRequestMessage)'.",

### ISSUE THREAD

**Issue by som-nitjsr** [Microsoft/BotBuilder#875]
i am trying to run the default and getting this error my details. i am getting the same error locally aswell from azure.

 <package id="Microsoft.Bot.Builder" version="3.0.1" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Logging" version="1.0.0" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.2.206221351" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.0.0" targetFramework="net46" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.2" targetFramework="net46" />

**Comment by som-nitjsr** [comment]
<package id="Microsoft.Bot.Builder" version="3.1.0" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Logging" version="1.0.0" targetFramework="net452" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.2.206221351" targetFramework="net46" />
  <package id="Microsoft.IdentityModel.Tokens" version="5.0.0" targetFramework="net452" />
  <package id="Microsoft.Rest.ClientRuntime" version="2.3.2" targetFramework="net452" />
  <package id="Microsoft.WindowsAzure.ConfigurationManager" version="3.2.1" targetFramework="net46" />
  <package id="Newtonsoft.Json" version="9.0.1" targetFramework="net452" />
  <package id="System.IdentityModel.Tokens.Jwt" version="5.0.0" targetFramework="net452" />

**Comment by SaiKrishnaTej23** [comment]
I am facing similiar problem ... what must be the case ?

**Comment by slawciu** [comment]
same here:
   at Microsoft.Bot.Connector.Conversations.<ReplyToActivityWithHttpMessagesAsync>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Bot.Connector.Conversations.ReplyToActivityWithHttpMessagesAsync(String conversationId, String activityId, Activity activity, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Bot.Connector.ConversationsExtensions.<ReplyToActivityAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Bot.Connector.ConversationsExtensions.ReplyToActivity(IConversations operations, Activity activity)

**Comment by willportnoy** [comment]
This looks similar to issue 836.  "System.IdentityModel.Tokens.Jwt.4.0.2.206221351" is the version we're using, not 5.0.0 as in the above packages.config.

**Comment by willportnoy** [comment]
I'm going to close this issue, but feel free to open a new issue for further discussions.
