### ISSUE TITLE
[503] Service Unavailable

### ISSUE THREAD

**Issue by possan** [Microsoft/BotBuilder#955]
I'm seeing lots' of 503 service unavailable right now since i just updated and redeployed my bot, every fourth/fifth request or so, is there any status page that we can check to see the status of the backend side of things?

```
Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1MLdEGh1EE_n7q7D6mFq3iQRtc-7aR5QsTrAnrZ52w8M/activities' failed: [503] Service Unavailable
at Request._callback (/src/node_modules/botbuilder/lib/bots/ChatConnector.js:438:46)
at Request.self.callback (/src/node_modules/botbuilder/node_modules/request/request.js:187:22)
```

**Comment by jameslew** [comment]
Thanks for the report possan.  Will investigate.  I don't see these errors in our logs yet, but that could just be it's not making it far enough to get logged.

**Comment by jameslew** [comment]
Can you give us a time range to look in our logs?  Are these recent?

**Comment by possan** [comment]
Yes, they are occurring right now for me.

The contents of our messages has changed slightly, but not any major changes.

**Comment by possan** [comment]
Another issue for now is that it takes quite a long time to get the first webhook message through to the bot after starting it up, a couple of days ago, that felt like was almost instant..

**Comment by possan** [comment]
I can reproduce this issue locally now too

**Comment by jameslew** [comment]
Locally, as in emulator -> bot on your local machine?

I've restarted some servers in case something was stuck.  I'm not experiencing dropped messages anymore.

**Comment by possan** [comment]
Now it seems to work again! just like before

**Comment by possan** [comment]
Any ideas why this would happen, long running webhooks, server being down when webhook call is issued etc?

**Comment by possan** [comment]
Or more importantly, how to mitigate incidents like this in the future?

**Comment by jameslew** [comment]
We're continuously upgrading our monitoring and alerting features of the platform so you shouldn't see these incidents without us catching them first.  That said, please alert us the first time you see something so we can diagnose/address appropriately.

**Comment by jameslew** [comment]
What update did you do to your bot?  Change SDK's, or other things?

**Comment by Andrea-Orimoto** [comment]
Closing due to inactivity, please open a new issue or reply to this one asking us to reopen if needed. Thanks!

**Comment by mcsee** [comment]
Getting lots of 503's on production right now.
Azure status says everithing is OK

Where can we check this ?

**Comment by EricDahlvang** [comment]
@mcsee If you have Application Insights configured for the bot, you can check there for more information regarding connector errors.
