### ISSUE TITLE
Error: Cannot find module '../Consts'

### ISSUE THREAD

**Issue by y0unghe** [Microsoft/BotBuilder#98]
I am getting this error: `Error: Cannot find module '../Consts'` when I am trying to run with command `node botConnectorBot.js`.

```
module.js:327
    throw err;
    ^

Error: Cannot find module '../Consts'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/ubuntu/todoBot/node_modules/botbuilder/lib/dialogs/DialogCollection.js:10:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

**Comment by Stevenic** [comment]
Took your pull request. thanks!
