### ISSUE TITLE
Size limit with base64 encoded attachments on the Skype channel?

### ISSUE THREAD

**Issue by thingista** [Microsoft/BotBuilder#985]
It looks like I am hitting a size limit on the Skype channel with base64 encoded attachments.

- if I send the same image to Slack it works fine
- if I send a smaller image to Skype it works

I am getting errors like this (unfortunately they are generic):

`Error: Request to 'https://skype.botframework.com/v3/conversations/xyz/activities' failed: [500] Internal Server Error`

Is there a limit with this specific channel?

**Comment by v-ms** [comment]
Currently card images have a limit in size and resolution: up to 1,000,000 bytes and up to 1024x1024 in resolution.

**Comment by thingista** [comment]
I did some further testing, and it does not seem to be the case. I tried to send a 230KB, 1000x600 image across and it failed with this error message:

`Error: Request to 'https://skype.botframework.com/v3/conversations/xyz/activities' failed: [400] Bad Request`

Are you sure the limit above applies to base64 encoded attachments?

**Comment by vinodjoseph62** [comment]
Same here , I am using a 254kb image file
Getting the error as 
Error: Request to 'https://skype.botframework.com/v3/conversations/29%3A1awJOwTjcsaihhjqTbDzJHjbjJujcbCXb/activities' failed: [400] Bad Request
    at Request._callback (C:\VINOD\Projects\test\node_modules\botbuilder\lib\bots\ChatConnector.js:413:46)
    at Request.self.callback (C:\VINOD\Projects\test\node_modules\botbuilder\node_modules\request\request.js:186:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\VINOD\Projects\test\node_modules\botbuilder\node_modules\request\request.js:1081:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\VINOD\Projects\test\node_modules\botbuilder\node_modules\request\request.js:1001:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:921:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
